      *{TOTEM}PRG-COMMENT
      * garticoli.Cbl
      * garticoli.Cbl is generated by TOTEM
      * This is a generated file. DO NOT modify this file directly.
      *{TOTEM}END
       IDENTIFICATION       DIVISION.
      *{TOTEM}PRGID
       PROGRAM-ID.          garticoli.
       AUTHOR.              Andrea.
       DATE-WRITTEN.        giovedì 1 novembre 2012 13:21:14.
       REMARKS.
      *{TOTEM}END

       ENVIRONMENT          DIVISION.
       CONFIGURATION        SECTION.
       SPECIAL-NAMES.
      *{TOTEM}SPECIAL-NAME
      * <TOTEM:EPT. INIT:garticoli, INIT:garticoli, SpecialName>
      * <TOTEM:END>
      *{TOTEM}END
      *{TOTEM}ACTIVEX-DEF
      *{TOTEM}END
      *{TOTEM}DECIMAL-POINT
           DECIMAL-POINT IS COMMA.
      *{TOTEM}END

       INPUT-OUTPUT         SECTION.
       FILE-CONTROL.
      *{TOTEM}FILE-CONTROL
           COPY "articoli.sl".
      *{TOTEM}END
       DATA                 DIVISION.
       FILE                 SECTION.
      *{TOTEM}FILE
           COPY "articoli.fd".
      *{TOTEM}END

       WORKING-STORAGE      SECTION.
      *{TOTEM}ACU-DEF
               COPY "acugui.def".
               COPY "acucobol.def".
               COPY "fonts.def".
               COPY "crtvars.def".
               COPY "showmsg.def".
               COPY "totem.def".
               COPY "comune.def".
               COPY "custom.def".
               COPY "UTYDATA.DEF".
      *{TOTEM}END

      *{TOTEM}COPY-WORKING
      * Key Status
       77 Key-Status IS SPECIAL-NAMES CRT STATUS PIC 9(5) VALUE 0.
          88 Enter-Pushed VALUE 13.
          88 Exit-Pushed VALUE 27.
          88 Message-Received VALUE 95.
          88 Event-Occurred VALUE 96.
          88 Screen-No-Input-Field VALUE 97.
          88 Screen-Time-Out VALUE 99.
      * Properties & User defined Working Stoarge
       78 titolo VALUE IS "Studio - Gestione articoli". 
       77 como-numero      PIC  9(12)v99.
       77 Form1-Tb-1-Handle
                  USAGE IS HANDLE OF WINDOW.
       77 toolbar-bmp      PIC  S9(9)
                  USAGE IS COMP-4
                  VALUE IS 0.
       77 E-ESCI           PIC  9
                  VALUE IS 1.
       77 E-NUOVO          PIC  9
                  VALUE IS 1.
       77 E-CANCELLA       PIC  9
                  VALUE IS 1.
       77 E-SALVA          PIC  9
                  VALUE IS 1.
       77 E-ANTEPRIMA      PIC  9
                  VALUE IS 0.
       77 E-MODIFICA       PIC  9
                  VALUE IS 1.
       77 E-STAMPA         PIC  9
                  VALUE IS 0.
       77 E-CERCA          PIC  9
                  VALUE IS 0.
       77 E-SELEZIONA      PIC  9
                  VALUE IS 1.
       77 Small-Font
                  USAGE IS HANDLE OF FONT SMALL-FONT.
       77 Default-Font
                  USAGE IS HANDLE OF FONT DEFAULT-FONT.
       77 Form1-St-1-Handle
                  USAGE IS HANDLE OF STATUS-BAR.
       77 form1-Handle
                  USAGE IS HANDLE OF WINDOW.
       01 save-key.
           05 save-codice      PIC  x(6).
       01 save-key-1.
           05 save-ragsoc-1    PIC  x(50).
       77 STATUS-articoli  PIC  X(2).
           88 Valid-STATUS-articoli VALUE IS "00" THRU "09". 
       77 AUTO-ID          PIC  9(6)
                  VALUE IS 0.
       77 Calibri14-Occidentale
                  USAGE IS HANDLE OF FONT.
       77 Screen1-Bt-1-Handle          PIC  S9(9)
                  USAGE IS COMP-4
                  VALUE IS 0.
       77 Calibri14B-Occidentale
                  USAGE IS HANDLE OF FONT.
       77 LOGO-PICCOLO-BMP PIC  S9(9)
                  USAGE IS COMP-4
                  VALUE IS 0.

      ***********************************************************
      *   Code Gen's Buffer                                     *
      ***********************************************************
       77 STATUS-Form1-FLAG-REFRESH PIC  9.
          88 Form1-FLAG-REFRESH  VALUE 1 FALSE 0. 
      * DATA CONTROL BUFFER
       01 Form1-BUF.
      * Data.Entry-Field
              05 ef-codice-BUF PIC x(6).
      * Data.Entry-Field
              05 ef-descr-BUF PIC x(50).
              05 ef-descr-VALUEBUF PIC x(50).
      * Data.Entry-Field
              05 ef-note-BUF PIC x(200).

       77 TMP-Form1-KEY1-ORDER  PIC X VALUE "A".
       77 TMP-Form1-KEY2-ORDER  PIC X VALUE "A".
       77 TMP-Form1-articoli-RESTOREBUF  PIC X(810).
       77 TMP-Form1-KEYIS  PIC 9(3) VALUE 1.
       77 Form1-MULKEY-TMPBUF   PIC X(810).
       77 Form1-KEYISTMP2   PIC X(56).
      * Form1 : PKEY & AKEY'S TEMP BUFFER
       77 Form1-PKEYTMP   PIC X(6).
       77 TMP-DataSet1-articoli-BUF     PIC X(810).
      * VARIABLES FOR RECORD LENGTH.
       77  TotemFdSlRecordClearOffset   PIC 9(5) COMP-4.
       77  TotemFdSlRecordLength        PIC 9(5) COMP-4.
      * FILE'S LOCK MODE FLAG
       77 DataSet1-articoli-LOCK-FLAG   PIC X VALUE SPACE.
           88 DataSet1-articoli-LOCK  VALUE "Y".
       77 DataSet1-KEYIS   PIC 9(3) VALUE 1.
       77 DataSet1-articoli-KEY1-ORDER  PIC X VALUE "A".
          88 DataSet1-articoli-KEY1-Asc  VALUE "A".
          88 DataSet1-articoli-KEY1-Desc VALUE "D".
       77 DataSet1-articoli-KEY2-ORDER  PIC X VALUE "A".
          88 DataSet1-articoli-KEY2-Asc  VALUE "A".
          88 DataSet1-articoli-KEY2-Desc VALUE "D".

       77 articoli-art-k-descrizione-SPLITBUF  PIC X(57).
      * FOR SPLIT KEY BUFFER
       77 DataSet1-articoli-SPLIT-BUF2   PIC X(57).


       01 OLD-art-rec.
           05 OLD-art-chiave.
               10 OLD-art-codice       PIC  x(6).
           05 OLD-art-dati.
               10 OLD-art-descrizione  PIC  x(50).
               10 OLD-art-note         PIC  x(200).
               10 OLD-art-vuoti.
                   15 FILLER           PIC  9(18).
                   15 FILLER           PIC  9(18).
                   15 FILLER           PIC  9(18).
                   15 FILLER           PIC  x(500).
      *{TOTEM}END

      *{TOTEM}ID-LOGICI
      ***** Elenco ID Logici *****
       78  78-ID-ef-codice VALUE 5001.
       78  78-ID-ef-descr VALUE 5002.
       78  78-ID-ef-note VALUE 5003.
      ***** Fine ID Logici *****
      *{TOTEM}END

       LINKAGE          SECTION.
      *{TOTEM}LINKAGE
           COPY  "BLOCKPGM.LKS".

      *{TOTEM}END

       SCREEN           SECTION.
      *{TOTEM}COPY-SCREEN
      * FORM
       01 
           Form1, 
           AFTER PROCEDURE Form1-AfterProcedure,
           BEFORE PROCEDURE Form1-BeforeProcedure,
           .

      * ENTRY FIELD
       05
           ef-codice, 
           Entry-Field, 
           COL 14,00, 
           LINE 1,50,
           LINES 1,30 ,
           SIZE 10,00 ,
           BOXED,
           COLOR IS 513,
           ENABLED mod-k,
           ID IS 78-ID-ef-codice,                
           HEIGHT-IN-CELLS,
           WIDTH-IN-CELLS,
           LEFT,
           MAX-TEXT 6,
           VALUE ef-codice-BUF,
           .

      * LABEL
       05
           Screen1-La-1, 
           Label, 
           COL 2,90, 
           LINE 1,50,
           LINES 1,30 ,
           SIZE 10,00 ,
           ID IS 100,
           HEIGHT-IN-CELLS,
           WIDTH-IN-CELLS,
           TRANSPARENT,
           TITLE "Codice",
           .

      * LABEL
       05
           Screen1-Custom1-1, 
           Label, 
           COL 84,86, 
           LINE 1,00,
           LINES 0,69 ,
           SIZE 3,29 ,
           FONT IS Default-Font,
           ID IS 18,
           TRANSPARENT,
           TITLE "CUSTOM CONTROL",
           VISIBLE v-custom,
           .

      * LABEL
       05
           Screen1-blockpgm-2, 
           Label, 
           COL 85,71, 
           LINE 2,62,
           LINES 1,00 ,
           SIZE 2,43 ,
           ID IS 21,
           HEIGHT-IN-CELLS,
           WIDTH-IN-CELLS,
           TRANSPARENT,
           TITLE "BlockPgm",
           VISIBLE v-custom,
           .

      * BAR
       05
           Screen1-Br-1, 
           Bar,
           COL 1,00, 
           LINE 3,35,
           SIZE 88,50 ,
           ID IS 22,
           HEIGHT-IN-CELLS,
           WIDTH-IN-CELLS,
           COLORS (9, 9),
           WIDTH 2,
           .

      * ENTRY FIELD
       05
           ef-descr, 
           Entry-Field, 
           COL 14,00, 
           LINE 4,00,
           LINES 1,30 ,
           SIZE 72,00 ,
           BOXED,
           COLOR IS 513,
           ENABLED MOD,
           ID IS 78-ID-ef-descr,                
           HEIGHT-IN-CELLS,
           WIDTH-IN-CELLS,
           LEFT,
           MAX-TEXT 50,
           VALUE ef-descr-BUF,
           .

      * LABEL
       05
           Screen1-La-2, 
           Label, 
           COL 2,90, 
           LINE 4,00,
           LINES 1,30 ,
           SIZE 10,00 ,
           ID IS 33,
           HEIGHT-IN-CELLS,
           WIDTH-IN-CELLS,
           TRANSPARENT,
           TITLE "Descrizione",
           .

      * ENTRY FIELD
       05
           ef-note, 
           Entry-Field, 
           COL 14,00, 
           LINE 6,00,
           LINES 7,43 ,
           SIZE 73,70 ,
           BOXED,
           COLOR IS 513,
           ENABLED MOD,
           ID IS 78-ID-ef-note,                
           HEIGHT-IN-CELLS,
           WIDTH-IN-CELLS,
           MAX-TEXT 200,
           VSCROLL-BAR,
           USE-RETURN,
           VALUE ef-note-BUF,
           .
      * LABEL
       05
           Screen1-La-2a, 
           Label, 
           COL 2,90, 
           LINE 6,00,
           LINES 1,30 ,
           SIZE 10,00 ,
           ID IS 8,
           HEIGHT-IN-CELLS,
           WIDTH-IN-CELLS,
           TRANSPARENT,
           TITLE "Note",
           .

      * TOOLBAR
       01
           Form1-Tb-1,
           .    

      * PUSH BUTTON
       05
           TOOL-ESCI, 
           Push-Button, 
           COL 1,00, 
           LINE 1,09,
           LINES 64,00 ,
           SIZE 48,00 ,
           BITMAP-HANDLE toolbar-bmp,
           BITMAP-NUMBER 1,
           FRAMED,
           SQUARE,
           ENABLED E-ESCI,
           EXCEPTION-VALUE 27,
           FLAT,
           FONT IS Calibri14-Occidentale,
           ID IS 72,
           SELF-ACT,
           ESCAPE-BUTTON,
           TITLE "Esci (Esc)",
           .

      * PUSH BUTTON
       05
           TOOL-NUOVO, 
           Push-Button, 
           COL 6,30, 
           LINE 1,09,
           LINES 64,00 ,
           SIZE 48,00 ,
           BITMAP-HANDLE toolbar-bmp,
           FRAMED,
           SQUARE,
           ENABLED E-NUOVO,
           EXCEPTION-VALUE 2,
           FLAT,
           FONT IS Calibri14-Occidentale,
           ID IS 73,
           SELF-ACT,
           TITLE "Nuovo (F2)",
           BITMAP-NUMBER BitmapNumNew
           .

      * PUSH BUTTON
       05
           TOOL-CANCELLA, 
           Push-Button, 
           COL 16,90, 
           LINE 1,09,
           LINES 64,00 ,
           SIZE 48,00 ,
           BITMAP-HANDLE toolbar-bmp,
           FRAMED,
           SQUARE,
           ENABLED E-CANCELLA,
           EXCEPTION-VALUE 4,
           FLAT,
           FONT IS Calibri14-Occidentale,
           ID IS 74,
           SELF-ACT,
           TITLE "Cancella (F4)",
           BITMAP-NUMBER BitmapNumDelete
           .

      * PUSH BUTTON
       05
           TOOL-SALVA, 
           Push-Button, 
           COL 11,60, 
           LINE 1,09,
           LINES 64,00 ,
           SIZE 48,00 ,
           BITMAP-HANDLE toolbar-bmp,
           FRAMED,
           SQUARE,
           ENABLED E-SALVA,
           EXCEPTION-VALUE 3,
           FLAT,
           FONT IS Calibri14-Occidentale,
           ID IS 75,
           SELF-ACT,
           TITLE "Salva (F3)",
           BITMAP-NUMBER BitmapNumSave
           .

      * PUSH BUTTON
       05
           TOOL-ANTEPRIMA, 
           Push-Button, 
           COL 27,40, 
           LINE 1,09,
           LINES 64,00 ,
           SIZE 48,00 ,
           BITMAP-HANDLE toolbar-bmp,
           BITMAP-NUMBER 6,
           FRAMED,
           SQUARE,
           ENABLED 1,
           EXCEPTION-VALUE 6,
           FLAT,
           FONT IS Calibri14-Occidentale,
           ID IS 76,
           SELF-ACT,
           TITLE "Anteprima (F6)",
           .

      * CHECK BOX
       05
           TOOL-MODIFICA, 
           Check-Box, 
           COL 22,10, 
           LINE 1,09,
           LINES 64,00 ,
           SIZE 48,00 ,
           BITMAP-HANDLE toolbar-bmp,
           BITMAP-NUMBER 5,
           FRAMED,
           SQUARE,
           ENABLED E-MODIFICA,
           EXCEPTION-VALUE 150
           FLAT,
           FONT IS Calibri14-Occidentale,
           ID IS 77,
           SELF-ACT,
           TITLE "Modifica (F5)",
           VALUE MOD,
           BITMAP-NUMBER BitmapNumEdit
           AFTER PROCEDURE TOOL-MODIFICA-AfterProcedure,
           BEFORE PROCEDURE TOOL-MODIFICA-BeforeProcedure, 
           .
      * PUSH BUTTON
       05
           TOOL-STAMPA, 
           Push-Button, 
           COL 32,70, 
           LINE 1,09,
           LINES 64,00 ,
           SIZE 48,00 ,
           BITMAP-HANDLE toolbar-bmp,
           BITMAP-NUMBER 7,
           FRAMED,
           SQUARE,
           ENABLED 1,
           EXCEPTION-VALUE 7,
           FLAT,
           FONT IS Calibri14-Occidentale,
           ID IS 110,
           SELF-ACT,
           TITLE "Stampa (F7)",
           .

      * PUSH BUTTON
       05
           TOOL-CERCA, 
           Push-Button, 
           COL 38,00, 
           LINE 1,09,
           LINES 64,00 ,
           SIZE 48,00 ,
           BITMAP-HANDLE toolbar-bmp,
           FRAMED,
           SQUARE,
           ENABLED E-CERCA,
           EXCEPTION-VALUE 8,
           FLAT,
           FONT IS Calibri14-Occidentale,
           ID IS 111,
           SELF-ACT,
           TITLE "Cerca (F8)",
           BITMAP-NUMBER BitmapNumZoom
           .

      * PUSH BUTTON
       05
           TOOL-SELEZIONA, 
           Push-Button, 
           COL 43,30, 
           LINE 1,09,
           LINES 64,00 ,
           SIZE 48,00 ,
           BITMAP-HANDLE toolbar-bmp,
           BITMAP-NUMBER 9,
           FRAMED,
           SQUARE,
           ENABLED E-SELEZIONA,
           EXCEPTION-VALUE 9,
           FLAT,
           FONT IS Calibri14-Occidentale,
           ID IS 112,
           SELF-ACT,
           TITLE "Seleziona (F9)",
           .

      * PUSH BUTTON
       05
           Form1-Pb-1a, 
           Push-Button, 
           COL 48,60, 
           LINE 1,09,
           LINES 64,00 ,
           SIZE 48,00 ,
           BITMAP-HANDLE toolbar-bmp,
           BITMAP-NUMBER 10,
           FRAMED,
           SQUARE,
           EXCEPTION-VALUE 1002,
           FLAT,
           FONT IS Calibri14-Occidentale,
           ID IS 113,
           SELF-ACT,
           TITLE "&Primo",
           .

      * PUSH BUTTON
       05
           Form1-Pb-1b, 
           Push-Button, 
           COL 53,90, 
           LINE 1,09,
           LINES 64,00 ,
           SIZE 48,00 ,
           BITMAP-HANDLE toolbar-bmp,
           BITMAP-NUMBER 11,
           FRAMED,
           SQUARE,
           EXCEPTION-VALUE 67,
           FLAT,
           FONT IS Calibri14-Occidentale,
           ID IS 114,
           SELF-ACT,
           TITLE "Precedente (PgDn)",
           .

      * PUSH BUTTON
       05
           Form1-Pb-1c, 
           Push-Button, 
           COL 59,20, 
           LINE 1,09,
           LINES 64,00 ,
           SIZE 48,00 ,
           BITMAP-HANDLE toolbar-bmp,
           BITMAP-NUMBER 12,
           FRAMED,
           SQUARE,
           EXCEPTION-VALUE 68,
           FLAT,
           FONT IS Calibri14-Occidentale,
           ID IS 115,
           SELF-ACT,
           TITLE "Successivo (PgUp)",
           .

      * PUSH BUTTON
       05
           Form1-Pb-1d, 
           Push-Button, 
           COL 64,50, 
           LINE 1,09,
           LINES 64,00 ,
           SIZE 48,00 ,
           BITMAP-HANDLE toolbar-bmp,
           BITMAP-NUMBER 13,
           FRAMED,
           SQUARE,
           EXCEPTION-VALUE 1006,
           FLAT,
           FONT IS Calibri14-Occidentale,
           ID IS 116,
           SELF-ACT,
           TITLE "&Ultimo",
           .

      * CHECK BOX
       05
           TOOL-ORD, 
           Check-Box, 
           COL 69,80, 
           LINE 1,09,
           LINES 64,00 ,
           SIZE 48,00 ,
           BITMAP-HANDLE toolbar-bmp,
           BITMAP-NUMBER 14,
           UNFRAMED,
           SQUARE,
           EXCEPTION-VALUE 1001
           FLAT,
           FONT IS Calibri14-Occidentale,
           ID IS 122,
           SELF-ACT,
           TITLE "Ordinamento Alfabetico (F10)",
           VALUE OrderBy,
           AFTER PROCEDURE TOOL-ORD-AfterProcedure,
           BEFORE PROCEDURE TOOL-ORD-BeforeProcedure, 
           .
      * BITMAP
       05
           Form1-Bt-1, 
           Bitmap, 
           COL 84,40, 
           LINE 1,00,
           LINES 64,00 ,
           SIZE 48,00 ,
           BITMAP-HANDLE LOGO_PICCOLO-BMP,
           BITMAP-NUMBER 1,
           ID IS 123,
           .

      *{TOTEM}END

      *{TOTEM}LINKPARA
       PROCEDURE  DIVISION USING LK-BLOCKPGM.
      *{TOTEM}END

      *{TOTEM}DECLARATIVE
       DECLARATIVES.
      * <TOTEM:EPT. INIT:garticoli, INIT:garticoli, BeforeDeclarative>
       FILE-ERROR SECTION.
           use after error procedure on articoli.
           set RecLocked to false.
           evaluate status-articoli
           when "35"
                display message "File [articoli] not found!"
                           title titolo
                            icon 3
                set errori to true
           when "39"
                display message "File [articoli] Mismatch size!"
                           title titolo
                            icon 3
                set errori to true
           when "98"
                display message "[articoli] Indexed file corrupt!"
                           title titolo
                            icon 3
                set errori to true
           when "99"
           when "93"
                set RecLocked to true
                set errori    to true
                move 0 to mod
                modify tool-modifica, value = mod
                move 1 to mod-k
                display form1
                set StatusVisua to true
                perform STATUS-BAR-MSG
                move "00" to status-articoli
                if ReadSecca
                   read articoli     no lock 
                        invalid      continue
                        not invalid  perform FORM1-IUD-DISPLAY
                   end-read
                end-if
                display message box MSG-Record-gia-in-uso
                        title = tit-err
                        icon is mb-error-icon
           when "23"
                move 1 to mod-k
                move 0 to mod
                modify tool-modifica, value = mod
                set StatusVisua to true
                perform STATUS-BAR-MSG 
                if nuovo              
                   initialize art-dati replacing numeric data by zeroes
                                            alphanumeric data by spaces
                   perform FORM1-FLD-TO-BUF
                   display form1-tb-1
                   set vecchio to true
                end-if      
                perform ABILITAZIONI
                display form1
                |RISETTO IL VALORE A "23" PERCHE DENTRO AL PAR. CLEAR-SCREEN
                |CON L'OPERAZIONE UNLOCK VIENE RISETTATO A ZERO COSICCHÈ 
                |QUANDO TORNA DENTRO AI PAR. DI SCORRIMENTO DI TOTEM SI 
                |TROVA IN UNA SITUAZIONE CORRETTA E PROSEGUE CON LA READ
                |USCENDO CON UN MESSAGGIO DI ERRORE DI TIPO "46"
                move "23" to status-articoli
           end-evaluate.

      * <TOTEM:END>
       INPUT-ERROR SECTION.
           USE AFTER STANDARD ERROR PROCEDURE ON INPUT.
       0100-DECL.
           EXIT.
       I-O-ERROR SECTION.
           USE AFTER STANDARD ERROR PROCEDURE ON I-O.
       0200-DECL.
           EXIT.
       OUTPUT-ERROR SECTION.
           USE AFTER STANDARD ERROR PROCEDURE ON OUTPUT.
       0300-DECL.
           EXIT.
       TRANSACTION-ERROR SECTION.
           USE AFTER STANDARD ERROR PROCEDURE ON TRANSACTION.
       0400-DECL.
           EXIT.
       END DECLARATIVES.
      *{TOTEM}END

       MAIN-LOGIC.
      *{TOTEM}ENTRY-BEFPRG
      *    Before-Program
           PERFORM ginqui-Ev-Before-Program
      *{TOTEM}END
           PERFORM INITIALIZE-ROUTINE.
      * run main screen
      *{TOTEM}RUN-MAINSCR
           PERFORM Form1-OPEN-ROUTINE.
      *{TOTEM}END

      *{TOTEM}COPY-PROCEDURE
       EXIT-STOP-ROUTINE.
           PERFORM CLOSE-FILE-RTN
      * <TOTEM:EPT. INIT:garticoli, INIT:garticoli, BeforeDestroyResource>
      * <TOTEM:END>
           DESTROY Calibri14-Occidentale
           CALL "w$bitmap" USING WBITMAP-DESTROY, toolbar-bmp
           CALL "w$bitmap" USING WBITMAP-DESTROY, LOGO_PICCOLO-BMP
      *    After-Program
           PERFORM ginqui-Ev-After-Program
           EXIT PROGRAM TOTEM-PgmStatus
           STOP RUN.

       INITIALIZE-ROUTINE.
      *    Before Init
      * initialize program status variable
           Initialize TOTEM-PgmStatus.
      * get system information
           ACCEPT SYSTEM-INFORMATION FROM SYSTEM-INFO.
      * get terminal information
           ACCEPT TERMINAL-ABILITIES FROM TERMINAL-INFO.
      * set font
           PERFORM INIT-FONT.
      * load bitmap
           PERFORM INIT-BMP.
      * load resource
           PERFORM INIT-RES.
      * create pop-up menu
           PERFORM INIT-POPUP.
      * open files
           PERFORM OPEN-FILE-RTN.
      *    After Init
           .
    
       INIT-FONT.
      * Calibri14-Occidentale
           INITIALIZE WFONT-DATA Calibri14-Occidentale
           MOVE 14 TO WFONT-SIZE
           MOVE "Calibri" TO WFONT-NAME
           SET WFCHARSET-DONT-CARE TO TRUE
           SET WFONT-BOLD TO FALSE
           SET WFONT-ITALIC TO FALSE
           SET WFONT-UNDERLINE TO FALSE
           SET WFONT-STRIKEOUT TO FALSE
           SET WFONT-FIXED-PITCH TO FALSE
           MOVE 0 TO WFONT-CHAR-SET
           CALL "W$FONT" USING WFONT-GET-FONT, 
                     Calibri14-Occidentale, WFONT-DATA
           .

       INIT-BMP.
      * TOOL-ESCI
           COPY RESOURCE "toolbar.bmp".
           CALL "w$bitmap" USING WBITMAP-LOAD "toolbar.bmp", 
                   GIVING toolbar-bmp.
      * Form1-Bt-1
           COPY RESOURCE "LOGO_PICCOLO.BMP".
           CALL "w$bitmap" USING WBITMAP-LOAD "LOGO_PICCOLO.BMP", 
                   GIVING LOGO_PICCOLO-BMP.
           .

       INIT-RES.
           .

       INIT-POPUP.
           .

       OPEN-FILE-RTN.
      *    Before Open
           PERFORM OPEN-articoli
      *    After Open
           .

       OPEN-articoli.
      * <TOTEM:EPT. INIT:garticoli, FD:articoli, BeforeOpen>
      * <TOTEM:END>
           OPEN  I-O articoli
           IF STATUS-articoli = "35"
              OPEN OUTPUT articoli
                IF Valid-STATUS-articoli
                   CLOSE articoli
                   OPEN I-O articoli
                END-IF
           END-IF
           IF NOT Valid-STATUS-articoli
              PERFORM  Form1-EXTENDED-FILE-STATUS
              GO TO EXIT-STOP-ROUTINE
           END-IF
      * <TOTEM:EPT. INIT:garticoli, FD:articoli, AfterOpen>
      * <TOTEM:END>
           .

       CLOSE-FILE-RTN.
      *    Before Close
           PERFORM CLOSE-articoli
      *    After Close
           .

       CLOSE-articoli.
      * <TOTEM:EPT. INIT:garticoli, FD:articoli, BeforeClose>
      * <TOTEM:END>
           CLOSE articoli
           .

       articoli-art-k-descrizione-MERGE-SPLITBUF.
           INITIALIZE articoli-art-k-descrizione-SPLITBUF
           MOVE art-descrizione(1:50) TO 
           articoli-art-k-descrizione-SPLITBUF(1:50)
           MOVE art-chiave(1:6) TO 
           articoli-art-k-descrizione-SPLITBUF(51:6)
           .

       DataSet1-articoli-INITSTART.
           EVALUATE DataSet1-KEYIS
           WHEN 1
              IF DataSet1-articoli-KEY1-Asc
                 MOVE Low-Value TO art-chiave
              ELSE
                 MOVE High-Value TO art-chiave
              END-IF
           WHEN 2
              IF DataSet1-articoli-KEY2-Asc
                 MOVE Low-Value TO art-descrizione
              ELSE
                 MOVE High-Value TO art-descrizione
              END-IF
              IF DataSet1-articoli-KEY2-Asc
                 MOVE Low-Value TO art-chiave
              ELSE
                 MOVE High-Value TO art-chiave
              END-IF
           END-EVALUATE
           .

       DataSet1-articoli-INITEND.
           EVALUATE DataSet1-KEYIS
           WHEN 1
              IF DataSet1-articoli-KEY1-Asc
                 MOVE High-Value TO art-chiave
              ELSE
                 MOVE Low-Value TO art-chiave
              END-IF
           WHEN 2
              IF DataSet1-articoli-KEY2-Asc
                 MOVE High-Value to art-descrizione
              ELSE          
                 MOVE Low-Value to art-descrizione
              END-IF
              IF DataSet1-articoli-KEY2-Asc
                 MOVE High-Value to art-chiave
              ELSE          
                 MOVE Low-Value to art-chiave
              END-IF
           END-EVALUATE
           .

       DataSet1-articoli-TMPBUF-TO-FLD.
           EVALUATE DataSet1-KEYIS
           WHEN 2
              MOVE DataSet1-articoli-SPLIT-BUF2(1:50) TO
                   art-descrizione(1:50)
              MOVE DataSet1-articoli-SPLIT-BUF2(51:6) TO
                   art-chiave(1:6)
           END-EVALUATE
           .

       DataSet1-articoli-FLD-TO-TMPBUF.
           EVALUATE DataSet1-KEYIS
           WHEN 2
              MOVE art-descrizione(1:50) TO
                   DataSet1-articoli-SPLIT-BUF2(1:50)
              MOVE art-chiave(1:6) TO
                   DataSet1-articoli-SPLIT-BUF2(51:6)
           END-EVALUATE
           .

       DataSet1-CHANGETO-KEY1.
           MOVE 1 TO DataSet1-KEYIS
           .   

       DataSet1-CHANGETO-KEY2.
           MOVE 2 TO DataSet1-KEYIS
           .   

       DataSet1-Change-CurrentKey-Asc.
           EVALUATE DataSet1-KEYIS
           WHEN 1
              MOVE "A" TO DataSet1-articoli-KEY1-ORDER
           WHEN 2
              MOVE "A" TO DataSet1-articoli-KEY2-ORDER
           END-EVALUATE
           .

       DataSet1-Change-CurrentKey-Desc.
           EVALUATE DataSet1-KEYIS
           WHEN 1
              MOVE "D" TO DataSet1-articoli-KEY1-ORDER
           WHEN 2
              MOVE "D" TO DataSet1-articoli-KEY2-ORDER
           END-EVALUATE
           .

      * articoli
       DataSet1-articoli-START.
           EVALUATE DataSet1-KEYIS
           WHEN 1
              IF DataSet1-articoli-KEY1-Asc
                 START articoli KEY >= art-chiave
              ELSE
                 START articoli KEY <= art-chiave
              END-IF
           WHEN 2
              IF DataSet1-articoli-KEY2-Asc
                 START articoli KEY >= art-k-descrizione
              ELSE
                 START articoli KEY <= art-k-descrizione
              END-IF
           END-EVALUATE
           .

       DataSet1-articoli-START-NOTGREATER.
           EVALUATE DataSet1-KEYIS
           WHEN 1
              IF DataSet1-articoli-KEY1-Asc
                 START articoli KEY <= art-chiave
              ELSE
                 START articoli KEY >= art-chiave
              END-IF
           WHEN 2
              IF DataSet1-articoli-KEY2-Asc
                 START articoli KEY <= art-k-descrizione
              ELSE
                 START articoli KEY >= art-k-descrizione
              END-IF
           END-EVALUATE
           .

       DataSet1-articoli-START-GREATER.
           EVALUATE DataSet1-KEYIS
           WHEN 1
              IF DataSet1-articoli-KEY1-Asc
                 START articoli KEY > art-chiave
              ELSE
                 START articoli KEY < art-chiave
              END-IF
           WHEN 2
              IF DataSet1-articoli-KEY2-Asc
                 START articoli KEY > art-k-descrizione
              ELSE
                 START articoli KEY < art-k-descrizione
              END-IF
           END-EVALUATE
           .

       DataSet1-articoli-START-LESS.
           EVALUATE DataSet1-KEYIS
           WHEN 1
              IF DataSet1-articoli-KEY1-Asc
                 START articoli KEY < art-chiave
              ELSE
                 START articoli KEY > art-chiave
              END-IF
           WHEN 2
              IF DataSet1-articoli-KEY2-Asc
                 START articoli KEY < art-k-descrizione
              ELSE
                 START articoli KEY > art-k-descrizione
              END-IF
           END-EVALUATE
           .

       DataSet1-articoli-START-EQUAL.
           EVALUATE DataSet1-KEYIS
           WHEN 2
              START articoli KEY = art-k-descrizione
           END-EVALUATE
           .

       DataSet1-articoli-Read.
      * <TOTEM:EPT. FD:DataSet1, FD:articoli, BeforeRead>
      * <TOTEM:END>
      * <TOTEM:EPT. FD:DataSet1, FD:articoli, BeforeReadRecord>
      * <TOTEM:END>
           EVALUATE DataSet1-KEYIS
           WHEN 1
              IF DataSet1-articoli-LOCK
                 READ articoli WITH LOCK 
                 KEY art-chiave
              ELSE
                 READ articoli WITH NO LOCK 
                 KEY art-chiave
              END-IF
           WHEN 2
              IF DataSet1-articoli-LOCK
                 READ articoli WITH LOCK 
                 KEY art-k-descrizione
              ELSE
                 READ articoli WITH NO LOCK 
                 KEY art-k-descrizione
              END-IF
           END-EVALUATE
           PERFORM articoli-art-k-descrizione-MERGE-SPLITBUF
           MOVE STATUS-articoli TO TOTEM-ERR-STAT 
           MOVE "articoli" TO TOTEM-ERR-FILE
           MOVE "READ" TO TOTEM-ERR-MODE
      * <TOTEM:EPT. FD:DataSet1, FD:articoli, AfterRead>
      * <TOTEM:END>
      * <TOTEM:EPT. FD:DataSet1, FD:articoli, AfterReadRecord>
      * <TOTEM:END>
           .

       DataSet1-articoli-Read-Next.
      * <TOTEM:EPT. FD:DataSet1, FD:articoli, BeforeRead>
      * <TOTEM:END>
      * <TOTEM:EPT. FD:DataSet1, FD:articoli, BeforeReadNext>
      * <TOTEM:END>
           EVALUATE DataSet1-KEYIS
           WHEN 1
              IF DataSet1-articoli-KEY1-Asc
                 IF DataSet1-articoli-LOCK
                    READ articoli NEXT WITH LOCK
                 ELSE
                    READ articoli NEXT WITH NO LOCK
                 END-IF
              ELSE
                 IF DataSet1-articoli-LOCK
                    READ articoli PREVIOUS WITH LOCK
                 ELSE
                    READ articoli PREVIOUS WITH NO LOCK
                 END-IF
              END-IF
           WHEN 2
              IF DataSet1-articoli-KEY2-Asc
                 IF DataSet1-articoli-LOCK
                    READ articoli NEXT WITH LOCK
                 ELSE
                    READ articoli NEXT WITH NO LOCK
                 END-IF
              ELSE
                 IF DataSet1-articoli-LOCK
                    READ articoli PREVIOUS WITH LOCK
                 ELSE
                    READ articoli PREVIOUS WITH NO LOCK
                 END-IF
              END-IF
           END-EVALUATE
           PERFORM articoli-art-k-descrizione-MERGE-SPLITBUF
           MOVE STATUS-articoli TO TOTEM-ERR-STAT
           MOVE "articoli" TO TOTEM-ERR-FILE
           MOVE "READ NEXT" TO TOTEM-ERR-MODE
      * <TOTEM:EPT. FD:DataSet1, FD:articoli, AfterRead>
      * <TOTEM:END>
      * <TOTEM:EPT. FD:DataSet1, FD:articoli, AfterReadNext>
      * <TOTEM:END>
           .

       DataSet1-articoli-Read-Prev.
      * <TOTEM:EPT. FD:DataSet1, FD:articoli, BeforeRead>
      * <TOTEM:END>
      * <TOTEM:EPT. FD:DataSet1, FD:articoli, BeforeReadPrev>
      * <TOTEM:END>
           EVALUATE DataSet1-KEYIS
           WHEN 1
              IF DataSet1-articoli-KEY1-Asc
                 IF DataSet1-articoli-LOCK
                    READ articoli PREVIOUS WITH LOCK
                 ELSE
                    READ articoli PREVIOUS WITH NO LOCK
                 END-IF
              ELSE
                 IF DataSet1-articoli-LOCK
                    READ articoli NEXT WITH LOCK
                 ELSE
                    READ articoli NEXT WITH NO LOCK
                 END-IF
              END-IF
           WHEN 2
              IF DataSet1-articoli-KEY2-Asc
                 IF DataSet1-articoli-LOCK
                    READ articoli PREVIOUS WITH LOCK
                 ELSE
                    READ articoli PREVIOUS WITH NO LOCK
                 END-IF
              ELSE
                 IF DataSet1-articoli-LOCK
                    READ articoli NEXT WITH LOCK
                 ELSE
                    READ articoli NEXT WITH NO LOCK
                 END-IF
              END-IF
           END-EVALUATE
           PERFORM articoli-art-k-descrizione-MERGE-SPLITBUF
           MOVE STATUS-articoli TO TOTEM-ERR-STAT
           MOVE "articoli" TO TOTEM-ERR-FILE
           MOVE "READ PREVIOUS" TO TOTEM-ERR-MODE
      * <TOTEM:EPT. FD:DataSet1, FD:articoli, AfterRead>
      * <TOTEM:END>
      * <TOTEM:EPT. FD:DataSet1, FD:articoli, AfterReadPrev>
      * <TOTEM:END>
           .

       DataSet1-articoli-Rec-Write.
      * <TOTEM:EPT. FD:DataSet1, FD:articoli, BeforeWrite>
      * <TOTEM:END>
           WRITE art-rec OF articoli.
           MOVE STATUS-articoli TO TOTEM-ERR-STAT
           MOVE "articoli" TO TOTEM-ERR-FILE
           MOVE "WRITE" TO TOTEM-ERR-MODE
      * <TOTEM:EPT. FD:DataSet1, FD:articoli, AfterWrite>
      * <TOTEM:END>
           .

       DataSet1-articoli-Rec-Rewrite.
      * <TOTEM:EPT. FD:DataSet1, FD:articoli, BeforeRewrite>
      * <TOTEM:END>
           REWRITE art-rec OF articoli.
           MOVE STATUS-articoli TO TOTEM-ERR-STAT
           MOVE "articoli" TO TOTEM-ERR-FILE
           MOVE "REWRITE" TO TOTEM-ERR-MODE
      * <TOTEM:EPT. FD:DataSet1, FD:articoli, AfterRewrite>
      * <TOTEM:END>
           .

       DataSet1-articoli-Rec-Delete.
      * <TOTEM:EPT. FD:DataSet1, FD:articoli, BeforeDelete>
      * <TOTEM:END>
           DELETE articoli.
           MOVE STATUS-articoli TO TOTEM-ERR-STAT
           MOVE "articoli" TO TOTEM-ERR-FILE
           MOVE "DELETE" TO TOTEM-ERR-MODE
      * <TOTEM:EPT. FD:DataSet1, FD:articoli, AfterDelete>
      * <TOTEM:END>
           .

       DataSet1-INIT-RECORD.
           INITIALIZE art-rec OF articoli
           .


      * FD's Initialize Paragraph
       DataSet1-articoli-INITREC.
           INITIALIZE art-rec OF articoli
               REPLACING NUMERIC       DATA BY ZEROS
                         ALPHANUMERIC  DATA BY SPACES
                         ALPHABETIC    DATA BY SPACES
           .

      *
       DataSet1-DISPATCH-BUFTOFLD.
           EVALUATE TOTEM-Form-Index ALSO TOTEM-Frame-Index
              WHEN 1 ALSO 0
                  PERFORM Form1-Buf-To-Fld
           END-EVALUATE
           .

       Form1-DISPLAY-STATUS-MSG.
            MODIFY Form1-St-1-Handle PANEL-INDEX = 1
                PANEL-TEXT = TOTEM-HINT-TEXT
           .

       Form1-CLEAR-STATUS-MSG.
           MOVE SPACES TO TOTEM-MSG-1, TOTEM-MSG-2, TOTEM-MSG-3, 
           TOTEM-MSG-TEXT
           PERFORM Form1-DISPLAY-STATUS-MSG
           .

       Form1-Open-Routine.
           PERFORM Form1-Scrn
           PERFORM Form1-Proc
           .

       Form1-Scrn.
           PERFORM Form1-Create-Win
           PERFORM Form1-Init-Value
           PERFORM Form1-Init-Data
      * Tab keystrok settings
      * Tool Bar
           DISPLAY Form1-Tb-1
           PERFORM Form1-DISPLAY
           .

       Form1-Create-Win.
           Display Independent GRAPHICAL WINDOW
              LINES 15,35,
              SIZE 88,50,
              HEIGHT-IN-CELLS,
              WIDTH-IN-CELLS,
              COLOR 131329,
              CONTROL FONT Calibri14-Occidentale,
              LABEL-OFFSET 23,
              LINK TO THREAD,
              MODELESS,
              NO SCROLL,
              TITLE-BAR,
              TITLE titolo,
              AUTO-MINIMIZE,
              WITH SYSTEM MENU,
              USER-GRAY,
              USER-WHITE,
              No WRAP,
              EVENT PROCEDURE Screen1-Event-Proc,
              HANDLE IS form1-Handle,
      * <TOTEM:EPT. FORM:Form1, FORM:Form1, AfterCreateWin>
      * <TOTEM:END>


      * Tool Bar    
           DISPLAY TOOL-BAR 
              LINES 3,35,   
              CONTROL FONT IS Calibri14-Occidentale
              HANDLE IN Form1-Tb-1-Handle
           DISPLAY Form1-Tb-1 UPON Form1-Tb-1-Handle

      * Status-bar
           DISPLAY STATUS-BAR
              GRIP,
              PANEL-WIDTHS (45, 23, 999),
              PANEL-STYLE  (1, 1, 1),
              PANEL-TEXT   (SPACE, SPACE, SPACE),
              HANDLE IS Form1-St-1-Handle
           DISPLAY Form1 UPON form1-Handle
      * DISPLAY-COLUMNS settings
           .

       Form1-PROC.
      * <TOTEM:EPT. FORM:Form1, FORM:Form1, BeforeAccept>
      *****     |Specifico del pgm. gproprieta
      *****     |                   ginqui
      *****     accept data-oggi from century-date.
      *****     move data-oggi(1:4) to como-anno.
      *****     subtract       18 from como-anno.
      *****     move data-oggi to data-maggiorenne.
      *****     move como-anno to data-maggiorenne(1:4).
      *****     |||||||


           perform INIT.
           perform ABILITA-TOOLBAR.
           perform ABILITAZIONI.
           perform STATUS-BAR-MSG.   
           
      *     perform PRIMO.

           .
      * <TOTEM:END>
           PERFORM UNTIL Exit-Pushed
              ACCEPT Form1
                 ON EXCEPTION
                    PERFORM Form1-Evaluate-Func
                 MOVE 1 TO TOTEM-Form-Index
              END-ACCEPT
      * <TOTEM:EPT. FORM:Form1, FORM:Form1, AfterEndAccept>
      * <TOTEM:END>
           END-PERFORM
      * <TOTEM:EPT. FORM:Form1, FORM:Form1, BeforeDestroyWindow>
      * <TOTEM:END>
           DESTROY form1-Handle
           INITIALIZE Key-Status
           .

       Form1-Evaluate-Func.
      * <TOTEM:EPT. FORM:Form1, FORM:Form1, AfterAccept>
           evaluate key-status
           when 5 |MODIFICA
                inquire tool-modifica, enabled in e-modifica
                if e-modifica = 1
                   if mod = zero 
                      move 1    to mod
                   else          
                      move zero to mod
                   end-if
                   modify tool-modifica, value = mod
                   perform MODIFICA
                end-if
           when 10 |ORDINAMENTO ALFABETICO 
                if OrderBy = zero 
                   move 1       to OrderBy
                else              
                   move zero    to OrderBy
                end-if
                modify TOOL-ORD, value OrderBy
                perform ORDINAMENTO
           end-evaluate.

           .
      * <TOTEM:END>
           EVALUATE TRUE
              WHEN Exit-Pushed
                 PERFORM Form1-Exit
              WHEN Event-Occurred
                 IF Event-Type = Cmd-Close
                    PERFORM Form1-Exit
                 END-IF
              WHEN Key-Status = 2
                 PERFORM NUOVO-LinkTo
              WHEN Key-Status = 4
                 PERFORM CANCELLA-LinkTo
              WHEN Key-Status = 3
                 PERFORM TOOL-SALVA-LinkTo
              WHEN Key-Status = 6
                 PERFORM ANTEPRIMA-LinkTo
              WHEN Key-Status = 150
                 PERFORM TOOL-MODIFICA-LinkTo
              WHEN Key-Status = 7
                 PERFORM STAMPA-LinkTo
              WHEN Key-Status = 8
                 PERFORM TOOL-CERCA-LinkTo
              WHEN Key-Status = 9
                 PERFORM TOOL-SELEZIONA-LinkTo
              WHEN Key-Status = 1002
                 PERFORM TOOL-PRIMO
              WHEN Key-Status = 67
                 PERFORM TOOL-PRECEDENTE
              WHEN Key-Status = 68
                 PERFORM TOOL-SUCCESSIVO
              WHEN Key-Status = 1006
                 PERFORM TOOL-ULTIMO
              WHEN Key-Status = 1001
                 PERFORM TOOL-ORD-LinkTo
           END-EVALUATE
      * avoid changing focus
           MOVE 4 TO Accept-Control
           .

       Form1-CLEAR.
           PERFORM Form1-INIT-VALUE
           PERFORM Form1-DISPLAY
           .

       Form1-DISPLAY.
      * <TOTEM:EPT. FORM:Form1, FORM:Form1, BeforeDisplay>
      * <TOTEM:END>
           DISPLAY Form1-Tb-1
           DISPLAY Form1 UPON form1-Handle
      * <TOTEM:EPT. FORM:Form1, FORM:Form1, AfterDisplay>
           SET LK-BL-SCRITTURA     TO TRUE.
           MOVE COMO-PROG-ID       TO LK-BL-PROG-ID.
           MOVE FORM1-HANDLE       TO LK-HND-WIN.
           CALL "BLOCKPGM"  USING LK-BLOCKPGM.
           CANCEL "BLOCKPGM".

           .
      * <TOTEM:END>
           .

       Form1-Exit.
      * for main screen
      * <TOTEM:EPT. FORM:Form1, FORM:Form1, BeforeExit>
           perform SALV-MOD.

           if errori
              move 26 to key-status
              exit paragraph
           end-if.

           .
      * <TOTEM:END>
           MOVE 27 TO Key-Status
           .

       Form1-Init-Data.
           MOVE 1 TO TOTEM-Form-Index
           MOVE 0 TO TOTEM-Frame-Index
           .

       Form1-DataSet1-CHANGETO-KEY1.
           MOVE 1 TO DataSet1-KEYIS
           PERFORM Form1-DataSet1-Update-Key
           .

       Form1-DataSet1-CHANGETO-KEY2.
           MOVE 2 TO DataSet1-KEYIS
           PERFORM Form1-DataSet1-Update-Key
           .

       Form1-DataSet1-Change-CurrentKey-Asc.
           EVALUATE DataSet1-KEYIS
           WHEN 1
              MOVE "A" TO DataSet1-articoli-KEY1-ORDER
           WHEN 2
              MOVE "A" TO DataSet1-articoli-KEY2-ORDER
           END-EVALUATE
           PERFORM Form1-DataSet1-Update-Key
           .

       Form1-DataSet1-Change-CurrentKey-Desc.
           EVALUATE DataSet1-KEYIS
           WHEN 1
              MOVE "D" TO DataSet1-articoli-KEY1-ORDER
           WHEN 2
              MOVE "D" TO DataSet1-articoli-KEY2-ORDER
           END-EVALUATE
           PERFORM Form1-DataSet1-Update-Key
           .

       Form1-DataSet1-Update-Key.
           MOVE art-rec OF articoli TO
                     Form1-MULKEY-TMPBUF
           PERFORM Form1-CLEAR
           PERFORM Form1-INIT-DATA
           MOVE Form1-MULKEY-TMPBUF TO
                     art-rec OF articoli
           PERFORM DataSet1-articoli-Read
           PERFORM Form1-DUPLICATE-MOVEKEY
           PERFORM Form1-DUMMY-CURR
           PERFORM Form1-IUD-Display
           .

       Form1-DUPLICATE-PREV.
           EVALUATE DataSet1-KEYIS
           WHEN 2
              PERFORM articoli-art-k-descrizione-MERGE-SPLITBUF
              IF articoli-art-k-descrizione-SPLITBUF = Form1-KEYISTMP2
                 MOVE DataSet1-articoli-KEY2-ORDER TO 
           TMP-Form1-KEY2-ORDER
                 MOVE "A" TO DataSet1-articoli-KEY2-ORDER
                 PERFORM DataSet1-articoli-START-EQUAL
                 IF Valid-STATUS-articoli
                    PERFORM DataSet1-articoli-Read-Next
                    PERFORM UNTIL NOT Valid-STATUS-articoli OR 
                         art-chiave = Form1-PKEYTMP OR
                         articoli-art-k-descrizione-SPLITBUF NOT = 
           Form1-KEYISTMP2
                       PERFORM DataSet1-articoli-Read-Next
                    END-PERFORM
                 END-IF
                 MOVE TMP-Form1-KEY2-ORDER TO 
           DataSet1-articoli-KEY2-ORDER
              ELSE
                 PERFORM DataSet1-articoli-START-LESS
              END-IF
           WHEN OTHER
              PERFORM DataSet1-articoli-START-LESS
           END-EVALUATE
           .

       Form1-DUPLICATE-NEXT.
           EVALUATE DataSet1-KEYIS
           WHEN 2
              PERFORM articoli-art-k-descrizione-MERGE-SPLITBUF
              IF articoli-art-k-descrizione-SPLITBUF = Form1-KEYISTMP2
                 MOVE DataSet1-articoli-KEY2-ORDER TO 
           TMP-Form1-KEY2-ORDER
                 MOVE "A" TO DataSet1-articoli-KEY2-ORDER
                 PERFORM DataSet1-articoli-START
                 IF Valid-STATUS-articoli
                    PERFORM DataSet1-articoli-Read-Next
                    PERFORM UNTIL NOT Valid-STATUS-articoli OR 
                         art-chiave = Form1-PKEYTMP OR
                         articoli-art-k-descrizione-SPLITBUF NOT = 
           Form1-KEYISTMP2
                       PERFORM DataSet1-articoli-Read-Next
                    END-PERFORM
                 END-IF
                 MOVE TMP-Form1-KEY2-ORDER TO 
           DataSet1-articoli-KEY2-ORDER
              ELSE
                 PERFORM DataSet1-articoli-START-GREATER
              END-IF
           WHEN OTHER
              PERFORM DataSet1-articoli-START-GREATER
           END-EVALUATE
           .

       Form1-DUPLICATE-MOVEKEY.
           MOVE art-chiave TO Form1-PKEYTMP
           EVALUATE DataSet1-KEYIS
           WHEN 2
              MOVE articoli-art-k-descrizione-SPLITBUF TO
                   Form1-KEYISTMP2
           END-EVALUATE
           .

       Form1-First.
           PERFORM Form1-DUMMY-FIRST
           PERFORM DataSet1-articoli-INITSTART
           PERFORM DataSet1-articoli-START
           IF NOT Valid-STATUS-articoli
              PERFORM Form1-Extended-File-Status
              EXIT PARAGRAPH
           END-IF
      * <TOTEM:EPT. FORM:Form1, FORM:Form1, BeforeFirst>
      * <TOTEM:END>
           PERFORM DataSet1-articoli-Read-Next
           IF NOT Valid-STATUS-articoli
              PERFORM Form1-Extended-File-Status
              EXIT PARAGRAPH
           END-IF
      * <TOTEM:EPT. FORM:Form1, FORM:Form1, AfterFirst>
      * <TOTEM:END>
           PERFORM Form1-DUPLICATE-MOVEKEY.
           PERFORM Form1-IUD-Display
           .

       Form1-Previous.
              PERFORM Form1-Buf-To-Fld
              PERFORM Form1-DUPLICATE-PREV
           IF NOT Valid-STATUS-articoli
              PERFORM Form1-Extended-File-Status
              EXIT PARAGRAPH
           END-IF
      * <TOTEM:EPT. FORM:Form1, FORM:Form1, BeforePrevious>
      * <TOTEM:END>
           PERFORM DataSet1-articoli-Read-Prev
           IF NOT Valid-STATUS-articoli
              PERFORM Form1-Extended-File-Status
              EXIT PARAGRAPH
           END-IF
      * <TOTEM:EPT. FORM:Form1, FORM:Form1, AfterPrevious>
      * <TOTEM:END>
           PERFORM Form1-DUPLICATE-MOVEKEY
           PERFORM Form1-DUMMY-PREVIOUS
           PERFORM Form1-IUD-Display
           .

       Form1-Next.
              PERFORM Form1-Buf-To-Fld
              PERFORM Form1-DUPLICATE-NEXT
           IF NOT Valid-STATUS-articoli
              PERFORM Form1-Extended-File-Status
              EXIT PARAGRAPH
           END-IF
      * <TOTEM:EPT. FORM:Form1, FORM:Form1, BeforeNext>
      * <TOTEM:END>
           PERFORM DataSet1-articoli-Read-Next
           IF NOT Valid-STATUS-articoli
              PERFORM Form1-Extended-File-Status
              EXIT PARAGRAPH
           END-IF
      * <TOTEM:EPT. FORM:Form1, FORM:Form1, AfterNext>
      * <TOTEM:END>
           PERFORM Form1-DUPLICATE-MOVEKEY
           PERFORM Form1-DUMMY-NEXT
           PERFORM Form1-IUD-Display
           .
      
       Form1-Last.
           PERFORM Form1-DUMMY-LAST
           PERFORM DataSet1-articoli-INITEND
           PERFORM DataSet1-articoli-START-NOTGREATER
           IF NOT Valid-STATUS-articoli
              PERFORM Form1-Extended-File-Status
              EXIT PARAGRAPH
           END-IF
      * <TOTEM:EPT. FORM:Form1, FORM:Form1, BeforeLast>
      * <TOTEM:END>
           PERFORM DataSet1-articoli-Read-Prev
           IF NOT Valid-STATUS-articoli
              PERFORM Form1-Extended-File-Status
              EXIT PARAGRAPH
           END-IF
      * <TOTEM:EPT. FORM:Form1, FORM:Form1, AfterLast>
      * <TOTEM:END>
           PERFORM Form1-DUPLICATE-MOVEKEY.
           PERFORM Form1-IUD-Display
           .

       Form1-Curr.
      * <TOTEM:EPT. FORM:Form1, FORM:Form1, BeforeCurrent>
      * <TOTEM:END>
           PERFORM Form1-Buf-To-Fld
           PERFORM DataSet1-articoli-Read
           PERFORM Form1-DUPLICATE-MOVEKEY
           PERFORM Form1-DUMMY-CURR
           PERFORM Form1-IUD-Display
      * <TOTEM:EPT. FORM:Form1, FORM:Form1, AfterCurrent>
      * <TOTEM:END>
           .

       Form1-IUD-Display.
           IF Valid-STATUS-articoli
              PERFORM Form1-ALLGRID-RESET
              PERFORM Form1-Fld-To-Buf
              PERFORM Form1-NAVI-FOR-MASTERGRID
              PERFORM Form1-DISPLAY
           ELSE
              IF Form1-FLAG-REFRESH
                 CONTINUE
              ELSE
                 PERFORM Form1-Extended-File-Status
              END-IF
           END-IF
           .

       Form1-Add.
           PERFORM Form1-Buf-To-Fld
           PERFORM Form1-VALIDATION-ROUTINE
           IF NOT TOTEM-CHECK-OK
               EXIT PARAGRAPH
           END-IF
           PERFORM Form1-DUMMY-ADD
           PERFORM DataSet1-articoli-INITREC
           PERFORM Form1-Buf-To-Fld
           MOVE SPACES TO TOTEM-TRANSACTION-FLAG
      * <TOTEM:EPT. FORM:Form1, FORM:Form1, BeforeAdd>
      * <TOTEM:END>
      * write
           PERFORM DataSet1-articoli-Rec-Write
           IF Valid-STATUS-articoli
              PERFORM Form1-RESUMMARY-INS
              PERFORM Form1-DUMMY-UPDATE-INIT
              MOVE "301" TO TOTEM-MSG-ID
              PERFORM Form1-IUD-Display
           END-IF
           PERFORM Form1-ERR-CHECKING
      * <TOTEM:EPT. FORM:Form1, FORM:Form1, AfterAdd>
      * <TOTEM:END>
           .
     
       Form1-Update.
           PERFORM Form1-Buf-To-Fld
           PERFORM DataSet1-articoli-START              
           IF NOT Valid-STATUS-articoli
              PERFORM Form1-Extended-File-Status
              EXIT PARAGRAPH
           END-IF
           PERFORM DataSet1-articoli-Read
           PERFORM Form1-Buf-To-Fld
           PERFORM Form1-VALIDATION-ROUTINE
           IF NOT TOTEM-CHECK-OK
               EXIT PARAGRAPH
           END-IF
           PERFORM Form1-DUMMY-UPDATE
           PERFORM Form1-Buf-To-Fld
           MOVE SPACES TO TOTEM-TRANSACTION-FLAG
      * <TOTEM:EPT. FORM:Form1, FORM:Form1, BeforeUpdate>
      * <TOTEM:END>
      * write
           PERFORM DataSet1-articoli-Rec-Rewrite
           IF Valid-STATUS-articoli
              PERFORM Form1-RESUMMARY-DEL
              PERFORM Form1-DUMMY-UPDATE-INIT
              MOVE "302" TO TOTEM-MSG-ID
              PERFORM Form1-IUD-Display
           END-IF
           PERFORM Form1-ERR-CHECKING
      * <TOTEM:EPT. FORM:Form1, FORM:Form1, AfterUpdate>
      * <TOTEM:END>
           .

       Form1-Delete.
           MOVE "203" TO TOTEM-MSG-ID
           PERFORM MESSAGE-BOX-DISPLAY
           IF TOTEM-MSG-RETURN-VALUE NOT = 1
              INITIALIZE TOTEM-MSG-TEXT
              EXIT PARAGRAPH 
           END-IF
           MOVE SPACES TO TOTEM-TRANSACTION-FLAG
      * <TOTEM:EPT. FORM:Form1, FORM:Form1, BeforeDelete>
      * <TOTEM:END>
           PERFORM Form1-DUMMY-DELETE
      * delete
           PERFORM Form1-Buf-To-Fld
           PERFORM DataSet1-articoli-Rec-Delete
           IF Valid-STATUS-articoli
              PERFORM Form1-CLEAR
              PERFORM Form1-DUMMY-DELETE-INIT
              MOVE "303" TO TOTEM-MSG-ID
              MOVE "00" to STATUS-articoli
           END-IF
      * <TOTEM:EPT. FORM:Form1, FORM:Form1, AfterDelete>
      * <TOTEM:END>
           PERFORM Form1-ERR-CHECKING
           .

       Form1-NAVI-FOR-MASTERGRID.
           .

       Form1-ERR-CHECKING.
           IF Valid-STATUS-articoli
              PERFORM Form1-SHOW-MSG-ROUTINE
           ELSE
              PERFORM Form1-Extended-File-Status
           END-IF
           .

       Form1-RESUMMARY-INS.
           .

       Form1-RESUMMARY-DEL.
           .


       Form1-DUMMY-FIRST.
           .

       Form1-DUMMY-PREVIOUS.
           .

       Form1-DUMMY-NEXT.
           .

       Form1-DUMMY-LAST.
           .

       Form1-DUMMY-CURR.
           .

       Form1-DUMMY-ADD.
           .

       Form1-DUMMY-UPDATE.
           .

       Form1-DUMMY-UPDATE-INIT.
           .

       Form1-DUMMY-DELETE.
           .

       Form1-DUMMY-DELETE-INIT.
           .

       Form1-Init-Value.
           MOVE titolo TO TOTEM-MSG-TITLE
           INITIALIZE Form1-BUF
      * FORM : Form1
           PERFORM DataSet1-INIT-RECORD
           MOVE ALL X'9' TO Form1-KEYISTMP2
           MOVE ALL X'9' TO Form1-PKEYTMP
      * <TOTEM:EPT. FORM:Form1, FORM:Form1, SetDefault>
      * <TOTEM:END>
           PERFORM Form1-FLD-TO-BUF
           .


       Form1-ALLGRID-RESET.
           .

      * for Form's Validation
       Form1-VALIDATION-ROUTINE.
           SET TOTEM-CHECK-OK TO TRUE
      * ef-codice's Validation
           SET TOTEM-CHECK-OK TO FALSE
           PERFORM ef-codice-VALIDATION
           IF NOT TOTEM-CHECK-OK
               MOVE 4 TO ACCEPT-CONTROL
               MOVE 5001 TO CONTROL-ID
               EXIT PARAGRAPH
           END-IF
      * ef-descr's Validation
           SET TOTEM-CHECK-OK TO FALSE
           PERFORM ef-descr-VALIDATION
           IF NOT TOTEM-CHECK-OK
               MOVE 4 TO ACCEPT-CONTROL
               MOVE 5002 TO CONTROL-ID
               EXIT PARAGRAPH
           END-IF
      * ef-note's Validation
           SET TOTEM-CHECK-OK TO FALSE
           PERFORM ef-note-VALIDATION
           IF NOT TOTEM-CHECK-OK
               MOVE 4 TO ACCEPT-CONTROL
               MOVE 5003 TO CONTROL-ID
               EXIT PARAGRAPH
           END-IF
           .

       ef-codice-BEFORE-VALIDATION.
      * <TOTEM:EPT. FORM:Form1, Data.Entry-Field:ef-codice, BeforeValidation>
      * <TOTEM:END>
           .

       ef-codice-AFTER-VALIDATION.
      * <TOTEM:EPT. FORM:Form1, Data.Entry-Field:ef-codice, AfterValidation>
      * <TOTEM:END>
           .

      * ef-codice's Validation
       ef-codice-VALIDATION.
           PERFORM ef-codice-BEFORE-VALIDATION
           SET TOTEM-CHECK-OK TO TRUE
           PERFORM ef-codice-AFTER-VALIDATION
           .

       ef-descr-BEFORE-VALIDATION.
      * <TOTEM:EPT. FORM:Form1, Data.Entry-Field:ef-descr, BeforeValidation>
      * <TOTEM:END>
           .

       ef-descr-AFTER-VALIDATION.
      * <TOTEM:EPT. FORM:Form1, Data.Entry-Field:ef-descr, AfterValidation>
      * <TOTEM:END>
           .

      * ef-descr's Validation
       ef-descr-VALIDATION.
           PERFORM ef-descr-BEFORE-VALIDATION
           SET TOTEM-CHECK-OK TO TRUE
           PERFORM ef-descr-AFTER-VALIDATION
           .

       ef-note-BEFORE-VALIDATION.
      * <TOTEM:EPT. FORM:Form1, Data.Entry-Field:ef-note, BeforeValidation>
      * <TOTEM:END>
           .

       ef-note-AFTER-VALIDATION.
      * <TOTEM:EPT. FORM:Form1, Data.Entry-Field:ef-note, AfterValidation>
      * <TOTEM:END>
           .

      * ef-note's Validation
       ef-note-VALIDATION.
           PERFORM ef-note-BEFORE-VALIDATION
           SET TOTEM-CHECK-OK TO TRUE
           PERFORM ef-note-AFTER-VALIDATION
           .


       Form1-Buf-To-Fld.
      * <TOTEM:EPT. FORM:Form1, FORM:Form1, BeforeBufToFld>
      * <TOTEM:END>
      * DB_Entry-Field : ef-codice
           MOVE ef-codice-BUF TO art-codice
      * DB_Entry-Field : ef-descr
           MOVE ef-descr-BUF TO art-descrizione
      * DB_Entry-Field : ef-note
           MOVE ef-note-BUF TO art-note
      * <TOTEM:EPT. FORM:Form1, FORM:Form1, AfterBufToFld>
      * <TOTEM:END>
           .

       Form1-Fld-To-Buf.
      * <TOTEM:EPT. FORM:Form1, FORM:Form1, BeforeFldToBuf>
      * <TOTEM:END>
      * DB_Entry-Field : ef-codice
           MOVE art-codice TO ef-codice-BUF
      * DB_Entry-Field : ef-descr
           MOVE art-descrizione TO ef-descr-BUF
      * DB_Entry-Field : ef-note
           MOVE art-note TO ef-note-BUF
      * <TOTEM:EPT. FORM:Form1, FORM:Form1, AfterFldToBuf>
           perform ABILITAZIONI.

           Perform VALORIZZA-OLD.

           .
      * <TOTEM:END>
           .

       Form1-CONTROLLO-OLD.
           set SiSalvato to true.
           if mod = 0 exit paragraph end-if.
           perform Form1-BUF-TO-FLD.
           move 0 to scelta.
           if art-descrizione not = old-art-descrizione
              and SiSalvato
              set NoSalvato to true
              |78-ID-ef-descr è l'ID del campo ef-descr
              move 78-ID-ef-descr to store-id 
           end-if

           .
       Form1-EXTENDED-FILE-STATUS.
           CALL "C$RERRNAME" USING TOTEM-MSG-ERR-FILE
           CALL "C$RERR" USING EXTEND-STAT, TEXT-MESSAGE
           MOVE PRIMARY-ERROR TO TOTEM-MSG-ID
           PERFORM Form1-SHOW-MSG-ROUTINE
           .

       Form1-SHOW-MSG-ROUTINE.
           PERFORM SHOW-MSG-ROUTINE
           PERFORM Form1-DISPLAY-MESSAGE
           .

       Form1-DISPLAY-MESSAGE.
           PERFORM MESSAGE-BOX-ROUTINE
           DISPLAY MESSAGE BOX TOTEM-MSG-TEXT
               TITLE IS TOTEM-MSG-TITLE
               TYPE  IS TOTEM-MSG-BUTTON-TYPE
               ICON  IS TOTEM-MSG-DEFAULT-BUTTON
               RETURNING TOTEM-MSG-RETURN-VALUE
           .

       Form1-Save-Status.
           MOVE DataSet1-articoli-KEY1-ORDER TO TMP-Form1-KEY1-ORDER
           MOVE DataSet1-articoli-KEY2-ORDER TO TMP-Form1-KEY2-ORDER
           MOVE DataSet1-KEYIS TO TMP-Form1-KEYIS
           MOVE art-rec OF articoli TO 
              TMP-Form1-articoli-RESTOREBUF
           .             

       Form1-Restore-Status.
           MOVE TMP-Form1-KEY1-ORDER TO DataSet1-articoli-KEY1-ORDER
           MOVE TMP-Form1-KEY2-ORDER TO DataSet1-articoli-KEY2-ORDER
           MOVE TMP-Form1-KEYIS TO DataSet1-KEYIS
           MOVE TMP-Form1-articoli-RESTOREBUF TO
              art-rec OF articoli
           PERFORM DataSet1-articoli-START
           IF Valid-STATUS-articoli
              PERFORM DataSet1-articoli-Read-Next
           ELSE
              PERFORM DataSet1-articoli-INITREC
           END-IF
           PERFORM UNTIL NOT Valid-STATUS-articoli OR
              (Valid-STATUS-articoli AND
                 art-rec OF articoli = 
                   TMP-Form1-articoli-RESTOREBUF)
              PERFORM DataSet1-articoli-Read-Next
           END-PERFORM
           .


      * Paragrafo per la struttura del codice in AFTER sulla screen Form1
      ***---
       Form1-AFTER-SCREEN.

      * Generazione risettaggio keyboard "." ---> "."

      * Generazione stringa perform CONTROLLO
           evaluate control-id
           |78-ID-ef-codice è l'ID del campo ef-codice
           when 78-ID-ef-codice
                perform CONTROLLO
           |78-ID-ef-descr è l'ID del campo ef-descr
           when 78-ID-ef-descr
                perform CONTROLLO
           |99999 è un valore fittizio, che non sarà MAI usato,
           |ma mi serve per non riscontrare errori di compilazione
           |in caso non avessi generato nulla nella AFTER CONTROLLO della screen
           when 99999 continue
           when other continue
           end-evaluate.



       Form1-BeforeProcedure.
           EVALUATE Control-Id
           WHEN 5001 MOVE "Digitare il Codice" to TOTEM-HINT-TEXT
           WHEN 5002 MOVE "." to TOTEM-HINT-TEXT
           WHEN 5003 MOVE "." to TOTEM-HINT-TEXT
           WHEN OTHER MOVE SPACES TO TOTEM-HINT-TEXT
           END-EVALUATE
           EVALUATE Control-Id
           When 5001 PERFORM ef-codice-BeforeProcedure
           When 5002 PERFORM ef-descr-BeforeProcedure
           When 5003 PERFORM Screen1-DaEf-1-BeforeProcedure
           END-EVALUATE
           PERFORM Form1-DISPLAY-STATUS-MSG
           .

       Form1-AfterProcedure.
           EVALUATE Control-Id
           When 5001 PERFORM ef-codice-AfterProcedure
           When 5002 PERFORM ef-ragsoc-AfterProcedure
           When 5003 PERFORM Screen1-DaEf-1-AfterProcedure
           END-EVALUATE
           perform Form1-AFTER-SCREEN
           .

       Screen1-Event-Proc.
           .

      * USER DEFINE PARAGRAPH
       ABILITAZIONI.
      * <TOTEM:PARA. ABILITAZIONI>
           if mod = 1              
              move BitmapDeleteEnabled to BitmapNumDelete
              move BitmapSaveEnabled   to BitmapNumSave
              move 1 to e-salva e-cancella
           else           
              move BitmapDeleteDisabled to BitmapNumDelete
              move BitmapSaveDisabled   to BitmapNumSave
              move ZERO to e-salva e-cancella
           end-if.      

           modify tool-cancella, enabled = e-cancella.
           modify tool-salva,    enabled = e-salva.
       
      * ISACCO (SERVE SEMPRE PER LA MODIFICA PRCEDENTE E PER RIPRISTINARE
      * LE BITMAP DISABILITATE. - 10/11/2003
      *     perform FORM1-DISPLAY.
           display tool-nuovo, tool-salva, tool-cancella, tool-modifica.
      * FINE 
           .
      * <TOTEM:END>

       ANTEPRIMA.
      * <TOTEM:PARA. ANTEPRIMA>
           continue 
           .
      * <TOTEM:END>

       CANCELLA.
      * <TOTEM:PARA. CANCELLA>
           if mod = ZERO
              exit paragraph 
           end-if.
      *
           display message box MSg-Cancellare-il-record-corrente
                   title   titolo
                   type    mb-yes-no 
                   default mb-no
                   giving  scelta

           if scelta = mb-yes
              perform RIEMPI-CHIAVE
              delete articoli record invalid continue end-delete

              move 0    to mod
              move 1    to mod-k
              perform FORM1-CLEAR
              set vecchio to true
              perform CANCELLA-COLORE
              perform INIT-OLD-REC

              
              display message box 
           MSG-Cancellazione-avvenuta-con-successo
                      title titolo                         

              unlock articoli all records

              perform PRIMO 
              move 78-ID-ef-codice to  CONTROL-ID     
              move 4         to  ACCEPT-CONTROL 

              set Statusvisua to true
              perform STATUS-BAR-MSG
              modify TOOL-MODIFICA value = mod
           end-if 
           .
      * <TOTEM:END>

       CERCA.
      * <TOTEM:PARA. CERCA>
           continue 
           .
      * <TOTEM:END>

       CLEAR-SCREEN.
      * <TOTEM:PARA. CLEAR-SCREEN>
           move art-chiave to old-art-chiave.

           initialize art-dati replacing numeric data by zeroes
                                   alphanumeric data by spaces.
                         
           perform FORM1-FLD-TO-BUF. 

           perform INIT-OLD-REC.
                                          
           display form1. 

           unlock articoli all records 
           .
      * <TOTEM:END>

       CHECK-INSERIMENTO.
      * <TOTEM:PARA. CHECK-INSERIMENTO>
      * MODIFICA LA STATUS-BAR
      * CONTROLLO SE DA INSERIMENTO SCORRO. ALLORA DEVO SEGNALARE CHE
      * SONO TORNATO IN MODIFICA.
           inquire tool-modifica, value in mod.

           evaluate mod
           when 1   set StatusModifica to true
           when 0   set StatusVisua    to true   
           end-evaluate.
      
           perform STATUS-BAR-MSG 
           .
      * <TOTEM:END>

       CONTROLLO.
      * <TOTEM:PARA. CONTROLLO>
           set tutto-ok to true. 

           evaluate CONTROL-ID
           when 78-ID-ef-codice
                perform RIEMPI-CHIAVE
      
                if ef-codice-buf not = spaces
                   perform SELEZIONA-NUMERICO
                else
                   set errori to true
                   display message box MSG-Codice-obbligatorio
                           title tit-err
                           icon  mb-warning-icon
                end-if
      
           when 78-ID-ef-descr
                inquire ef-descr value in art-descrizione
                if art-descrizione = spaces
                   set errori to true
                   display message box "Descrizione obbligatoria"
                           title tit-err
                           type  mb-ok
                           icon  mb-warning-icon
                end-if
           end-evaluate.
      
           if errori
              perform CANCELLA-COLORE
              move CONTROL-ID to store-id
              move 4          to ACCEPT-CONTROL
           end-if 
           .
      * <TOTEM:END>

       CURRENT-RECORD.
      * <TOTEM:PARA. CURRENT-RECORD>
           perform RIEMPI-CHIAVE.
           set tutto-ok  to true.
           set ReadSecca to true.
           if nuovo move 0 to mod end-if.

           if mod = 1
              read articoli    lock invalid 
                 set errori to true 
              end-read
           else
              read articoli no lock invalid 
                 set errori to true 
              end-read
           end-if.                    
           set ReadSecca to false.

           if RecLocked
              set RecLocked to false
           else
              if tutto-ok    
                 if nuovo
                    move 0      to mod
                    move 1      to mod-k
                    move 78-ID-ef-codice to CONTROL-ID
                    move 4         to ACCEPT-CONTROL
                 end-if   
                 perform FORM1-IUD-DISPLAY
                 set vecchio to true
                 if mod = 1
                    set StatusModifica to true
                 else                         
                    set StatusVisua    to true
                 end-if
                 perform STATUS-BAR-MSG
                 perform VALORIZZA-OLD
              else
                 move 0 to mod
                 move 1 to mod-k
                 if vecchio
                    perform CLEAR-SCREEN
                    if YesMessage
                       move 78-ID-ef-codice to CONTROL-ID
                       move 4         to ACCEPT-CONTROL
                       display message box MSG-Record-inesistente
                               title = tit-err
                               icon mb-warning-icon
                    end-if
                 end-if
              end-if
           end-if 
           .
      * <TOTEM:END>

       INIT.
      * <TOTEM:PARA. INIT>
           move 0    to StatusHelp.
           move 1    to mod-k.
           set StatusVisua    to true  
           .
      * <TOTEM:END>

       INIT-OLD-REC.
      * <TOTEM:PARA. INIT-OLD-REC>
           initialize old-art-rec replacing numeric data by zeroes
                                       alphanumeric data by spaces 
           .
      * <TOTEM:END>

       MODIFICA.
      * <TOTEM:PARA. MODIFICA>
           move 5 to key-status.
           inquire tool-modifica, value in mod.
           set tutto-ok to true.

           if nuovo
              move 1 to mod                  
              modify tool-modifica, value mod
           else
      *  SE L'UTENTE E' ABILITATO PUO' MODIFICARE UN RECORD
              if mod = 1
                 set YesMessage to true
                 perform CURRENT-RECORD
                 if tutto-ok
                    if CONTROL-ID < 78-ID-ef-descr
                       move 78-ID-ef-descr to CONTROL-ID
                    end-if
                    move ZERO to mod-k
                    move 1    to mod
                    set StatusModifica to true
                    perform STATUS-BAR-MSG
                 end-if
              else
                 move 1    to mod
                 perform SALV-MOD            
                 move ZERO to mod
                 move 1    to mod-k
                 if errori
                    move 1    to mod
                    move ZERO to mod-k
                 else
                    move 78-ID-ef-codice to CONTROL-ID
                    set NoMessage to true
                    perform CURRENT-RECORD
                    set StatusVisua to true
                    perform STATUS-BAR-MSG 
                    unlock articoli all records
                 end-if
              end-if
                        
              display form1
              modify tool-modifica,  value mod
              perform CANCELLA-COLORE 

              move 4 to ACCEPT-CONTROL
           end-if 
           .
      * <TOTEM:END>

       NUOVO.
      * <TOTEM:PARA. NUOVO>
           perform SALV-MOD.

           if tutto-ok  
              move 1         to mod mod-k
              modify tool-modifica,  value = mod
              perform CANCELLA-COLORE                  
              perform VALORIZZA-NUOVO
              perform INIT-OLD-REC       
              set StatusIns to true
              perform STATUS-BAR-MSG  
              set nuovo to true       
              unlock articoli all records
              move 78-ID-ef-codice to CONTROL-ID       
              move 4               to ACCEPT-CONTROL   
           end-if 
           .
      * <TOTEM:END>

       ORDINAMENTO.
      * <TOTEM:PARA. ORDINAMENTO>
           inquire tool-ord, value in OrderBy.
      
           if OrderBy = zero
              perform DataSet1-CHANGETO-KEY1
           else
              perform DataSet1-CHANGETO-KEY2
           end-if.
      
           perform CURRENT-RECORD 
           .
      * <TOTEM:END>

       PARAGRAFO-COPY.
      * <TOTEM:PARA. PARAGRAFO-COPY>
           copy "abilita-toolbar.cpy".
           copy "color-custom.cpy".
           copy "status.cpy"  
           .
      * <TOTEM:END>

       PRECEDENTE.
      * <TOTEM:PARA. PRECEDENTE>
           perform SALV-MOD.           
           if tutto-ok

              perform CHECK-INSERIMENTO
              unlock articoli all records

              if mod = 1
                 move ZERO to mod-k
                 set dataset1-articoli-lock to true
              else              
                 move 1    to mod-k     
                 initialize dataset1-articoli-lock-flag
              end-if
                    
              perform CANCELLA-COLORE
              perform FORM1-PREVIOUS

              if RecLocked
                 set RecLocked to false             
                 initialize dataset1-articoli-lock-flag
                 move 1 to mod-k
                 perform FORM1-PREVIOUS
              end-if
           end-if 
           .
      * <TOTEM:END>

       PRIMO.
      * <TOTEM:PARA. PRIMO>
           perform SALV-MOD.           
           if tutto-ok    
 
              perform CHECK-INSERIMENTO
              unlock articoli all records

              if mod = 1
                 move ZERO to mod-k
                 set dataset1-articoli-lock to true
              else              
                 move 1    to mod-k     
                 initialize dataset1-articoli-lock-flag
              end-if
                                  
              perform CANCELLA-COLORE
              perform FORM1-FIRST

              if RecLocked
                 set RecLocked to false             
                 initialize dataset1-articoli-lock-flag
                 move 1 to mod-k
                 perform FORM1-FIRST
              end-if
           end-if 
           .
      * <TOTEM:END>

       RIEMPI-CHIAVE.
      * <TOTEM:PARA. RIEMPI-CHIAVE>
           inquire ef-codice, value in ef-codice-buf.
           move ef-codice-buf       to art-codice 
           .
      * <TOTEM:END>

       SALVA.
      * <TOTEM:PARA. SALVA>
           if mod = ZERO 
              exit paragraph 
           end-if.

           set tutto-ok to true.

           perform varying CONTROL-ID from 78-ID-ef-descr by 1
                     until CONTROL-ID > 78-ID-ef-descr
              perform CONTROLLO
              if errori 
                 exit perform 
              end-if
           end-perform.

           if errori
              perform ABILITAZIONI
              move store-id to CONTROL-ID
              move 4        to ACCEPT-CONTROL
           else                       
              perform FORM1-BUF-TO-FLD
              perform CANCELLA-COLORE 
                                     
              accept como-data from century-date
              accept como-ora  from time
          
              write art-rec invalid rewrite art-rec end-write

              set vecchio to true       
              perform TORNA-IN-VISUA
           end-if.   
                 
           display form1 
           .
      * <TOTEM:END>

       SALV-MOD.
      * <TOTEM:PARA. SALV-MOD>
           set tutto-ok to true.
           perform FORM1-CONTROLLO-OLD.

           if NoSalvato
              display message box MSG-Salvare-le-modifiche
                            title titolo
                            type mb-yes-no-cancel 
                            giving scelta       
       
              evaluate scelta
              when mb-yes 
                   perform SALVA
              when mb-no  
                   continue
              when other                
                   perform CANCELLA-COLORE
                   set errori to true
                   move store-id to CONTROL-ID       
                   move 4        to ACCEPT-CONTROL   
              end-evaluate
           end-if 
           .
      * <TOTEM:END>

       SELEZIONA.
      * <TOTEM:PARA. SELEZIONA>
           perform RIEMPI-CHIAVE.

           move "articoli"  to    como-file.
           call "zoom-gt" using como-file, art-rec
                          giving stato-zoom.
           cancel "zoom-gt".
           if stato-zoom = ZERO
              if old-art-chiave not = art-chiave or
               ( art-codice = 0 and mod = 0 )
                 move art-chiave to save-key
                 perform SALV-MOD
                 if tutto-ok
                    move save-key to art-chiave
                    set ReadSecca to true
                    modify ef-codice, value art-codice
                    perform CURRENT-RECORD
                    perform CANCELLA-COLORE
                    move 78-ID-ef-descr to CONTROL-ID       
                    move 4              to ACCEPT-CONTROL   
                 end-if                                  
              end-if
           end-if 
           .
      * <TOTEM:END>

       SELEZIONA-ALFA.
      * <TOTEM:PARA. SELEZIONA-ALFA>
      * LA SECONDA CHIAVE E' ALFANUMERICA E LA VALUE VARIABLE CONTIENE
      * ANCORA GLI ZERI DAVANTI CHE ELIMINO
           inspect ef-codice-buf replacing leading ZERO by SPACES.
           move ef-codice-buf to art-descrizione.

      * POI GIUSTIFICO A SINISTRA E MI POSIZIONO SULLO ZOOM PER CHIAVE
      * ALTERNATA
           call "C$JUSTIFY" using art-descrizione, "L".

           start articoli key >= art-k-descrizione
                 invalid continue
             not invalid read articoli next 
           end-start.

           move "articoli-alfa" to como-file.
           call "zoom-gt" using como-file, art-rec
                          giving stato-zoom.
           cancel "zoom-gt".
           if stato-zoom = 0
              move art-codice    to ef-codice-buf   
              display ef-codice

              if old-art-descrizione not = art-descrizione
                 move art-descrizione to save-key-1
                 perform SALV-MOD
                 if tutto-ok
                    move save-key-1 to art-descrizione
                    set ReadSecca  to true
                    modify ef-codice, value art-codice
                    perform CURRENT-RECORD
                    perform CANCELLA-COLORE
                    move 78-ID-ef-descr to CONTROL-ID       
                    move 4              to ACCEPT-CONTROL   
                 end-if                                  
              end-if
           end-if 
           .
      * <TOTEM:END>

       SELEZIONA-NUMERICO.
      * <TOTEM:PARA. SELEZIONA-NUMERICO>
           read articoli no lock
                invalid
                if vecchio
                   perform SELEZIONA-ALFA
                end-if
            not invalid      
                if old-art-chiave not = art-chiave or
                 ( art-codice = 0 and mod = 0 )
                   perform CURRENT-RECORD 
                end-if
           end-read 
           .
      * <TOTEM:END>

       STAMPA.
      * <TOTEM:PARA. STAMPA>
           continue 
           .
      * <TOTEM:END>

       SUCCESSIVO.
      * <TOTEM:PARA. SUCCESSIVO>
           perform SALV-MOD.
           if tutto-ok

              perform CHECK-INSERIMENTO
              unlock articoli all records

              if mod = 1
                 move ZERO to mod-k
                 set dataset1-articoli-lock to true
              else              
                 move 1    to mod-k     
                 initialize dataset1-articoli-lock-flag
              end-if
                                     
              perform CANCELLA-COLORE
              perform FORM1-NEXT
 
              if RecLocked
                 set RecLocked to false             
                 initialize dataset1-articoli-lock-flag
                 move 1 to mod-k
                 perform FORM1-NEXT
              end-if
           end-if 
           .
      * <TOTEM:END>

       TORNA-IN-VISUA.
      * <TOTEM:PARA. TORNA-IN-VISUA>
           move 0 to mod.
           move 1 to mod-k.
           move 78-ID-ef-codice to CONTROL-ID.
           set NoMessage to true.
           perform ABILITAZIONI.
           set StatusVisua to true.
           perform STATUS-BAR-MSG.
           unlock articoli all records.
                        
           modify tool-modifica,  value mod.
           perform CANCELLA-COLORE.
           move 4 to ACCEPT-CONTROL 
           .
      * <TOTEM:END>

       ULTIMO.
      * <TOTEM:PARA. ULTIMO>
           perform SALV-MOD.
           if tutto-ok

              perform CHECK-INSERIMENTO
              unlock articoli all records 

              if mod = 1
                 move ZERO to mod-k
                 set dataset1-articoli-lock to true
              else              
                 move 1    to mod-k     
                 initialize dataset1-articoli-lock-flag
              end-if
                               
              perform CANCELLA-COLORE
              perform FORM1-LAST 
 
              if RecLocked
                 set RecLocked to false             
                 initialize dataset1-articoli-lock-flag
                 move 1 to mod-k
                 perform FORM1-LAST
              end-if
           end-if 
           .
      * <TOTEM:END>

       VALORIZZA-OLD.
      * <TOTEM:PARA. VALORIZZA-OLD>
           move art-rec to old-art-rec.
           set vecchio to true.

           move ZERO to StatusHelp
           perform STATUS-HELP 
           .
      * <TOTEM:END>

       VALORIZZA-NUOVO.
      * <TOTEM:PARA. VALORIZZA-NUOVO>
           move "00"    to status-articoli.

           initialize art-rec replacing numeric data by zeroes
                                   alphanumeric data by spaces.
                                       
           perform FORM1-IUD-DISPLAY   
           .
      * <TOTEM:END>

      * EVENT PARAGRAPH
       NUOVO-LinkTo.
      * <TOTEM:PARA. NUOVO-LinkTo>
           INQUIRE TOOL-NUOVO, ENABLED IN E-NUOVO.

           IF E-NUOVO = 1
              PERFORM NUOVO
           END-IF                    
           .
      * <TOTEM:END>
       CANCELLA-LinkTo.
      * <TOTEM:PARA. CANCELLA-LinkTo>
           INQUIRE TOOL-MODIFICA, VALUE IN MOD.
                              
           INQUIRE TOOL-CANCELLA, ENABLED IN E-CANCELLA
           IF E-CANCELLA = 1
              PERFORM CANCELLA
           END-IF                                                
           .
      * <TOTEM:END>
       TOOL-SALVA-LinkTo.
      * <TOTEM:PARA. TOOL-SALVA-LinkTo>
           INQUIRE TOOL-MODIFICA, VALUE IN MOD           

           INQUIRE TOOL-SALVA, ENABLED IN E-SALVA
           IF E-SALVA = 1
              PERFORM SALVA
           END-IF           
           .
      * <TOTEM:END>
       ANTEPRIMA-LinkTo.
      * <TOTEM:PARA. ANTEPRIMA-LinkTo>
           INQUIRE TOOL-ANTEPRIMA, ENABLED IN E-ANTEPRIMA.
           IF E-ANTEPRIMA = 1
                PERFORM ANTEPRIMA
           END-IF 
           .
      * <TOTEM:END>
       TOOL-MODIFICA-BeforeProcedure.
      * <TOTEM:PARA. TOOL-MODIFICA-BeforeProcedure>
           MODIFY CONTROL-HANDLE COLOR = COLORE-NU
           .
      * <TOTEM:END>
       TOOL-MODIFICA-AfterProcedure.
      * <TOTEM:PARA. TOOL-MODIFICA-AfterProcedure>
           MODIFY CONTROL-HANDLE COLOR = COLORE-OR
           .
      * <TOTEM:END>
       TOOL-MODIFICA-LinkTo.
      * <TOTEM:PARA. TOOL-MODIFICA-LinkTo>
           INQUIRE TOOL-MODIFICA, ENABLED IN E-MODIFICA.

           IF E-MODIFICA = 1
              PERFORM MODIFICA
           END-IF 
           .
      * <TOTEM:END>
       STAMPA-LinkTo.
      * <TOTEM:PARA. STAMPA-LinkTo>
           INQUIRE TOOL-STAMPA, ENABLED IN E-STAMPA
           IF E-STAMPA = 1
                PERFORM STAMPA
           END-IF 
           .
      * <TOTEM:END>
       TOOL-CERCA-LinkTo.
      * <TOTEM:PARA. TOOL-CERCA-LinkTo>
           inquire tool-cerca, enabled in e-cerca
           if e-cerca = 1
              perform CERCA
           end-if 
           .
      * <TOTEM:END>
       TOOL-SELEZIONA-LinkTo.
      * <TOTEM:PARA. TOOL-SELEZIONA-LinkTo>
           inquire tool-seleziona, enabled in e-seleziona
           if e-seleziona = 1
              perform SELEZIONA
           end-if 
           .
      * <TOTEM:END>
       TOOL-PRIMO.
      * <TOTEM:PARA. TOOL-PRIMO>
           PERFORM PRIMO 
           .
      * <TOTEM:END>
       TOOL-PRECEDENTE.
      * <TOTEM:PARA. TOOL-PRECEDENTE>
           if nuovo             
              perform PRIMO
           else
              perform PRECEDENTE
           end-if 
           .
      * <TOTEM:END>
       TOOL-SUCCESSIVO.
      * <TOTEM:PARA. TOOL-SUCCESSIVO>
           if nuovo             
              perform ULTIMO
           else
              perform SUCCESSIVO
           end-if 
           .
      * <TOTEM:END>
       TOOL-ULTIMO.
      * <TOTEM:PARA. TOOL-ULTIMO>
           PERFORM ULTIMO 
           .
      * <TOTEM:END>
       ginqui-Ev-Before-Program.
      * <TOTEM:PARA. ginqui-Ev-Before-Program>
           move LK-BL-PROG-ID    TO COMO-PROG-ID 
           .
      * <TOTEM:END>
       ginqui-Ev-After-Program.
      * <TOTEM:PARA. ginqui-Ev-After-Program>
           SET LK-BL-CANCELLAZIONE TO TRUE.
           MOVE COMO-PROG-ID       TO LK-BL-PROG-ID.
           CALL "BLOCKPGM"  USING LK-BLOCKPGM 
           .
      * <TOTEM:END>
       TOOL-ORD-LinkTo.
      * <TOTEM:PARA. TOOL-ORD-LinkTo>
           perform ORDINAMENTO 
           .
      * <TOTEM:END>
       TOOL-ORD-BeforeProcedure.
      * <TOTEM:PARA. TOOL-ORD-BeforeProcedure>
           MODIFY CONTROL-HANDLE COLOR = COLORE-NU
           .
      * <TOTEM:END>
       TOOL-ORD-AfterProcedure.
      * <TOTEM:PARA. TOOL-ORD-AfterProcedure>
           MODIFY CONTROL-HANDLE COLOR = COLORE-OR
           .
      * <TOTEM:END>
       ef-codice-BeforeProcedure.
      * <TOTEM:PARA. ef-codice-BeforeProcedure>
           MODIFY CONTROL-HANDLE COLOR = COLORE-NU
           .
      * <TOTEM:END>
       Screen1-DaEf-1-BeforeProcedure.
      * <TOTEM:PARA. Screen1-DaEf-1-BeforeProcedure>
           MODIFY CONTROL-HANDLE COLOR = COLORE-NU
           .
      * <TOTEM:END>
       ef-codice-AfterProcedure.
      * <TOTEM:PARA. ef-codice-AfterProcedure>
              INQUIRE ef-codice, VALUE IN art-codice
              SET TOTEM-CHECK-OK TO FALSE
              PERFORM ef-codice-VALIDATION
              IF NOT TOTEM-CHECK-OK
                 MOVE 1 TO ACCEPT-CONTROL
              END-IF
           MODIFY CONTROL-HANDLE COLOR = COLORE-OR

           .
      * <TOTEM:END>

       Screen1-DaEf-1-AfterProcedure.
      * <TOTEM:PARA. Screen1-DaEf-1-AfterProcedure>
              INQUIRE ef-note, VALUE IN art-note
              SET TOTEM-CHECK-OK TO FALSE
              PERFORM ef-note-VALIDATION
              IF NOT TOTEM-CHECK-OK
                 MOVE 1 TO ACCEPT-CONTROL
              END-IF
           MODIFY CONTROL-HANDLE COLOR = COLORE-OR

           .
      * <TOTEM:END>

       ef-ragsoc-AfterProcedure.
      * <TOTEM:PARA. ef-ragsoc-AfterProcedure>
              INQUIRE ef-descr, VALUE IN art-descrizione
              SET TOTEM-CHECK-OK TO FALSE
              PERFORM ef-descr-VALIDATION
              IF NOT TOTEM-CHECK-OK
                 MOVE 1 TO ACCEPT-CONTROL
              END-IF
           MODIFY CONTROL-HANDLE COLOR = COLORE-OR

           .
      * <TOTEM:END>

       ef-descr-BeforeProcedure.
      * <TOTEM:PARA. ef-descr-BeforeProcedure>
           MODIFY CONTROL-HANDLE COLOR = COLORE-NU
           .
      * <TOTEM:END>

      *{TOTEM}END

      *{TOTEM}SHOW-MSG
       MESSAGE-FOR-FILEERROR.
           CALL "C$RERRNAME" USING TOTEM-MSG-ERR-FILE
           CALL "C$RERR" USING EXTEND-STAT, TEXT-MESSAGE
              MOVE PRIMARY-ERROR TO TOTEM-MSG-ID
           .

       SHOW-TRANSACTION-ROUTINE.
           IF TOTEM-TRANSACTION-FLAG = SPACES
              IF TRANSACTION-STATUS NOT = 0
                 STRING "TRANSACTION ERROR ", TRANSACTION-STATUS
                    DELIMITED BY SIZE INTO TOTEM-MSG-1
              END-IF
           ELSE
              PERFORM SHOW-MSG-ROUTINE
              IF TRANSACTION-STATUS = 0
                 MOVE "Transazione terminata con Rollback." TO 
           TOTEM-MSG-3
              ELSE
                 STRING "TRANSACTION ERROR ", TRANSACTION-STATUS
                    DELIMITED BY SIZE INTO TOTEM-MSG-3
              END-IF
           END-IF
           .

       SHOW-MSG-ROUTINE.
           MOVE SPACE TO TOTEM-MSG-1 TOTEM-MSG-2 TOTEM-MSG-3
           EVALUATE TOTEM-MSG-ID
               WHEN "10"
                    STRING "File:" TOTEM-MSG-ERR-FILE DELIMITED BY SPACE
                       INTO TOTEM-MSG-1
                    MOVE "Nessun altro dato." TO TOTEM-MSG-2
                    MOVE MB-DEFAULT-ICON TO TOTEM-MSG-ICON-TYPE
                    MOVE MB-OK TO TOTEM-MSG-BUTTON-TYPE
               WHEN "22"
                    STRING "File:" TOTEM-MSG-ERR-FILE DELIMITED BY SPACE
                       INTO TOTEM-MSG-1
                    MOVE "Chiave Duplicata." TO TOTEM-MSG-2
                    MOVE MB-ERROR-ICON TO TOTEM-MSG-ICON-TYPE
                    MOVE MB-OK TO TOTEM-MSG-BUTTON-TYPE
               WHEN "23"
                    STRING "File:" TOTEM-MSG-ERR-FILE DELIMITED BY SPACE
                       INTO TOTEM-MSG-1
                    MOVE "Raggiunta fine file." TO TOTEM-MSG-2
                    MOVE MB-WARNING-ICON TO TOTEM-MSG-ICON-TYPE
                    MOVE MB-OK TO TOTEM-MSG-BUTTON-TYPE
               WHEN "101"
                    MOVE "Terminare l'applicazione?" TO TOTEM-MSG-1
                    MOVE 4 TO TOTEM-MSG-ICON-TYPE
                    MOVE MB-YES-NO TO TOTEM-MSG-BUTTON-TYPE
               WHEN "201"
                    MOVE "Aggiungere un nuovo record?" TO TOTEM-MSG-1
                    MOVE 4 TO TOTEM-MSG-ICON-TYPE
                    MOVE MB-YES-NO TO TOTEM-MSG-BUTTON-TYPE
               WHEN "202"
                    MOVE "Aggiornare il Record?" TO TOTEM-MSG-1
                    MOVE 4 TO TOTEM-MSG-ICON-TYPE
                    MOVE MB-YES-NO TO TOTEM-MSG-BUTTON-TYPE
               WHEN "203"
                    MOVE "Cancellare il Record?" TO TOTEM-MSG-1
                    MOVE 4 TO TOTEM-MSG-ICON-TYPE
                    MOVE MB-YES-NO TO TOTEM-MSG-BUTTON-TYPE
               WHEN "204"
                    MOVE "Chiave duplicata." TO TOTEM-MSG-1
                    MOVE MB-WARNING-ICON TO TOTEM-MSG-ICON-TYPE
                    MOVE MB-OK TO TOTEM-MSG-BUTTON-TYPE
               WHEN "301"
                    MOVE "Inserimento avvenuto con Successo." TO 
           TOTEM-MSG-1
                    MOVE MB-DEFAULT-ICON TO TOTEM-MSG-ICON-TYPE
                    MOVE MB-OK TO TOTEM-MSG-BUTTON-TYPE
               WHEN "302"
                    MOVE "Aggiornamento avvenuto con Successo." TO 
           TOTEM-MSG-1
                    MOVE MB-DEFAULT-ICON TO TOTEM-MSG-ICON-TYPE
                    MOVE MB-OK TO TOTEM-MSG-BUTTON-TYPE
               WHEN "303"
                    MOVE "Cancellazione avvenuta con Successo." TO 
           TOTEM-MSG-1
                    MOVE MB-DEFAULT-ICON TO TOTEM-MSG-ICON-TYPE
                    MOVE MB-OK TO TOTEM-MSG-BUTTON-TYPE
               WHEN "401"
                    MOVE "Shell non trovata." TO TOTEM-MSG-1
                    MOVE MB-ERROR-ICON TO TOTEM-MSG-ICON-TYPE
                    MOVE MB-OK TO TOTEM-MSG-BUTTON-TYPE
               WHEN OTHER
                    MOVE TEXT-MESSAGE TO TOTEM-MSG-1
                    STRING "FILE:" TOTEM-MSG-ERR-FILE DELIMITED BY SPACE
                       INTO TOTEM-MSG-3
                    MOVE 0 TO TOTEM-IDX1
                    INSPECT TOTEM-MSG-3 TALLYING TOTEM-IDX1
                       FOR TRAILING SPACE
                    STRING TOTEM-MSG-3(1:TOTEM-MSG-LENGTH - 
           TOTEM-IDX1), 
                       ", FILE STATUS ", PRIMARY-ERROR "," 
                       SECONDARY-ERROR
                    DELIMITED BY SIZE INTO TOTEM-MSG-2
                    MOVE SPACES TO TOTEM-MSG-3
                    MOVE MB-ERROR-ICON TO TOTEM-MSG-ICON-TYPE
                    MOVE MB-OK TO TOTEM-MSG-BUTTON-TYPE
           END-EVALUATE
           PERFORM MESSAGE-BOX-ROUTINE
           .

       MESSAGE-BOX-ROUTINE.
           MOVE 1 TO TOTEM-MSG-TEXT-POINTER
           IF TOTEM-MSG-1 NOT = SPACE
              MOVE 0 TO TOTEM-MSG-SIZE
              INSPECT TOTEM-MSG-1 TALLYING TOTEM-MSG-SIZE FOR TRAILING 
           SPACE
              STRING TOTEM-MSG-1( 1 : TOTEM-MSG-LENGTH - TOTEM-MSG-SIZE 
           )
                 DELIMITED BY SIZE
                 INTO TOTEM-MSG-TEXT, POINTER TOTEM-MSG-TEXT-POINTER
           END-IF

           IF TOTEM-MSG-2 NOT = SPACE
              MOVE 0 TO TOTEM-MSG-SIZE
              INSPECT TOTEM-MSG-2 TALLYING TOTEM-MSG-SIZE FOR TRAILING 
           SPACE
              IF TOTEM-MSG-TEXT-POINTER > 1
                 STRING X"0A" DELIMITED BY SIZE
                     INTO TOTEM-MSG-TEXT, POINTER TOTEM-MSG-TEXT-POINTER
              END-IF
              STRING TOTEM-MSG-2( 1 : TOTEM-MSG-LENGTH - TOTEM-MSG-SIZE 
           )
                  DELIMITED BY SIZE
                  INTO TOTEM-MSG-TEXT, POINTER TOTEM-MSG-TEXT-POINTER
           END-IF

           IF TOTEM-MSG-3 NOT = SPACE
              MOVE 0 TO TOTEM-MSG-SIZE
              INSPECT TOTEM-MSG-3 TALLYING TOTEM-MSG-SIZE FOR TRAILING 
           SPACE
              IF TOTEM-MSG-TEXT-POINTER > 1
                 STRING X"0A" DELIMITED BY SIZE
                     INTO TOTEM-MSG-TEXT, POINTER TOTEM-MSG-TEXT-POINTER
              END-IF
              STRING TOTEM-MSG-3( 1 : TOTEM-MSG-LENGTH - TOTEM-MSG-SIZE 
           )
                  DELIMITED BY SIZE
                  INTO TOTEM-MSG-TEXT, POINTER TOTEM-MSG-TEXT-POINTER
           END-IF

           IF TOTEM-MSG-TEXT-POINTER = 1
              MOVE 0 TO TOTEM-MSG-SIZE
              INSPECT TOTEM-MSG-TEXT TALLYING TOTEM-MSG-SIZE FOR 
           TRAILING SPACE
                  COMPUTE TOTEM-MSG-TEXT-POINTER = 
           TOTEM-MSG-FULL-LENGTH - TOTEM-MSG-SIZE + 1
           END-IF
           MOVE LOW-VALUES TO TOTEM-MSG-TEXT(TOTEM-MSG-TEXT-POINTER : 1 
           )
           .

       MESSAGE-BOX-DISPLAY.
           PERFORM SHOW-MSG-ROUTINE
           PERFORM MESSAGE-BOX-ROUTINE
           DISPLAY MESSAGE BOX TOTEM-MSG-TEXT
               TITLE IS TOTEM-MSG-TITLE
               TYPE  IS TOTEM-MSG-BUTTON-TYPE
               ICON  IS TOTEM-MSG-DEFAULT-BUTTON
               RETURNING TOTEM-MSG-RETURN-VALUE
           .

      *{TOTEM}END

