      *{TOTEM}PRG-COMMENT
      * menu.Cbl
      * menu.Cbl is generated by TOTEM
      * This is a generated file. DO NOT modify this file directly.
      *{TOTEM}END
       IDENTIFICATION       DIVISION.
      *{TOTEM}PRGID
       PROGRAM-ID.          "menu".
       AUTHOR.              andre.
       DATE-WRITTEN.        giovedì 29 aprile 2021 15:11:48.
       REMARKS.
      *{TOTEM}END

       ENVIRONMENT          DIVISION.
       CONFIGURATION        SECTION.
       SPECIAL-NAMES.
      *{TOTEM}SPECIAL-NAME
      * <TOTEM:EPT. INIT:menu, INIT:menu, SpecialName>
      * <TOTEM:END>
      *{TOTEM}END
      *{TOTEM}ACTIVEX-DEF
      *{TOTEM}END
      *{TOTEM}DECIMAL-POINT
           DECIMAL-POINT IS COMMA.
      *{TOTEM}END

       INPUT-OUTPUT         SECTION.
       FILE-CONTROL.
      *{TOTEM}FILE-CONTROL
           COPY "param.sl".
           COPY "lineseq.sl".
      *{TOTEM}END
       DATA                 DIVISION.
       FILE                 SECTION.
      *{TOTEM}FILE
           COPY "param.fd".
           COPY "lineseq.fd".
      *{TOTEM}END

       WORKING-STORAGE      SECTION.
      *{TOTEM}ACU-DEF
               COPY "acugui.def".
               COPY "acucobol.def".
               COPY "fonts.def".
               COPY "crtvars.def".
               COPY "showmsg.def".
               COPY "totem.def".
               COPY "comune.def".
               COPY "custom.def".
               COPY "UTYDATA.DEF".
      *{TOTEM}END

      *{TOTEM}COPY-WORKING
      * Key Status
       77 Key-Status IS SPECIAL-NAMES CRT STATUS PIC 9(5) VALUE 0.
          88 Enter-Pushed VALUE 13.
          88 Exit-Pushed VALUE 27.
          88 Message-Received VALUE 95.
          88 Event-Occurred VALUE 96.
          88 Screen-No-Input-Field VALUE 97.
          88 Screen-Time-Out VALUE 99.
      * Properties & User defined Working Stoarge
       77 HND-WIN-ATTIVA
                  USAGE IS HANDLE OF WINDOW.
       77 Screen1-Handle
                  USAGE IS HANDLE OF WINDOW.
       78 titolo VALUE IS "Studio - Menu Principale". 
       77 Screen1-Bt-1-Handle          PIC  S9(9)
                  USAGE IS COMP-4
                  VALUE IS 0.
       77 QUADRATO_MEDIO2-BMP          PIC  S9(9)
                  USAGE IS COMP-4
                  VALUE IS 0.
       77 Small-Font
                  USAGE IS HANDLE OF FONT SMALL-FONT.
       77 strip-menu-bmp   PIC  S9(9)
                  USAGE IS COMP-4
                  VALUE IS 0.
       77 Calibri16-Occidentale
                  USAGE IS HANDLE OF FONT.
       77 tit-frame        PIC  x(50).
       77 Calibri20-Occidentale
                  USAGE IS HANDLE OF FONT.
       77 NomeProgramma    PIC  x(20).
       77 link-status
                  USAGE IS SIGNED-SHORT.
       77 sessioni         PIC  99.
       77 comando          PIC  x(200).
       77 STATUS-param     PIC  X(2).
           88 Valid-STATUS-param VALUE IS "00" THRU "09". 
           COPY  "BLOCKPGM.LKS".
       77 wstampa          PIC  X(256).
       77 STATUS-lineseq   PIC  X(2).
           88 Valid-STATUS-lineseq VALUE IS "00" THRU "09". 

      ***********************************************************
      *   Code Gen's Buffer                                     *
      ***********************************************************
       77 STATUS-Screen1-FLAG-REFRESH PIC  9.
          88 Screen1-FLAG-REFRESH  VALUE 1 FALSE 0. 
       77 TMP-DataSet1-param-BUF     PIC X(1125).
       77 TMP-DataSet1-lineseq-BUF     PIC X(900).
      * VARIABLES FOR RECORD LENGTH.
       77  TotemFdSlRecordClearOffset   PIC 9(5) COMP-4.
       77  TotemFdSlRecordLength        PIC 9(5) COMP-4.
      * FILE'S LOCK MODE FLAG
       77 DataSet1-param-LOCK-FLAG   PIC X VALUE SPACE.
           88 DataSet1-param-LOCK  VALUE "Y".
       77 DataSet1-KEYIS   PIC 9(3) VALUE 1.
       77 DataSet1-param-KEY1-ORDER  PIC X VALUE "A".
          88 DataSet1-param-KEY1-Asc  VALUE "A".
          88 DataSet1-param-KEY1-Desc VALUE "D".
       77 DataSet1-lineseq-LOCK-FLAG   PIC X VALUE SPACE.
           88 DataSet1-lineseq-LOCK  VALUE "Y".
       77 DataSet1-lineseq-KEY-ORDER  PIC X VALUE "A".
          88 DataSet1-lineseq-KEY-Asc  VALUE "A".
          88 DataSet1-lineseq-KEY-Desc VALUE "D".


      *{TOTEM}END

      *{TOTEM}ID-LOGICI
      ***** Elenco ID Logici *****
      ***** Fine ID Logici *****
      *{TOTEM}END

       LINKAGE          SECTION.
      *{TOTEM}LINKAGE
      *{TOTEM}END

       SCREEN           SECTION.
      *{TOTEM}COPY-SCREEN
      * FORM
       01 
           Screen1, 
           .

      * FRAME
       05
           frame-menu, 
           Frame, 
           COL 2,00, 
           LINE 1,39,
           LINES 20,21 ,
           SIZE 63,07 ,
           COLOR IS 11,
           ID IS 1,
           HEIGHT-IN-CELLS,
           WIDTH-IN-CELLS,
           HEAVY,
           TITLE tit-frame,
           TITLE-POSITION 2,
           .

      * PUSH BUTTON
       05
           pb-clienti, 
           Push-Button, 
           COL 3,79, 
           LINE 2,66,
           LINES 130,00 ,
           SIZE 260,00 ,
           BITMAP-HANDLE STRIP-MENU-BMP,
           BITMAP-NUMBER 1,
           FRAMED,
           SQUARE,
           EXCEPTION-VALUE 1,
           ID IS 3,
           TITLE "Gestione Clienti (F1)",
           .

      * PUSH BUTTON
       05
           pb-articoli, 
           Push-Button, 
           COL 24,07, 
           LINE 2,66,
           LINES 130,00 ,
           SIZE 260,00 ,
           BITMAP-HANDLE STRIP-MENU-BMP,
           BITMAP-NUMBER 2,
           FRAMED,
           SQUARE,
           EXCEPTION-VALUE 2,
           ID IS 4,
           TITLE "Anagrafica Articoli (F2)",
           .

      * PUSH BUTTON
       05
           pb-iva, 
           Push-Button, 
           COL 44,36, 
           LINE 2,66,
           LINES 130,00 ,
           SIZE 260,00 ,
           BITMAP-HANDLE STRIP-MENU-BMP,
           BITMAP-NUMBER 3,
           FRAMED,
           SQUARE,
           EXCEPTION-VALUE 3,
           ID IS 5,
           TITLE "Tabella IVA (F3)",
           .

      * PUSH BUTTON
       05
           pb-catcli, 
           Push-Button, 
           COL 3,50, 
           LINE 7,33,
           LINES 130,00 ,
           SIZE 260,00 ,
           BITMAP-HANDLE STRIP-MENU-BMP,
           BITMAP-NUMBER 4,
           FRAMED,
           SQUARE,
           EXCEPTION-VALUE 4,
           ID IS 6,
           TITLE "Categorie Clienti (F4)",
           .

      * PUSH BUTTON
       05
           pb-param, 
           Push-Button, 
           COL 24,07, 
           LINE 7,33,
           LINES 130,00 ,
           SIZE 260,00 ,
           BITMAP-HANDLE STRIP-MENU-BMP,
           BITMAP-NUMBER 5,
           FRAMED,
           SQUARE,
           EXCEPTION-VALUE 5,
           ID IS 7,
           TITLE "Parametri Ditta (F5)",
           .

      * PUSH BUTTON
       05
           pb-listini, 
           Push-Button, 
           COL 44,36, 
           LINE 7,33,
           LINES 130,00 ,
           SIZE 260,00 ,
           BITMAP-HANDLE STRIP-MENU-BMP,
           BITMAP-NUMBER 6,
           FRAMED,
           SQUARE,
           EXCEPTION-VALUE 6,
           ID IS 8,
           TITLE "Listini Clienti (F6)",
           .

      * PUSH BUTTON
       05
           pb-schede, 
           Push-Button, 
           COL 3,50, 
           LINE 12,03,
           LINES 130,00 ,
           SIZE 260,00 ,
           BITMAP-HANDLE STRIP-MENU-BMP,
           BITMAP-NUMBER 7,
           FRAMED,
           SQUARE,
           EXCEPTION-VALUE 7,
           ID IS 9,
           TITLE "Schede Clienti (F7)",
           .

      * PUSH BUTTON
       05
           pb-fatture, 
           Push-Button, 
           COL 24,07, 
           LINE 12,03,
           LINES 130,00 ,
           SIZE 260,00 ,
           BITMAP-HANDLE STRIP-MENU-BMP,
           BITMAP-NUMBER 8,
           FRAMED,
           SQUARE,
           EXCEPTION-VALUE 8,
           ID IS 10,
           TITLE "Fatture / Corrispettivi (F8)",
           .

      * PUSH BUTTON
       05
           pb-report, 
           Push-Button, 
           COL 3,50, 
           LINE 16,75,
           LINES 130,00 ,
           SIZE 260,00 ,
           BITMAP-HANDLE STRIP-MENU-BMP,
           BITMAP-NUMBER 9,
           FRAMED,
           SQUARE,
           EXCEPTION-VALUE 10,
           ID IS 11,
           TITLE "Reportistica Fatturati (F10)",
           .

      * PUSH BUTTON
       05
           pb-note, 
           Push-Button, 
           COL 44,36, 
           LINE 12,03,
           LINES 130,00 ,
           SIZE 260,00 ,
           BITMAP-HANDLE STRIP-MENU-BMP,
           BITMAP-NUMBER 10,
           FRAMED,
           SQUARE,
           EXCEPTION-VALUE 9,
           ID IS 12,
           TITLE "Note Credito (F9)",
           .

      * PUSH BUTTON
       05
           pb-exit, 
           Push-Button, 
           COL 44,36, 
           LINE 16,75,
           LINES 130,00 ,
           SIZE 260,00 ,
           BITMAP-HANDLE STRIP-MENU-BMP,
           BITMAP-NUMBER 11,
           FRAMED,
           SQUARE,
           EXCEPTION-VALUE 27,
           ID IS 13,
           ESCAPE-BUTTON,
           TITLE "Esce dal programma (Esc)",
           .

      * PUSH BUTTON
       05
           pb-appuntamenti, 
           Push-Button, 
           COL 24,07, 
           LINE 16,75,
           LINES 130,00 ,
           SIZE 260,00 ,
           BITMAP-HANDLE STRIP-MENU-BMP,
           BITMAP-NUMBER 12,
           FRAMED,
           SQUARE,
           EXCEPTION-VALUE 11,
           ID IS 14,
           TITLE "Gestione appuntamenti (F11)",
           .

      *{TOTEM}END

      *{TOTEM}LINKPARA
       PROCEDURE        DIVISION.
      *{TOTEM}END

      *{TOTEM}DECLARATIVE
       DECLARATIVES.
      * <TOTEM:EPT. INIT:menu, INIT:menu, BeforeDeclarative>
       LINESEQ-ERR SECTION.
           use after error procedure on lineseq.

      * <TOTEM:END>
       INPUT-ERROR SECTION.
           USE AFTER STANDARD ERROR PROCEDURE ON INPUT.
       0100-DECL.
           EXIT.
       I-O-ERROR SECTION.
           USE AFTER STANDARD ERROR PROCEDURE ON I-O.
       0200-DECL.
           EXIT.
       OUTPUT-ERROR SECTION.
           USE AFTER STANDARD ERROR PROCEDURE ON OUTPUT.
       0300-DECL.
           EXIT.
       TRANSACTION-ERROR SECTION.
           USE AFTER STANDARD ERROR PROCEDURE ON TRANSACTION.
       0400-DECL.
           EXIT.
       END DECLARATIVES.
      *{TOTEM}END

       MAIN-LOGIC.
      *{TOTEM}ENTRY-BEFPRG
      *    Before-Program
           PERFORM menu-Ev-Before-Program
      *{TOTEM}END
           PERFORM INITIALIZE-ROUTINE.
      * run main screen
      *{TOTEM}RUN-MAINSCR
           PERFORM Screen1-OPEN-ROUTINE.
      *{TOTEM}END

      *{TOTEM}COPY-PROCEDURE
       EXIT-STOP-ROUTINE.
           PERFORM CLOSE-FILE-RTN
      * <TOTEM:EPT. INIT:menu, INIT:menu, BeforeDestroyResource>
      * <TOTEM:END>
           DESTROY Calibri20-Occidentale
           CALL "w$bitmap" USING WBITMAP-DESTROY, STRIP-MENU-BMP
      *    After-Program
           EXIT PROGRAM TOTEM-PgmStatus
           STOP RUN.

       INITIALIZE-ROUTINE.
      *    Before Init
      * initialize program status variable
           Initialize TOTEM-PgmStatus.
      * get system information
           ACCEPT SYSTEM-INFORMATION FROM SYSTEM-INFO.
      * get terminal information
           ACCEPT TERMINAL-ABILITIES FROM TERMINAL-INFO.
      * set font
           PERFORM INIT-FONT.
      * load bitmap
           PERFORM INIT-BMP.
      * load resource
           PERFORM INIT-RES.
      * create pop-up menu
           PERFORM INIT-POPUP.
      * open files
           PERFORM OPEN-FILE-RTN.
      *    After Init
           .
    
       INIT-FONT.
      * Calibri20-Occidentale
           INITIALIZE WFONT-DATA Calibri20-Occidentale
           MOVE 20 TO WFONT-SIZE
           MOVE "Calibri" TO WFONT-NAME
           SET WFCHARSET-DONT-CARE TO TRUE
           SET WFONT-BOLD TO FALSE
           SET WFONT-ITALIC TO FALSE
           SET WFONT-UNDERLINE TO FALSE
           SET WFONT-STRIKEOUT TO FALSE
           SET WFONT-FIXED-PITCH TO FALSE
           MOVE 0 TO WFONT-CHAR-SET
           CALL "W$FONT" USING WFONT-GET-FONT, 
                     Calibri20-Occidentale, WFONT-DATA
           .

       INIT-BMP.
      * pb-clienti
           COPY RESOURCE "STRIP-MENU.BMP".
           CALL "w$bitmap" USING WBITMAP-LOAD "STRIP-MENU.BMP", 
                   GIVING STRIP-MENU-BMP.
           .

       INIT-RES.
           .

       INIT-POPUP.
           .

       OPEN-FILE-RTN.
      *    Before Open
           PERFORM OPEN-param
      *    lineseq OPEN MODE IS FALSE
      *    PERFORM OPEN-lineseq
      *    After Open
           .

       OPEN-param.
      * <TOTEM:EPT. INIT:menu, FD:param, BeforeOpen>
      * <TOTEM:END>
           OPEN  INPUT param
           IF NOT Valid-STATUS-param
              PERFORM  Screen1-EXTENDED-FILE-STATUS
              GO TO EXIT-STOP-ROUTINE
           END-IF
      * <TOTEM:EPT. INIT:menu, FD:param, AfterOpen>
      * <TOTEM:END>
           .

       OPEN-lineseq.
      * <TOTEM:EPT. INIT:menu, FD:lineseq, BeforeOpen>
      * <TOTEM:END>
           OPEN  INPUT lineseq
           IF NOT Valid-STATUS-lineseq
              PERFORM  Screen1-EXTENDED-FILE-STATUS
              GO TO EXIT-STOP-ROUTINE
           END-IF
      * <TOTEM:EPT. INIT:menu, FD:lineseq, AfterOpen>
      * <TOTEM:END>
           .

       CLOSE-FILE-RTN.
      *    Before Close
           PERFORM CLOSE-param
      *    lineseq CLOSE MODE IS FALSE
      *    PERFORM CLOSE-lineseq
      *    After Close
           .

       CLOSE-param.
      * <TOTEM:EPT. INIT:menu, FD:param, BeforeClose>
      * <TOTEM:END>
           CLOSE param
           .

       CLOSE-lineseq.
      * <TOTEM:EPT. INIT:menu, FD:lineseq, BeforeClose>
      * <TOTEM:END>
           .

       DataSet1-param-INITSTART.
           EVALUATE DataSet1-KEYIS
           WHEN 1
              IF DataSet1-param-KEY1-Asc
                 MOVE Low-Value TO prm-chiave
              ELSE
                 MOVE High-Value TO prm-chiave
              END-IF
           END-EVALUATE
           .

       DataSet1-param-INITEND.
           EVALUATE DataSet1-KEYIS
           WHEN 1
              IF DataSet1-param-KEY1-Asc
                 MOVE High-Value TO prm-chiave
              ELSE
                 MOVE Low-Value TO prm-chiave
              END-IF
           END-EVALUATE
           .

       DataSet1-CHANGETO-KEY1.
           MOVE 1 TO DataSet1-KEYIS
           .   

       DataSet1-Change-CurrentKey-Asc.
           EVALUATE DataSet1-KEYIS
           WHEN 1
              MOVE "A" TO DataSet1-param-KEY1-ORDER
           END-EVALUATE
           .

       DataSet1-Change-CurrentKey-Desc.
           EVALUATE DataSet1-KEYIS
           WHEN 1
              MOVE "D" TO DataSet1-param-KEY1-ORDER
           END-EVALUATE
           .

      * param
       DataSet1-param-START.
           EVALUATE DataSet1-KEYIS
           WHEN 1
              IF DataSet1-param-KEY1-Asc
                 START param KEY >= prm-chiave
              ELSE
                 START param KEY <= prm-chiave
              END-IF
           END-EVALUATE
           .

       DataSet1-param-START-NOTGREATER.
           EVALUATE DataSet1-KEYIS
           WHEN 1
              IF DataSet1-param-KEY1-Asc
                 START param KEY <= prm-chiave
              ELSE
                 START param KEY >= prm-chiave
              END-IF
           END-EVALUATE
           .

       DataSet1-param-START-GREATER.
           EVALUATE DataSet1-KEYIS
           WHEN 1
              IF DataSet1-param-KEY1-Asc
                 START param KEY > prm-chiave
              ELSE
                 START param KEY < prm-chiave
              END-IF
           END-EVALUATE
           .

       DataSet1-param-START-LESS.
           EVALUATE DataSet1-KEYIS
           WHEN 1
              IF DataSet1-param-KEY1-Asc
                 START param KEY < prm-chiave
              ELSE
                 START param KEY > prm-chiave
              END-IF
           END-EVALUATE
           .

       DataSet1-param-Read.
      * <TOTEM:EPT. FD:DataSet1, FD:param, BeforeRead>
      * <TOTEM:END>
      * <TOTEM:EPT. FD:DataSet1, FD:param, BeforeReadRecord>
      * <TOTEM:END>
           EVALUATE DataSet1-KEYIS
           WHEN 1
              IF DataSet1-param-LOCK
                 READ param WITH LOCK 
                 KEY prm-chiave
              ELSE
                 READ param WITH NO LOCK 
                 KEY prm-chiave
              END-IF
           END-EVALUATE
           MOVE STATUS-param TO TOTEM-ERR-STAT 
           MOVE "param" TO TOTEM-ERR-FILE
           MOVE "READ" TO TOTEM-ERR-MODE
      * <TOTEM:EPT. FD:DataSet1, FD:param, AfterRead>
      * <TOTEM:END>
      * <TOTEM:EPT. FD:DataSet1, FD:param, AfterReadRecord>
      * <TOTEM:END>
           .

       DataSet1-param-Read-Next.
      * <TOTEM:EPT. FD:DataSet1, FD:param, BeforeRead>
      * <TOTEM:END>
      * <TOTEM:EPT. FD:DataSet1, FD:param, BeforeReadNext>
      * <TOTEM:END>
           EVALUATE DataSet1-KEYIS
           WHEN 1
              IF DataSet1-param-KEY1-Asc
                 IF DataSet1-param-LOCK
                    READ param NEXT WITH LOCK
                 ELSE
                    READ param NEXT WITH NO LOCK
                 END-IF
              ELSE
                 IF DataSet1-param-LOCK
                    READ param PREVIOUS WITH LOCK
                 ELSE
                    READ param PREVIOUS WITH NO LOCK
                 END-IF
              END-IF
           END-EVALUATE
           MOVE STATUS-param TO TOTEM-ERR-STAT
           MOVE "param" TO TOTEM-ERR-FILE
           MOVE "READ NEXT" TO TOTEM-ERR-MODE
      * <TOTEM:EPT. FD:DataSet1, FD:param, AfterRead>
      * <TOTEM:END>
      * <TOTEM:EPT. FD:DataSet1, FD:param, AfterReadNext>
      * <TOTEM:END>
           .

       DataSet1-param-Read-Prev.
      * <TOTEM:EPT. FD:DataSet1, FD:param, BeforeRead>
      * <TOTEM:END>
      * <TOTEM:EPT. FD:DataSet1, FD:param, BeforeReadPrev>
      * <TOTEM:END>
           EVALUATE DataSet1-KEYIS
           WHEN 1
              IF DataSet1-param-KEY1-Asc
                 IF DataSet1-param-LOCK
                    READ param PREVIOUS WITH LOCK
                 ELSE
                    READ param PREVIOUS WITH NO LOCK
                 END-IF
              ELSE
                 IF DataSet1-param-LOCK
                    READ param NEXT WITH LOCK
                 ELSE
                    READ param NEXT WITH NO LOCK
                 END-IF
              END-IF
           END-EVALUATE
           MOVE STATUS-param TO TOTEM-ERR-STAT
           MOVE "param" TO TOTEM-ERR-FILE
           MOVE "READ PREVIOUS" TO TOTEM-ERR-MODE
      * <TOTEM:EPT. FD:DataSet1, FD:param, AfterRead>
      * <TOTEM:END>
      * <TOTEM:EPT. FD:DataSet1, FD:param, AfterReadPrev>
      * <TOTEM:END>
           .

       DataSet1-param-Rec-Write.
      * <TOTEM:EPT. FD:DataSet1, FD:param, BeforeWrite>
      * <TOTEM:END>
           MOVE STATUS-param TO TOTEM-ERR-STAT
           MOVE "param" TO TOTEM-ERR-FILE
           MOVE "WRITE" TO TOTEM-ERR-MODE
      * <TOTEM:EPT. FD:DataSet1, FD:param, AfterWrite>
      * <TOTEM:END>
           .

       DataSet1-param-Rec-Rewrite.
      * <TOTEM:EPT. FD:DataSet1, FD:param, BeforeRewrite>
      * <TOTEM:END>
           MOVE STATUS-param TO TOTEM-ERR-STAT
           MOVE "param" TO TOTEM-ERR-FILE
           MOVE "REWRITE" TO TOTEM-ERR-MODE
      * <TOTEM:EPT. FD:DataSet1, FD:param, AfterRewrite>
      * <TOTEM:END>
           .

       DataSet1-param-Rec-Delete.
      * <TOTEM:EPT. FD:DataSet1, FD:param, BeforeDelete>
      * <TOTEM:END>
           MOVE STATUS-param TO TOTEM-ERR-STAT
           MOVE "param" TO TOTEM-ERR-FILE
           MOVE "DELETE" TO TOTEM-ERR-MODE
      * <TOTEM:EPT. FD:DataSet1, FD:param, AfterDelete>
      * <TOTEM:END>
           .

       DataSet1-lineseq-INITSTART.
           .

       DataSet1-lineseq-INITEND.
           .

       DataSet1-lineseq-Read.
      * <TOTEM:EPT. FD:DataSet1, FD:lineseq, BeforeRead>
      * <TOTEM:END>
      * <TOTEM:EPT. FD:DataSet1, FD:lineseq, BeforeReadRecord>
      * <TOTEM:END>
           IF DataSet1-lineseq-LOCK
              READ lineseq WITH LOCK 
           ELSE
              READ lineseq WITH NO LOCK 
           END-IF
           MOVE STATUS-lineseq TO TOTEM-ERR-STAT 
           MOVE "lineseq" TO TOTEM-ERR-FILE
           MOVE "READ" TO TOTEM-ERR-MODE
      * <TOTEM:EPT. FD:DataSet1, FD:lineseq, AfterRead>
      * <TOTEM:END>
      * <TOTEM:EPT. FD:DataSet1, FD:lineseq, AfterReadRecord>
      * <TOTEM:END>
           .

       DataSet1-lineseq-Read-Next.
      * <TOTEM:EPT. FD:DataSet1, FD:lineseq, BeforeRead>
      * <TOTEM:END>
      * <TOTEM:EPT. FD:DataSet1, FD:lineseq, BeforeReadNext>
      * <TOTEM:END>
           IF DataSet1-lineseq-KEY-Asc
              IF DataSet1-lineseq-LOCK
                 READ lineseq NEXT WITH LOCK
              ELSE
                 READ lineseq NEXT WITH NO LOCK
              END-IF
           END-IF
           MOVE STATUS-lineseq TO TOTEM-ERR-STAT
           MOVE "lineseq" TO TOTEM-ERR-FILE
           MOVE "READ NEXT" TO TOTEM-ERR-MODE
      * <TOTEM:EPT. FD:DataSet1, FD:lineseq, AfterRead>
      * <TOTEM:END>
      * <TOTEM:EPT. FD:DataSet1, FD:lineseq, AfterReadNext>
      * <TOTEM:END>
           .

       DataSet1-lineseq-Read-Prev.
      * <TOTEM:EPT. FD:DataSet1, FD:lineseq, BeforeRead>
      * <TOTEM:END>
      * <TOTEM:EPT. FD:DataSet1, FD:lineseq, BeforeReadPrev>
      * <TOTEM:END>
      * <TOTEM:EPT. FD:DataSet1, FD:lineseq, AfterRead>
      * <TOTEM:END>
      * <TOTEM:EPT. FD:DataSet1, FD:lineseq, AfterReadPrev>
      * <TOTEM:END>
           .

       DataSet1-lineseq-Rec-Write.
      * <TOTEM:EPT. FD:DataSet1, FD:lineseq, BeforeWrite>
      * <TOTEM:END>
           MOVE STATUS-lineseq TO TOTEM-ERR-STAT
           MOVE "lineseq" TO TOTEM-ERR-FILE
           MOVE "WRITE" TO TOTEM-ERR-MODE
      * <TOTEM:EPT. FD:DataSet1, FD:lineseq, AfterWrite>
      * <TOTEM:END>
           .

       DataSet1-lineseq-Rec-Rewrite.
      * <TOTEM:EPT. FD:DataSet1, FD:lineseq, BeforeRewrite>
      * <TOTEM:END>
           MOVE STATUS-lineseq TO TOTEM-ERR-STAT
           MOVE "lineseq" TO TOTEM-ERR-FILE
           MOVE "REWRITE" TO TOTEM-ERR-MODE
      * <TOTEM:EPT. FD:DataSet1, FD:lineseq, AfterRewrite>
      * <TOTEM:END>
           .

       DataSet1-lineseq-Rec-Delete.
      * <TOTEM:EPT. FD:DataSet1, FD:lineseq, BeforeDelete>
      * <TOTEM:END>
           MOVE STATUS-lineseq TO TOTEM-ERR-STAT
           MOVE "lineseq" TO TOTEM-ERR-FILE
           MOVE "DELETE" TO TOTEM-ERR-MODE
      * <TOTEM:EPT. FD:DataSet1, FD:lineseq, AfterDelete>
      * <TOTEM:END>
           .

       DataSet1-INIT-RECORD.
           INITIALIZE prm-rec OF param
           INITIALIZE line-riga OF lineseq
           .


      * FD's Initialize Paragraph
       DataSet1-param-INITREC.
           INITIALIZE prm-rec OF param
               REPLACING NUMERIC       DATA BY ZEROS
                         ALPHANUMERIC  DATA BY SPACES
                         ALPHABETIC    DATA BY SPACES
           .

      * FD's Initialize Paragraph
       DataSet1-lineseq-INITREC.
           INITIALIZE line-riga OF lineseq
               REPLACING NUMERIC       DATA BY ZEROS
                         ALPHANUMERIC  DATA BY SPACES
                         ALPHABETIC    DATA BY SPACES
           .

      *
       DataSet1-DISPATCH-BUFTOFLD.
           .

       Screen1-Open-Routine.
           PERFORM Screen1-Scrn
           PERFORM Screen1-Proc
           .

       Screen1-Scrn.
           PERFORM Screen1-Create-Win
           PERFORM Screen1-Init-Value
           PERFORM Screen1-Init-Data
      * Tab keystrok settings
      * Tool Bar
           PERFORM Screen1-DISPLAY
           .

       Screen1-Create-Win.
           Display Initial GRAPHICAL WINDOW
              LINES 21,00,
              SIZE 65,14,
              HEIGHT-IN-CELLS,
              WIDTH-IN-CELLS,
              COLOR 131329,
              CONTROL FONT Calibri20-Occidentale,
              LINK TO THREAD,
              MODELESS,
              NO SCROLL,
              TITLE-BAR,
              TITLE titolo,
              AUTO-MINIMIZE,
              WITH SYSTEM MENU,
              USER-GRAY,
              USER-WHITE,
              No WRAP,
              EVENT PROCEDURE Screen1-Event-Proc,
              HANDLE IS Screen1-Handle,
      * <TOTEM:EPT. FORM:Screen1, FORM:Screen1, AfterCreateWin>
      * <TOTEM:END>


      * Tool Bar    
      * Status-bar
           DISPLAY Screen1 UPON Screen1-Handle
      * DISPLAY-COLUMNS settings
           .

       Screen1-PROC.
      * <TOTEM:EPT. FORM:Screen1, FORM:Screen1, BeforeAccept>
           move spaces to prm-chiave.
           read param no lock invalid continue end-read.
           move prm-ragsoc to tit-frame.
           modify frame-menu, title tit-frame.

           .
      * <TOTEM:END>
           PERFORM UNTIL Exit-Pushed
              ACCEPT Screen1
                 ON EXCEPTION
                    PERFORM Screen1-Evaluate-Func
                 MOVE 1 TO TOTEM-Form-Index
              END-ACCEPT
      * <TOTEM:EPT. FORM:Screen1, FORM:Screen1, AfterEndAccept>
      * <TOTEM:END>
           END-PERFORM
      * <TOTEM:EPT. FORM:Screen1, FORM:Screen1, BeforeDestroyWindow>
      * <TOTEM:END>
           DESTROY Screen1-Handle
           INITIALIZE Key-Status
           .

       Screen1-Evaluate-Func.
      * <TOTEM:EPT. FORM:Screen1, FORM:Screen1, AfterAccept>
      * <TOTEM:END>
           EVALUATE TRUE
              WHEN Exit-Pushed
                 PERFORM Screen1-Exit
              WHEN Event-Occurred
                 IF Event-Type = Cmd-Close
                    PERFORM Screen1-Exit
                 END-IF
              WHEN Key-Status = 1
                 PERFORM pb-clienti-LinkTo
              WHEN Key-Status = 2
                 PERFORM pb-articoli-LinkTo
              WHEN Key-Status = 3
                 PERFORM pb-iva-LinkTo
              WHEN Key-Status = 4
                 PERFORM pb-catcli-LinkTo
              WHEN Key-Status = 5
                 PERFORM pb-param-LinkTo
              WHEN Key-Status = 6
                 PERFORM pb-listini-LinkTo
              WHEN Key-Status = 7
                 PERFORM pb-schede-LinkTo
              WHEN Key-Status = 8
                 PERFORM pb-fatture-LinkTo
              WHEN Key-Status = 10
                 PERFORM pb-report-LinkTo
              WHEN Key-Status = 9
                 PERFORM pb-note-LinkTo
              WHEN Key-Status = 11
                 PERFORM pb-appuntamenti-LinkTo
           END-EVALUATE
      * avoid changing focus
           MOVE 4 TO Accept-Control
           .

       Screen1-CLEAR.
           PERFORM Screen1-INIT-VALUE
           PERFORM Screen1-DISPLAY
           .

       Screen1-DISPLAY.
      * <TOTEM:EPT. FORM:Screen1, FORM:Screen1, BeforeDisplay>
      * <TOTEM:END>
           DISPLAY Screen1 UPON Screen1-Handle
      * <TOTEM:EPT. FORM:Screen1, FORM:Screen1, AfterDisplay>
      * <TOTEM:END>
           .

       Screen1-Exit.
      * for main screen
      * <TOTEM:EPT. FORM:Screen1, FORM:Screen1, BeforeExit>
      * <TOTEM:END>
           MOVE 27 TO Key-Status
           .

       Screen1-Init-Data.
           MOVE 1 TO TOTEM-Form-Index
           MOVE 0 TO TOTEM-Frame-Index
           .

       Screen1-Init-Value.
           MOVE titolo TO TOTEM-MSG-TITLE
      * <TOTEM:EPT. FORM:Screen1, FORM:Screen1, SetDefault>
      * <TOTEM:END>
           PERFORM Screen1-FLD-TO-BUF
           .


       Screen1-ALLGRID-RESET.
           .

      * for Form's Validation
       Screen1-VALIDATION-ROUTINE.
           SET TOTEM-CHECK-OK TO TRUE
           .


       Screen1-Buf-To-Fld.
      * <TOTEM:EPT. FORM:Screen1, FORM:Screen1, BeforeBufToFld>
      * <TOTEM:END>
      * <TOTEM:EPT. FORM:Screen1, FORM:Screen1, AfterBufToFld>
      * <TOTEM:END>
           .

       Screen1-Fld-To-Buf.
      * <TOTEM:EPT. FORM:Screen1, FORM:Screen1, BeforeFldToBuf>
      * <TOTEM:END>
      * <TOTEM:EPT. FORM:Screen1, FORM:Screen1, AfterFldToBuf>
      * <TOTEM:END>
           .

       Screen1-CONTROLLO-OLD.
           set SiSalvato to true.
           if mod = 0 exit paragraph end-if.
           perform Screen1-BUF-TO-FLD.
           move 0 to scelta.
           .
       Screen1-EXTENDED-FILE-STATUS.
           CALL "C$RERRNAME" USING TOTEM-MSG-ERR-FILE
           CALL "C$RERR" USING EXTEND-STAT, TEXT-MESSAGE
           MOVE PRIMARY-ERROR TO TOTEM-MSG-ID
           PERFORM Screen1-SHOW-MSG-ROUTINE
           .

       Screen1-SHOW-MSG-ROUTINE.
           PERFORM SHOW-MSG-ROUTINE
           PERFORM Screen1-DISPLAY-MESSAGE
           .

       Screen1-DISPLAY-MESSAGE.
           PERFORM MESSAGE-BOX-ROUTINE
           DISPLAY MESSAGE BOX TOTEM-MSG-TEXT
               TITLE IS TOTEM-MSG-TITLE
               TYPE  IS TOTEM-MSG-BUTTON-TYPE
               ICON  IS TOTEM-MSG-DEFAULT-BUTTON
               RETURNING TOTEM-MSG-RETURN-VALUE
           .

       Screen1-Save-Status.
           .             

       Screen1-Restore-Status.
           .



       Screen1-Event-Extra.
           EVALUATE Event-Type
           WHEN Msg-Close
              PERFORM Screen1-MSG-CLOSE
           END-EVALUATE.

       Screen1-MSG-CLOSE.
           ACCEPT TOTEM-QUIT-MODE-FLAG FROM ENVIRONMENT "QUIT_MODE"
           IF TOTEM-QUIT-MODE-FLAG = ZEROS OR SPACES
              PERFORM Screen1-Exit
              IF NOT Exit-Pushed
                 MOVE Event-Action-Fail TO Event-Action
              ELSE
                 PERFORM EXIT-STOP-ROUTINE
              END-IF
           END-IF
           .

       Screen1-Event-Proc.
           IF Event-Control-Id = 0 AND
                 Event-Window-Handle = Screen1-Handle
              PERFORM Screen1-Event-Extra
           END-IF
           .

      * USER DEFINE PARAGRAPH
       CALL-PROGRAM.
      * <TOTEM:PARA. CALL-PROGRAM>
           set lk-bl-lettura to true.
           perform I-O-BLOCCO.
           if not lk-bl-in-uso
              set lk-bl-scrittura to true
              initialize lk-hnd-win
              perform I-O-BLOCCO
              call thread NomeProgramma using lk-blockpgm
              cancel      NomeProgramma
           else
              move lk-hnd-win    to hnd-win-attiva
              set i-o window     to hnd-win-attiva
           end-if.


      ***---
       I-O-BLOCCO.
           accept como-data from century-date.
           MOVE NomeProgramma    TO LK-BL-PROG-ID.
           MOVE COMO-DATA        TO LK-BL-DATA.
           if lk-bl-ora = 0
              MOVE COMO-ORA         TO LK-BL-ORA
           end-if.
           CALL   "BLOCKPGM"  USING LK-BLOCKPGM.
           CANCEL "BLOCKPGM" 
           .
      * <TOTEM:END>

      * EVENT PARAGRAPH
       pb-param-LinkTo.
      * <TOTEM:PARA. pb-param-LinkTo>
           move "gparam" to NomeProgramma.
           perform CALL-PROGRAM 
           .
      * <TOTEM:END>
       menu-Ev-Before-Program.
      * <TOTEM:PARA. menu-Ev-Before-Program>
           initialize comando.
           accept comando from environment "BAT_PROCESSI".
           call "C$SYSTEM"   using comando, 32
                            giving link-status.
           move "task.txt" to wstampa.
           call "C$SLEEP" using 2.
           perform until 1 = 2
              open input lineseq
              if status-lineseq = "00"
                 exit perform
              end-if
           end-perform.
           set trovato to false.
           move 0 to sessioni.
           perform until 1 = 2
              read lineseq next at end exit perform end-read
              if line-riga(1:10) = "wrun32.exe"
                 add 1 to sessioni
                 |Una volta è quella in esecuzione
                 if sessioni > 1
                    display message "Studio già in esecuzione!"
                              title titolo
                               icon 2
                    set trovato to true
                    exit perform
                 end-if
              end-if
           end-perform.
           close       lineseq.
           delete file lineseq.

           if trovato
              goback
           end-if.

           call   "genfiles" using link-status
           cancel "genfiles".

           if link-status = -1
              goback
           end-if.
           
           call   "colors".
           cancel "colors" 
           .
      * <TOTEM:END>
       pb-iva-LinkTo.
      * <TOTEM:PARA. pb-iva-LinkTo>
           move "tcodiva" to NomeProgramma.
           perform CALL-PROGRAM 
           .
      * <TOTEM:END>
       pb-catcli-LinkTo.
      * <TOTEM:PARA. pb-catcli-LinkTo>
           move "ttipocli" to NomeProgramma.
           perform CALL-PROGRAM 
           .
      * <TOTEM:END>
       pb-clienti-LinkTo.
      * <TOTEM:PARA. pb-clienti-LinkTo>
           move "gclienti" to NomeProgramma.
           perform CALL-PROGRAM 
           .
      * <TOTEM:END>
       pb-articoli-LinkTo.
      * <TOTEM:PARA. pb-articoli-LinkTo>
           move "garticoli" to NomeProgramma.
           perform CALL-PROGRAM 
           .
      * <TOTEM:END>
       pb-listini-LinkTo.
      * <TOTEM:PARA. pb-listini-LinkTo>
           move "glistini" to NomeProgramma.
           perform CALL-PROGRAM 
           .
      * <TOTEM:END>
       pb-schede-LinkTo.
      * <TOTEM:PARA. pb-schede-LinkTo>
           move "schedacli" to NomeProgramma.
           perform CALL-PROGRAM 
           .
      * <TOTEM:END>
       pb-fatture-LinkTo.
      * <TOTEM:PARA. pb-fatture-LinkTo>
           move "fatcli" to NomeProgramma.
           perform CALL-PROGRAM 
           .
      * <TOTEM:END>
       pb-report-LinkTo.
      * <TOTEM:PARA. pb-report-LinkTo>
           move "docum" to NomeProgramma.
           perform CALL-PROGRAM 
           .
      * <TOTEM:END>
       pb-note-LinkTo.
      * <TOTEM:PARA. pb-note-LinkTo>
           move "selnota" to NomeProgramma.
           perform CALL-PROGRAM 
           .
      * <TOTEM:END>
       pb-appuntamenti-LinkTo.
      * <TOTEM:PARA. pb-appuntamenti-LinkTo>
           move "appuntamenti" to NomeProgramma.
           perform CALL-PROGRAM 
           .
      * <TOTEM:END>

      *{TOTEM}END

      *{TOTEM}SHOW-MSG
       MESSAGE-FOR-FILEERROR.
           CALL "C$RERRNAME" USING TOTEM-MSG-ERR-FILE
           CALL "C$RERR" USING EXTEND-STAT, TEXT-MESSAGE
              MOVE PRIMARY-ERROR TO TOTEM-MSG-ID
           .

       SHOW-TRANSACTION-ROUTINE.
           IF TOTEM-TRANSACTION-FLAG = SPACES
              IF TRANSACTION-STATUS NOT = 0
                 STRING "TRANSACTION ERROR ", TRANSACTION-STATUS
                    DELIMITED BY SIZE INTO TOTEM-MSG-1
              END-IF
           ELSE
              PERFORM SHOW-MSG-ROUTINE
              IF TRANSACTION-STATUS = 0
                 MOVE "Transazione terminata con Rollback." TO 
           TOTEM-MSG-3
              ELSE
                 STRING "TRANSACTION ERROR ", TRANSACTION-STATUS
                    DELIMITED BY SIZE INTO TOTEM-MSG-3
              END-IF
           END-IF
           .

       SHOW-MSG-ROUTINE.
           MOVE SPACE TO TOTEM-MSG-1 TOTEM-MSG-2 TOTEM-MSG-3
           EVALUATE TOTEM-MSG-ID
               WHEN "10"
                    STRING "File:" TOTEM-MSG-ERR-FILE DELIMITED BY SPACE
                       INTO TOTEM-MSG-1
                    MOVE "Nessun altro dato." TO TOTEM-MSG-2
                    MOVE MB-DEFAULT-ICON TO TOTEM-MSG-ICON-TYPE
                    MOVE MB-OK TO TOTEM-MSG-BUTTON-TYPE
               WHEN "22"
                    STRING "File:" TOTEM-MSG-ERR-FILE DELIMITED BY SPACE
                       INTO TOTEM-MSG-1
                    MOVE "Chiave Duplicata." TO TOTEM-MSG-2
                    MOVE MB-ERROR-ICON TO TOTEM-MSG-ICON-TYPE
                    MOVE MB-OK TO TOTEM-MSG-BUTTON-TYPE
               WHEN "23"
                    STRING "File:" TOTEM-MSG-ERR-FILE DELIMITED BY SPACE
                       INTO TOTEM-MSG-1
                    MOVE "Raggiunta fine file." TO TOTEM-MSG-2
                    MOVE MB-WARNING-ICON TO TOTEM-MSG-ICON-TYPE
                    MOVE MB-OK TO TOTEM-MSG-BUTTON-TYPE
               WHEN "101"
                    MOVE "Terminare l'applicazione?" TO TOTEM-MSG-1
                    MOVE 4 TO TOTEM-MSG-ICON-TYPE
                    MOVE MB-YES-NO TO TOTEM-MSG-BUTTON-TYPE
               WHEN "201"
                    MOVE "Aggiungere un nuovo record?" TO TOTEM-MSG-1
                    MOVE 4 TO TOTEM-MSG-ICON-TYPE
                    MOVE MB-YES-NO TO TOTEM-MSG-BUTTON-TYPE
               WHEN "202"
                    MOVE "Aggiornare il Record?" TO TOTEM-MSG-1
                    MOVE 4 TO TOTEM-MSG-ICON-TYPE
                    MOVE MB-YES-NO TO TOTEM-MSG-BUTTON-TYPE
               WHEN "203"
                    MOVE "Cancellare il Record?" TO TOTEM-MSG-1
                    MOVE 4 TO TOTEM-MSG-ICON-TYPE
                    MOVE MB-YES-NO TO TOTEM-MSG-BUTTON-TYPE
               WHEN "204"
                    MOVE "Chiave duplicata." TO TOTEM-MSG-1
                    MOVE MB-WARNING-ICON TO TOTEM-MSG-ICON-TYPE
                    MOVE MB-OK TO TOTEM-MSG-BUTTON-TYPE
               WHEN "301"
                    MOVE "Inserimento avvenuto con Successo." TO 
           TOTEM-MSG-1
                    MOVE MB-DEFAULT-ICON TO TOTEM-MSG-ICON-TYPE
                    MOVE MB-OK TO TOTEM-MSG-BUTTON-TYPE
               WHEN "302"
                    MOVE "Aggiornamento avvenuto con Successo." TO 
           TOTEM-MSG-1
                    MOVE MB-DEFAULT-ICON TO TOTEM-MSG-ICON-TYPE
                    MOVE MB-OK TO TOTEM-MSG-BUTTON-TYPE
               WHEN "303"
                    MOVE "Cancellazione avvenuta con Successo." TO 
           TOTEM-MSG-1
                    MOVE MB-DEFAULT-ICON TO TOTEM-MSG-ICON-TYPE
                    MOVE MB-OK TO TOTEM-MSG-BUTTON-TYPE
               WHEN "401"
                    MOVE "Shell non trovata." TO TOTEM-MSG-1
                    MOVE MB-ERROR-ICON TO TOTEM-MSG-ICON-TYPE
                    MOVE MB-OK TO TOTEM-MSG-BUTTON-TYPE
               WHEN OTHER
                    MOVE TEXT-MESSAGE TO TOTEM-MSG-1
                    STRING "FILE:" TOTEM-MSG-ERR-FILE DELIMITED BY SPACE
                       INTO TOTEM-MSG-3
                    MOVE 0 TO TOTEM-IDX1
                    INSPECT TOTEM-MSG-3 TALLYING TOTEM-IDX1
                       FOR TRAILING SPACE
                    STRING TOTEM-MSG-3(1:TOTEM-MSG-LENGTH - 
           TOTEM-IDX1), 
                       ", FILE STATUS ", PRIMARY-ERROR "," 
                       SECONDARY-ERROR
                    DELIMITED BY SIZE INTO TOTEM-MSG-2
                    MOVE SPACES TO TOTEM-MSG-3
                    MOVE MB-ERROR-ICON TO TOTEM-MSG-ICON-TYPE
                    MOVE MB-OK TO TOTEM-MSG-BUTTON-TYPE
           END-EVALUATE
           PERFORM MESSAGE-BOX-ROUTINE
           .

       MESSAGE-BOX-ROUTINE.
           MOVE 1 TO TOTEM-MSG-TEXT-POINTER
           IF TOTEM-MSG-1 NOT = SPACE
              MOVE 0 TO TOTEM-MSG-SIZE
              INSPECT TOTEM-MSG-1 TALLYING TOTEM-MSG-SIZE FOR TRAILING 
           SPACE
              STRING TOTEM-MSG-1( 1 : TOTEM-MSG-LENGTH - TOTEM-MSG-SIZE 
           )
                 DELIMITED BY SIZE
                 INTO TOTEM-MSG-TEXT, POINTER TOTEM-MSG-TEXT-POINTER
           END-IF

           IF TOTEM-MSG-2 NOT = SPACE
              MOVE 0 TO TOTEM-MSG-SIZE
              INSPECT TOTEM-MSG-2 TALLYING TOTEM-MSG-SIZE FOR TRAILING 
           SPACE
              IF TOTEM-MSG-TEXT-POINTER > 1
                 STRING X"0A" DELIMITED BY SIZE
                     INTO TOTEM-MSG-TEXT, POINTER TOTEM-MSG-TEXT-POINTER
              END-IF
              STRING TOTEM-MSG-2( 1 : TOTEM-MSG-LENGTH - TOTEM-MSG-SIZE 
           )
                  DELIMITED BY SIZE
                  INTO TOTEM-MSG-TEXT, POINTER TOTEM-MSG-TEXT-POINTER
           END-IF

           IF TOTEM-MSG-3 NOT = SPACE
              MOVE 0 TO TOTEM-MSG-SIZE
              INSPECT TOTEM-MSG-3 TALLYING TOTEM-MSG-SIZE FOR TRAILING 
           SPACE
              IF TOTEM-MSG-TEXT-POINTER > 1
                 STRING X"0A" DELIMITED BY SIZE
                     INTO TOTEM-MSG-TEXT, POINTER TOTEM-MSG-TEXT-POINTER
              END-IF
              STRING TOTEM-MSG-3( 1 : TOTEM-MSG-LENGTH - TOTEM-MSG-SIZE 
           )
                  DELIMITED BY SIZE
                  INTO TOTEM-MSG-TEXT, POINTER TOTEM-MSG-TEXT-POINTER
           END-IF

           IF TOTEM-MSG-TEXT-POINTER = 1
              MOVE 0 TO TOTEM-MSG-SIZE
              INSPECT TOTEM-MSG-TEXT TALLYING TOTEM-MSG-SIZE FOR 
           TRAILING SPACE
                  COMPUTE TOTEM-MSG-TEXT-POINTER = 
           TOTEM-MSG-FULL-LENGTH - TOTEM-MSG-SIZE + 1
           END-IF
           MOVE LOW-VALUES TO TOTEM-MSG-TEXT(TOTEM-MSG-TEXT-POINTER : 1 
           )
           .

       MESSAGE-BOX-DISPLAY.
           PERFORM SHOW-MSG-ROUTINE
           PERFORM MESSAGE-BOX-ROUTINE
           DISPLAY MESSAGE BOX TOTEM-MSG-TEXT
               TITLE IS TOTEM-MSG-TITLE
               TYPE  IS TOTEM-MSG-BUTTON-TYPE
               ICON  IS TOTEM-MSG-DEFAULT-BUTTON
               RETURNING TOTEM-MSG-RETURN-VALUE
           .

      *{TOTEM}END

