      *{TOTEM}PRG-COMMENT
      * selnota.Cbl
      * selnota.Cbl is generated by TOTEM
      * This is a generated file. DO NOT modify this file directly.
      *{TOTEM}END
       IDENTIFICATION       DIVISION.
      *{TOTEM}PRGID
       PROGRAM-ID.          selnota.
       AUTHOR.              Andrea.
       DATE-WRITTEN.        martedì 5 giugno 2012 02:21:41.
       REMARKS.
      *{TOTEM}END

       ENVIRONMENT          DIVISION.
       CONFIGURATION        SECTION.
       SPECIAL-NAMES.
      *{TOTEM}SPECIAL-NAME
      * <TOTEM:EPT. INIT:selnota, INIT:selnota, SpecialName>
      * <TOTEM:END>
      *{TOTEM}END
      *{TOTEM}ACTIVEX-DEF
      *{TOTEM}END
      *{TOTEM}DECIMAL-POINT
           DECIMAL-POINT IS COMMA.
      *{TOTEM}END

       INPUT-OUTPUT         SECTION.
       FILE-CONTROL.
      *{TOTEM}FILE-CONTROL
           COPY "tfatture.sl".
           COPY "tcorrisp.sl".
      *{TOTEM}END
       DATA                 DIVISION.
       FILE                 SECTION.
      *{TOTEM}FILE
           COPY "tfatture.fd".
           COPY "tcorrisp.fd".
      *{TOTEM}END

       WORKING-STORAGE      SECTION.
      *{TOTEM}ACU-DEF
               COPY "acugui.def".
               COPY "acucobol.def".
               COPY "fonts.def".
               COPY "crtvars.def".
               COPY "showmsg.def".
               COPY "totem.def".
               COPY "comune.def".
               COPY "custom.def".
               COPY "UTYDATA.DEF".
      *{TOTEM}END

      *{TOTEM}COPY-WORKING
      * Key Status
       77 Key-Status IS SPECIAL-NAMES CRT STATUS PIC 9(5) VALUE 0.
          88 Enter-Pushed VALUE 13.
          88 Exit-Pushed VALUE 27.
          88 Message-Received VALUE 95.
          88 Event-Occurred VALUE 96.
          88 Screen-No-Input-Field VALUE 97.
          88 Screen-Time-Out VALUE 99.
      * Properties & User defined Working Stoarge
       78 titolo VALUE IS "Studio - Note Credito". 
       77 Form1-Tb-1-Handle
                  USAGE IS HANDLE OF WINDOW.
           COPY  "LINK-VDOCUM.DEF".
       77 toolbar-bmp      PIC  S9(9)
                  USAGE IS COMP-4
                  VALUE IS 0.
       77 Small-Font
                  USAGE IS HANDLE OF FONT SMALL-FONT.
       77 Form1-St-1-Handle
                  USAGE IS HANDLE OF STATUS-BAR.
       77 form1-Handle
                  USAGE IS HANDLE OF WINDOW.
       77 AUTO-ID          PIC  9(6)
                  VALUE IS 0,00.
       77 Calibri14-Occidentale
                  USAGE IS HANDLE OF FONT.
       77 Calibri14B-Occidentale
                  USAGE IS HANDLE OF FONT.
       77 Calibri16B-Occidentale
                  USAGE IS HANDLE OF FONT.
       77 LOGO-PICCOLO-BMP PIC  S9(9)
                  USAGE IS COMP-4
                  VALUE IS 0.
       77 Calibri18B-Occidentale
                  USAGE IS HANDLE OF FONT.
       77 FontSelezionato
                  USAGE IS HANDLE OF FONT.
       77 Default-Font
                  USAGE IS HANDLE OF FONT DEFAULT-FONT.
       77 STATUS-tfatture  PIC  X(2).
           88 Valid-STATUS-tfatture VALUE IS "00" THRU "09". 
       77 STATUS-tcorrisp  PIC  X(2).
           88 Valid-STATUS-tcorrisp VALUE IS "00" THRU "09". 
       77 ef-anno-buf      PIC  9999.
       77 ef-numero-buf    PIC  9(6).
       77 STRIP-DOCUM-BMP  PIC  S9(9)
                  USAGE IS COMP-4
                  VALUE IS 0.
       77 tipo-doc         PIC  S9(1)
                  VALUE IS 1.
       77 SINGOLA-BMP      PIC  S9(9)
                  USAGE IS COMP-4
                  VALUE IS 0.
       77 FATCLI-BMP       PIC  S9(9)
                  USAGE IS COMP-4
                  VALUE IS 0.

      ***********************************************************
      *   Code Gen's Buffer                                     *
      ***********************************************************
       77 STATUS-form1-FLAG-REFRESH PIC  9.
          88 form1-FLAG-REFRESH  VALUE 1 FALSE 0. 
       77 TMP-DataSet1-tfatture-BUF     PIC X(922).
       77 TMP-DataSet1-tcorrisp-BUF     PIC X(922).
      * VARIABLES FOR RECORD LENGTH.
       77  TotemFdSlRecordClearOffset   PIC 9(5) COMP-4.
       77  TotemFdSlRecordLength        PIC 9(5) COMP-4.
      * FILE'S LOCK MODE FLAG
       77 DataSet1-tfatture-LOCK-FLAG   PIC X VALUE SPACE.
           88 DataSet1-tfatture-LOCK  VALUE "Y".
       77 DataSet1-KEYIS   PIC 9(3) VALUE 1.
       77 DataSet1-tfatture-KEY1-ORDER  PIC X VALUE "A".
          88 DataSet1-tfatture-KEY1-Asc  VALUE "A".
          88 DataSet1-tfatture-KEY1-Desc VALUE "D".
       77 DataSet1-tcorrisp-LOCK-FLAG   PIC X VALUE SPACE.
           88 DataSet1-tcorrisp-LOCK  VALUE "Y".
       77 DataSet1-tcorrisp-KEY-ORDER  PIC X VALUE "A".
          88 DataSet1-tcorrisp-KEY-Asc  VALUE "A".
          88 DataSet1-tcorrisp-KEY-Desc VALUE "D".

       77 tfatture-tfa-k-data-SPLITBUF  PIC X(19).
       77 tfatture-tfa-k-cliente-SPLITBUF  PIC X(21).
       77 tcorrisp-tco-k-data-SPLITBUF  PIC X(19).
       77 tcorrisp-tco-k-cliente-SPLITBUF  PIC X(21).

      *{TOTEM}END

      *{TOTEM}ID-LOGICI
      ***** Elenco ID Logici *****
       78  78-ID-ef-anno VALUE 5001.
       78  78-ID-ef-numero VALUE 5002.
      ***** Fine ID Logici *****
      *{TOTEM}END

       LINKAGE          SECTION.
      *{TOTEM}LINKAGE
           COPY  "BLOCKPGM.LKS".
      *{TOTEM}END

       SCREEN           SECTION.
      *{TOTEM}COPY-SCREEN
      * FORM
       01 
           form1, 
           .

      * PUSH BUTTON
       05
           pb-procedi, 
           Push-Button, 
           COL 13,60, 
           LINE 17,13,
           LINES 114,00 ,
           SIZE 96,00 ,
           BITMAP-HANDLE FATCLI-BMP,
           BITMAP-NUMBER 1,
           FRAMED,
           SQUARE,
           EXCEPTION-VALUE 13,
           ID IS 101,
           .

      * PUSH BUTTON
       05
           pb-procedia, 
           Push-Button, 
           COL 26,30, 
           LINE 17,13,
           LINES 114,00 ,
           SIZE 96,00 ,
           BITMAP-HANDLE FATCLI-BMP,
           BITMAP-NUMBER 2,
           FRAMED,
           SQUARE,
           EXCEPTION-VALUE 27,
           ID IS 102,
           SELF-ACT,
           .

      * BITMAP
       05
           Form1-Bt-1a, 
           Bitmap, 
           COL 44,50, 
           LINE 20,35,
           LINES 64,00 ,
           SIZE 48,00 ,
           BITMAP-HANDLE LOGO_PICCOLO-BMP,
           BITMAP-NUMBER 1,
           ID IS 123,
           .

      * LABEL
       05
           form-clien-blockpgm-1, 
           Label, 
           COL 1,00, 
           LINE 1,00,
           LINES 0,70 ,
           SIZE 2,90 ,
           ID IS 10,
           HEIGHT-IN-CELLS,
           WIDTH-IN-CELLS,
           TRANSPARENT,
           TITLE "BlockPgm",
           VISIBLE v-custom,
           .

      * LABEL
       05
           form-clien-Custom1-1, 
           Label, 
           COL 10,00, 
           LINE 1,00,
           LINES 1,00 ,
           SIZE 1,00 ,
           FONT IS Default-Font,
           ID IS 12,
           TRANSPARENT,
           TITLE "CUSTOM CONTROL",
           VISIBLE v-custom,
           .

      * FRAME
       05
           form-clien-Fr-1, 
           Frame, 
           COL 2,50, 
           LINE 1,70,
           LINES 14,61 ,
           SIZE 45,20 ,
           COLOR IS 11,
           FONT IS Calibri14B-Occidentale,
           ID IS 5,
           HEIGHT-IN-CELLS,
           WIDTH-IN-CELLS,
           HEAVY,
           TITLE "Selezione Documento di base",
           TITLE-POSITION 2,
           .

      * ENTRY FIELD
       05
           ef-anno, 
           Entry-Field, 
           COL 12,50, 
           LINE 11,00,
           LINES 1,30 ,
           SIZE 9,00 ,
           BOXED,
           COLOR IS 513,
           ID IS 78-ID-ef-anno,                
           HEIGHT-IN-CELLS,
           WIDTH-IN-CELLS,
           RIGHT,
           MAX-TEXT 4,
           VALUE ef-anno-buf,
           AFTER PROCEDURE ef-anno-s-AfterProcedure, 
           BEFORE PROCEDURE ef-anno-s-BeforeProcedure, 
           .

      * ENTRY FIELD
       05
           ef-numero, 
           Entry-Field, 
           COL 33,70, 
           LINE 11,00,
           LINES 1,30 ,
           SIZE 11,00 ,
           BOXED,
           COLOR IS 513,
           ID IS 78-ID-ef-numero,                
           HEIGHT-IN-CELLS,
           WIDTH-IN-CELLS,
           RIGHT,
           MAX-TEXT 6,
           VALUE ef-numero-buf,
           AFTER PROCEDURE ef-numero-s-AfterProcedure, 
           BEFORE PROCEDURE ef-numero-s-BeforeProcedure, 
           .

      * RADIO BUTTON
       05
           rb-fatture, 
           Radio-Button, 
           COL 9,30, 
           LINE 3,66,
           LINES 128,00 ,
           SIZE 128,00 ,
           BITMAP-HANDLE STRIP-DOCUM-BMP,
           BITMAP-NUMBER 6,
           FRAMED,
           SQUARE,
           EXCEPTION-VALUE 1000
           GROUP 1,
           GROUP-VALUE 1,
           ID IS 127,
           NO-TAB,
           SELF-ACT,
           VALUE tipo-doc,
           AFTER PROCEDURE Screen1-Rb-1-AfterProcedure, 
           BEFORE PROCEDURE Screen1-Rb-1-BeforeProcedure, 
           .
      * RADIO BUTTON
       05
           rb-corrisp, 
           Radio-Button, 
           COL 27,30, 
           LINE 3,74,
           LINES 128,00 ,
           SIZE 128,00 ,
           BITMAP-HANDLE STRIP-DOCUM-BMP,
           BITMAP-NUMBER 1,
           FRAMED,
           SQUARE,
           EXCEPTION-VALUE 1001
           GROUP 1,
           GROUP-VALUE 2,
           ID IS 128,
           NO-TAB,
           SELF-ACT,
           VALUE tipo-doc,
           AFTER PROCEDURE Screen1-Rb-1-AfterProcedure, 
           BEFORE PROCEDURE Screen1-Rb-1-BeforeProcedure, 
           .
      * LABEL
       05
           lab-clientebaaa, 
           Label, 
           COL 5,50, 
           LINE 11,00,
           LINES 1,30 ,
           SIZE 6,00 ,
           COLOR IS 9,
           FONT IS Calibri16B-Occidentale,
           ID IS 129,
           HEIGHT-IN-CELLS,
           WIDTH-IN-CELLS,
           TRANSPARENT,
           TITLE "Anno",
           .

      * LABEL
       05
           lab-clientebaaaa, 
           Label, 
           COL 24,50, 
           LINE 11,00,
           LINES 1,30 ,
           SIZE 9,00 ,
           COLOR IS 9,
           FONT IS Calibri16B-Occidentale,
           ID IS 13,
           HEIGHT-IN-CELLS,
           WIDTH-IN-CELLS,
           TRANSPARENT,
           TITLE "Numero",
           .

      * PUSH BUTTON
       05
           pb-singola, 
           Push-Button, 
           COL 18,30, 
           LINE 13,18,
           LINES 50,00 ,
           SIZE 128,00 ,
           BITMAP-HANDLE SINGOLA-BMP,
           BITMAP-NUMBER 1,
           FRAMED,
           SQUARE,
           EXCEPTION-VALUE 465,
           ID IS 1,
           NO-TAB,
           SELF-ACT,
           .

      *{TOTEM}END

      *{TOTEM}LINKPARA
       PROCEDURE  DIVISION USING LK-BLOCKPGM.
      *{TOTEM}END

      *{TOTEM}DECLARATIVE
       DECLARATIVES.
      * <TOTEM:EPT. INIT:selnota, INIT:selnota, BeforeDeclarative>
      * <TOTEM:END>
       INPUT-ERROR SECTION.
           USE AFTER STANDARD ERROR PROCEDURE ON INPUT.
       0100-DECL.
           EXIT.
       I-O-ERROR SECTION.
           USE AFTER STANDARD ERROR PROCEDURE ON I-O.
       0200-DECL.
           EXIT.
       OUTPUT-ERROR SECTION.
           USE AFTER STANDARD ERROR PROCEDURE ON OUTPUT.
       0300-DECL.
           EXIT.
       TRANSACTION-ERROR SECTION.
           USE AFTER STANDARD ERROR PROCEDURE ON TRANSACTION.
       0400-DECL.
           EXIT.
       END DECLARATIVES.
      *{TOTEM}END

       MAIN-LOGIC.
      *{TOTEM}ENTRY-BEFPRG
      *    Before-Program
           PERFORM ginqui-Ev-Before-Program
      *{TOTEM}END
           PERFORM INITIALIZE-ROUTINE.
      * run main screen
      *{TOTEM}RUN-MAINSCR
           PERFORM form1-OPEN-ROUTINE.
      *{TOTEM}END

      *{TOTEM}COPY-PROCEDURE
       EXIT-STOP-ROUTINE.
           PERFORM CLOSE-FILE-RTN
      * <TOTEM:EPT. INIT:selnota, INIT:selnota, BeforeDestroyResource>
      * <TOTEM:END>
           DESTROY Calibri14B-Occidentale
           DESTROY Calibri16B-Occidentale
           DESTROY Calibri14-Occidentale
           CALL "w$bitmap" USING WBITMAP-DESTROY, FATCLI-BMP
           CALL "w$bitmap" USING WBITMAP-DESTROY, LOGO_PICCOLO-BMP
           CALL "w$bitmap" USING WBITMAP-DESTROY, STRIP-DOCUM-BMP
           CALL "w$bitmap" USING WBITMAP-DESTROY, SINGOLA-BMP
      *    After-Program
           PERFORM ginqui-Ev-After-Program
           EXIT PROGRAM TOTEM-PgmStatus
           STOP RUN.

       INITIALIZE-ROUTINE.
      *    Before Init
      * initialize program status variable
           Initialize TOTEM-PgmStatus.
      * get system information
           ACCEPT SYSTEM-INFORMATION FROM SYSTEM-INFO.
      * get terminal information
           ACCEPT TERMINAL-ABILITIES FROM TERMINAL-INFO.
      * set font
           PERFORM INIT-FONT.
      * load bitmap
           PERFORM INIT-BMP.
      * load resource
           PERFORM INIT-RES.
      * create pop-up menu
           PERFORM INIT-POPUP.
      * open files
           PERFORM OPEN-FILE-RTN.
      *    After Init
           .
    
       INIT-FONT.
      * Calibri14B-Occidentale
           INITIALIZE WFONT-DATA Calibri14B-Occidentale
           MOVE 14 TO WFONT-SIZE
           MOVE "Calibri" TO WFONT-NAME
           SET WFCHARSET-DONT-CARE TO TRUE
           SET WFONT-BOLD TO TRUE
           SET WFONT-ITALIC TO FALSE
           SET WFONT-UNDERLINE TO FALSE
           SET WFONT-STRIKEOUT TO FALSE
           SET WFONT-FIXED-PITCH TO FALSE
           MOVE 0 TO WFONT-CHAR-SET
           CALL "W$FONT" USING WFONT-GET-FONT, 
                     Calibri14B-Occidentale, WFONT-DATA
      * Calibri16B-Occidentale
           INITIALIZE WFONT-DATA Calibri16B-Occidentale
           MOVE 16 TO WFONT-SIZE
           MOVE "Calibri" TO WFONT-NAME
           SET WFCHARSET-DONT-CARE TO TRUE
           SET WFONT-BOLD TO TRUE
           SET WFONT-ITALIC TO FALSE
           SET WFONT-UNDERLINE TO FALSE
           SET WFONT-STRIKEOUT TO FALSE
           SET WFONT-FIXED-PITCH TO FALSE
           MOVE 0 TO WFONT-CHAR-SET
           CALL "W$FONT" USING WFONT-GET-FONT, 
                     Calibri16B-Occidentale, WFONT-DATA
      * Calibri14-Occidentale
           INITIALIZE WFONT-DATA Calibri14-Occidentale
           MOVE 14 TO WFONT-SIZE
           MOVE "Calibri" TO WFONT-NAME
           SET WFCHARSET-DONT-CARE TO TRUE
           SET WFONT-BOLD TO FALSE
           SET WFONT-ITALIC TO FALSE
           SET WFONT-UNDERLINE TO FALSE
           SET WFONT-STRIKEOUT TO FALSE
           SET WFONT-FIXED-PITCH TO FALSE
           MOVE 0 TO WFONT-CHAR-SET
           CALL "W$FONT" USING WFONT-GET-FONT, 
                     Calibri14-Occidentale, WFONT-DATA
           .

       INIT-BMP.
      * pb-procedi
           COPY RESOURCE "FATCLI.BMP".
           CALL "w$bitmap" USING WBITMAP-LOAD "FATCLI.BMP", 
                   GIVING FATCLI-BMP.
      * Form1-Bt-1a
           COPY RESOURCE "LOGO_PICCOLO.BMP".
           CALL "w$bitmap" USING WBITMAP-LOAD "LOGO_PICCOLO.BMP", 
                   GIVING LOGO_PICCOLO-BMP.
      * rb-fatture
           COPY RESOURCE "STRIP-DOCUM.BMP".
           CALL "w$bitmap" USING WBITMAP-LOAD "STRIP-DOCUM.BMP", 
                   GIVING STRIP-DOCUM-BMP.
      * pb-singola
           COPY RESOURCE "SINGOLA.BMP".
           CALL "w$bitmap" USING WBITMAP-LOAD "SINGOLA.BMP", 
                   GIVING SINGOLA-BMP.
           .

       INIT-RES.
           .

       INIT-POPUP.
           .

       OPEN-FILE-RTN.
      *    Before Open
           PERFORM OPEN-tfatture
           PERFORM OPEN-tcorrisp
      *    After Open
           .

       OPEN-tfatture.
      * <TOTEM:EPT. INIT:selnota, FD:tfatture, BeforeOpen>
      * <TOTEM:END>
           OPEN  INPUT tfatture
           IF NOT Valid-STATUS-tfatture
              PERFORM  form1-EXTENDED-FILE-STATUS
              GO TO EXIT-STOP-ROUTINE
           END-IF
      * <TOTEM:EPT. INIT:selnota, FD:tfatture, AfterOpen>
      * <TOTEM:END>
           .

       OPEN-tcorrisp.
      * <TOTEM:EPT. INIT:selnota, FD:tcorrisp, BeforeOpen>
      * <TOTEM:END>
           OPEN  INPUT tcorrisp
           IF NOT Valid-STATUS-tcorrisp
              PERFORM  form1-EXTENDED-FILE-STATUS
              GO TO EXIT-STOP-ROUTINE
           END-IF
      * <TOTEM:EPT. INIT:selnota, FD:tcorrisp, AfterOpen>
      * <TOTEM:END>
           .

       CLOSE-FILE-RTN.
      *    Before Close
           PERFORM CLOSE-tfatture
           PERFORM CLOSE-tcorrisp
      *    After Close
           .

       CLOSE-tfatture.
      * <TOTEM:EPT. INIT:selnota, FD:tfatture, BeforeClose>
      * <TOTEM:END>
           CLOSE tfatture
           .

       CLOSE-tcorrisp.
      * <TOTEM:EPT. INIT:selnota, FD:tcorrisp, BeforeClose>
      * <TOTEM:END>
           CLOSE tcorrisp
           .

       tfatture-tfa-k-data-MERGE-SPLITBUF.
           INITIALIZE tfatture-tfa-k-data-SPLITBUF
           MOVE tfa-data-doc(1:8) TO tfatture-tfa-k-data-SPLITBUF(1:8)
           MOVE tfa-chiave(1:10) TO tfatture-tfa-k-data-SPLITBUF(9:10)
           .

       tfatture-tfa-k-cliente-MERGE-SPLITBUF.
           INITIALIZE tfatture-tfa-k-cliente-SPLITBUF
           MOVE tfa-cliente(1:6) TO tfatture-tfa-k-cliente-SPLITBUF(1:6)
           MOVE tfa-data-doc(1:8) TO 
           tfatture-tfa-k-cliente-SPLITBUF(7:8)
           MOVE tfa-numero(1:6) TO tfatture-tfa-k-cliente-SPLITBUF(15:6)
           .

       DataSet1-tfatture-INITSTART.
           EVALUATE DataSet1-KEYIS
           WHEN 1
              IF DataSet1-tfatture-KEY1-Asc
                 MOVE Low-Value TO tfa-chiave
              ELSE
                 MOVE High-Value TO tfa-chiave
              END-IF
           END-EVALUATE
           .

       DataSet1-tfatture-INITEND.
           EVALUATE DataSet1-KEYIS
           WHEN 1
              IF DataSet1-tfatture-KEY1-Asc
                 MOVE High-Value TO tfa-chiave
              ELSE
                 MOVE Low-Value TO tfa-chiave
              END-IF
           END-EVALUATE
           .

       DataSet1-CHANGETO-KEY1.
           MOVE 1 TO DataSet1-KEYIS
           .   

       DataSet1-Change-CurrentKey-Asc.
           EVALUATE DataSet1-KEYIS
           WHEN 1
              MOVE "A" TO DataSet1-tfatture-KEY1-ORDER
           END-EVALUATE
           .

       DataSet1-Change-CurrentKey-Desc.
           EVALUATE DataSet1-KEYIS
           WHEN 1
              MOVE "D" TO DataSet1-tfatture-KEY1-ORDER
           END-EVALUATE
           .

      * tfatture
       DataSet1-tfatture-START.
           EVALUATE DataSet1-KEYIS
           WHEN 1
              IF DataSet1-tfatture-KEY1-Asc
                 START tfatture KEY >= tfa-chiave
              ELSE
                 START tfatture KEY <= tfa-chiave
              END-IF
           END-EVALUATE
           .

       DataSet1-tfatture-START-NOTGREATER.
           EVALUATE DataSet1-KEYIS
           WHEN 1
              IF DataSet1-tfatture-KEY1-Asc
                 START tfatture KEY <= tfa-chiave
              ELSE
                 START tfatture KEY >= tfa-chiave
              END-IF
           END-EVALUATE
           .

       DataSet1-tfatture-START-GREATER.
           EVALUATE DataSet1-KEYIS
           WHEN 1
              IF DataSet1-tfatture-KEY1-Asc
                 START tfatture KEY > tfa-chiave
              ELSE
                 START tfatture KEY < tfa-chiave
              END-IF
           END-EVALUATE
           .

       DataSet1-tfatture-START-LESS.
           EVALUATE DataSet1-KEYIS
           WHEN 1
              IF DataSet1-tfatture-KEY1-Asc
                 START tfatture KEY < tfa-chiave
              ELSE
                 START tfatture KEY > tfa-chiave
              END-IF
           END-EVALUATE
           .

       DataSet1-tfatture-Read.
      * <TOTEM:EPT. FD:DataSet1, FD:tfatture, BeforeRead>
      * <TOTEM:END>
      * <TOTEM:EPT. FD:DataSet1, FD:tfatture, BeforeReadRecord>
      * <TOTEM:END>
           EVALUATE DataSet1-KEYIS
           WHEN 1
              IF DataSet1-tfatture-LOCK
                 READ tfatture WITH LOCK 
                 KEY tfa-chiave
              ELSE
                 READ tfatture WITH NO LOCK 
                 KEY tfa-chiave
              END-IF
           END-EVALUATE
           PERFORM tfatture-tfa-k-data-MERGE-SPLITBUF
           PERFORM tfatture-tfa-k-cliente-MERGE-SPLITBUF
           MOVE STATUS-tfatture TO TOTEM-ERR-STAT 
           MOVE "tfatture" TO TOTEM-ERR-FILE
           MOVE "READ" TO TOTEM-ERR-MODE
      * <TOTEM:EPT. FD:DataSet1, FD:tfatture, AfterRead>
      * <TOTEM:END>
      * <TOTEM:EPT. FD:DataSet1, FD:tfatture, AfterReadRecord>
      * <TOTEM:END>
           .

       DataSet1-tfatture-Read-Next.
      * <TOTEM:EPT. FD:DataSet1, FD:tfatture, BeforeRead>
      * <TOTEM:END>
      * <TOTEM:EPT. FD:DataSet1, FD:tfatture, BeforeReadNext>
      * <TOTEM:END>
           EVALUATE DataSet1-KEYIS
           WHEN 1
              IF DataSet1-tfatture-KEY1-Asc
                 IF DataSet1-tfatture-LOCK
                    READ tfatture NEXT WITH LOCK
                 ELSE
                    READ tfatture NEXT WITH NO LOCK
                 END-IF
              ELSE
                 IF DataSet1-tfatture-LOCK
                    READ tfatture PREVIOUS WITH LOCK
                 ELSE
                    READ tfatture PREVIOUS WITH NO LOCK
                 END-IF
              END-IF
           END-EVALUATE
           PERFORM tfatture-tfa-k-data-MERGE-SPLITBUF
           PERFORM tfatture-tfa-k-cliente-MERGE-SPLITBUF
           MOVE STATUS-tfatture TO TOTEM-ERR-STAT
           MOVE "tfatture" TO TOTEM-ERR-FILE
           MOVE "READ NEXT" TO TOTEM-ERR-MODE
      * <TOTEM:EPT. FD:DataSet1, FD:tfatture, AfterRead>
      * <TOTEM:END>
      * <TOTEM:EPT. FD:DataSet1, FD:tfatture, AfterReadNext>
      * <TOTEM:END>
           .

       DataSet1-tfatture-Read-Prev.
      * <TOTEM:EPT. FD:DataSet1, FD:tfatture, BeforeRead>
      * <TOTEM:END>
      * <TOTEM:EPT. FD:DataSet1, FD:tfatture, BeforeReadPrev>
      * <TOTEM:END>
           EVALUATE DataSet1-KEYIS
           WHEN 1
              IF DataSet1-tfatture-KEY1-Asc
                 IF DataSet1-tfatture-LOCK
                    READ tfatture PREVIOUS WITH LOCK
                 ELSE
                    READ tfatture PREVIOUS WITH NO LOCK
                 END-IF
              ELSE
                 IF DataSet1-tfatture-LOCK
                    READ tfatture NEXT WITH LOCK
                 ELSE
                    READ tfatture NEXT WITH NO LOCK
                 END-IF
              END-IF
           END-EVALUATE
           PERFORM tfatture-tfa-k-data-MERGE-SPLITBUF
           PERFORM tfatture-tfa-k-cliente-MERGE-SPLITBUF
           MOVE STATUS-tfatture TO TOTEM-ERR-STAT
           MOVE "tfatture" TO TOTEM-ERR-FILE
           MOVE "READ PREVIOUS" TO TOTEM-ERR-MODE
      * <TOTEM:EPT. FD:DataSet1, FD:tfatture, AfterRead>
      * <TOTEM:END>
      * <TOTEM:EPT. FD:DataSet1, FD:tfatture, AfterReadPrev>
      * <TOTEM:END>
           .

       DataSet1-tfatture-Rec-Write.
      * <TOTEM:EPT. FD:DataSet1, FD:tfatture, BeforeWrite>
      * <TOTEM:END>
           MOVE STATUS-tfatture TO TOTEM-ERR-STAT
           MOVE "tfatture" TO TOTEM-ERR-FILE
           MOVE "WRITE" TO TOTEM-ERR-MODE
      * <TOTEM:EPT. FD:DataSet1, FD:tfatture, AfterWrite>
      * <TOTEM:END>
           .

       DataSet1-tfatture-Rec-Rewrite.
      * <TOTEM:EPT. FD:DataSet1, FD:tfatture, BeforeRewrite>
      * <TOTEM:END>
           MOVE STATUS-tfatture TO TOTEM-ERR-STAT
           MOVE "tfatture" TO TOTEM-ERR-FILE
           MOVE "REWRITE" TO TOTEM-ERR-MODE
      * <TOTEM:EPT. FD:DataSet1, FD:tfatture, AfterRewrite>
      * <TOTEM:END>
           .

       DataSet1-tfatture-Rec-Delete.
      * <TOTEM:EPT. FD:DataSet1, FD:tfatture, BeforeDelete>
      * <TOTEM:END>
           MOVE STATUS-tfatture TO TOTEM-ERR-STAT
           MOVE "tfatture" TO TOTEM-ERR-FILE
           MOVE "DELETE" TO TOTEM-ERR-MODE
      * <TOTEM:EPT. FD:DataSet1, FD:tfatture, AfterDelete>
      * <TOTEM:END>
           .

       tcorrisp-tco-k-data-MERGE-SPLITBUF.
           INITIALIZE tcorrisp-tco-k-data-SPLITBUF
           MOVE tco-data-doc(1:8) TO tcorrisp-tco-k-data-SPLITBUF(1:8)
           MOVE tco-chiave(1:10) TO tcorrisp-tco-k-data-SPLITBUF(9:10)
           .

       tcorrisp-tco-k-cliente-MERGE-SPLITBUF.
           INITIALIZE tcorrisp-tco-k-cliente-SPLITBUF
           MOVE tco-cliente(1:6) TO tcorrisp-tco-k-cliente-SPLITBUF(1:6)
           MOVE tco-data-doc(1:8) TO 
           tcorrisp-tco-k-cliente-SPLITBUF(7:8)
           MOVE tco-numero(1:6) TO tcorrisp-tco-k-cliente-SPLITBUF(15:6)
           .

       DataSet1-tcorrisp-INITSTART.
           IF DataSet1-tcorrisp-KEY-Asc
              MOVE Low-Value TO tco-chiave
           ELSE
              MOVE High-Value TO tco-chiave
           END-IF
           .

       DataSet1-tcorrisp-INITEND.
           IF DataSet1-tcorrisp-KEY-Asc
              MOVE High-Value TO tco-chiave
           ELSE
              MOVE Low-Value TO tco-chiave
           END-IF
           .

      * tcorrisp
       DataSet1-tcorrisp-START.
           IF DataSet1-tcorrisp-KEY-Asc
              START tcorrisp KEY >= tco-chiave
           ELSE
              START tcorrisp KEY <= tco-chiave
           END-IF
           .

       DataSet1-tcorrisp-START-NOTGREATER.
           IF DataSet1-tcorrisp-KEY-Asc
              START tcorrisp KEY <= tco-chiave
           ELSE
              START tcorrisp KEY >= tco-chiave
           END-IF
           .

       DataSet1-tcorrisp-START-GREATER.
           IF DataSet1-tcorrisp-KEY-Asc
              START tcorrisp KEY > tco-chiave
           ELSE
              START tcorrisp KEY < tco-chiave
           END-IF
           .

       DataSet1-tcorrisp-START-LESS.
           IF DataSet1-tcorrisp-KEY-Asc
              START tcorrisp KEY < tco-chiave
           ELSE
              START tcorrisp KEY > tco-chiave
           END-IF
           .

       DataSet1-tcorrisp-Read.
      * <TOTEM:EPT. FD:DataSet1, FD:tcorrisp, BeforeRead>
      * <TOTEM:END>
      * <TOTEM:EPT. FD:DataSet1, FD:tcorrisp, BeforeReadRecord>
      * <TOTEM:END>
           IF DataSet1-tcorrisp-LOCK
              READ tcorrisp WITH LOCK 
              KEY tco-chiave
           ELSE
              READ tcorrisp WITH NO LOCK 
              KEY tco-chiave
           END-IF
           PERFORM tcorrisp-tco-k-data-MERGE-SPLITBUF
           PERFORM tcorrisp-tco-k-cliente-MERGE-SPLITBUF
           MOVE STATUS-tcorrisp TO TOTEM-ERR-STAT 
           MOVE "tcorrisp" TO TOTEM-ERR-FILE
           MOVE "READ" TO TOTEM-ERR-MODE
      * <TOTEM:EPT. FD:DataSet1, FD:tcorrisp, AfterRead>
      * <TOTEM:END>
      * <TOTEM:EPT. FD:DataSet1, FD:tcorrisp, AfterReadRecord>
      * <TOTEM:END>
           .

       DataSet1-tcorrisp-Read-Next.
      * <TOTEM:EPT. FD:DataSet1, FD:tcorrisp, BeforeRead>
      * <TOTEM:END>
      * <TOTEM:EPT. FD:DataSet1, FD:tcorrisp, BeforeReadNext>
      * <TOTEM:END>
           IF DataSet1-tcorrisp-KEY-Asc
              IF DataSet1-tcorrisp-LOCK
                 READ tcorrisp NEXT WITH LOCK
              ELSE
                 READ tcorrisp NEXT WITH NO LOCK
              END-IF
           ELSE
              IF DataSet1-tcorrisp-LOCK
                 READ tcorrisp PREVIOUS WITH LOCK
              ELSE
                 READ tcorrisp PREVIOUS WITH NO LOCK
              END-IF
           END-IF
           PERFORM tcorrisp-tco-k-data-MERGE-SPLITBUF
           PERFORM tcorrisp-tco-k-cliente-MERGE-SPLITBUF
           MOVE STATUS-tcorrisp TO TOTEM-ERR-STAT
           MOVE "tcorrisp" TO TOTEM-ERR-FILE
           MOVE "READ NEXT" TO TOTEM-ERR-MODE
      * <TOTEM:EPT. FD:DataSet1, FD:tcorrisp, AfterRead>
      * <TOTEM:END>
      * <TOTEM:EPT. FD:DataSet1, FD:tcorrisp, AfterReadNext>
      * <TOTEM:END>
           .

       DataSet1-tcorrisp-Read-Prev.
      * <TOTEM:EPT. FD:DataSet1, FD:tcorrisp, BeforeRead>
      * <TOTEM:END>
      * <TOTEM:EPT. FD:DataSet1, FD:tcorrisp, BeforeReadPrev>
      * <TOTEM:END>
           IF DataSet1-tcorrisp-KEY-Asc
              IF DataSet1-tcorrisp-LOCK
                 READ tcorrisp PREVIOUS WITH LOCK
              ELSE
                 READ tcorrisp PREVIOUS WITH NO LOCK
              END-IF
           ELSE
              IF DataSet1-tcorrisp-LOCK
                 READ tcorrisp NEXT WITH LOCK
              ELSE
                 READ tcorrisp NEXT WITH NO LOCK
              END-IF
           END-IF
           PERFORM tcorrisp-tco-k-data-MERGE-SPLITBUF
           PERFORM tcorrisp-tco-k-cliente-MERGE-SPLITBUF
           MOVE STATUS-tcorrisp TO TOTEM-ERR-STAT
           MOVE "tcorrisp" TO TOTEM-ERR-FILE
           MOVE "READ PREVIOUS" TO TOTEM-ERR-MODE
      * <TOTEM:EPT. FD:DataSet1, FD:tcorrisp, AfterRead>
      * <TOTEM:END>
      * <TOTEM:EPT. FD:DataSet1, FD:tcorrisp, AfterReadPrev>
      * <TOTEM:END>
           .

       DataSet1-tcorrisp-Rec-Write.
      * <TOTEM:EPT. FD:DataSet1, FD:tcorrisp, BeforeWrite>
      * <TOTEM:END>
           MOVE STATUS-tcorrisp TO TOTEM-ERR-STAT
           MOVE "tcorrisp" TO TOTEM-ERR-FILE
           MOVE "WRITE" TO TOTEM-ERR-MODE
      * <TOTEM:EPT. FD:DataSet1, FD:tcorrisp, AfterWrite>
      * <TOTEM:END>
           .

       DataSet1-tcorrisp-Rec-Rewrite.
      * <TOTEM:EPT. FD:DataSet1, FD:tcorrisp, BeforeRewrite>
      * <TOTEM:END>
           MOVE STATUS-tcorrisp TO TOTEM-ERR-STAT
           MOVE "tcorrisp" TO TOTEM-ERR-FILE
           MOVE "REWRITE" TO TOTEM-ERR-MODE
      * <TOTEM:EPT. FD:DataSet1, FD:tcorrisp, AfterRewrite>
      * <TOTEM:END>
           .

       DataSet1-tcorrisp-Rec-Delete.
      * <TOTEM:EPT. FD:DataSet1, FD:tcorrisp, BeforeDelete>
      * <TOTEM:END>
           MOVE STATUS-tcorrisp TO TOTEM-ERR-STAT
           MOVE "tcorrisp" TO TOTEM-ERR-FILE
           MOVE "DELETE" TO TOTEM-ERR-MODE
      * <TOTEM:EPT. FD:DataSet1, FD:tcorrisp, AfterDelete>
      * <TOTEM:END>
           .

       DataSet1-INIT-RECORD.
           INITIALIZE tfa-rec OF tfatture
           INITIALIZE tco-rec OF tcorrisp
           .


      * FD's Initialize Paragraph
       DataSet1-tfatture-INITREC.
           INITIALIZE tfa-rec OF tfatture
               REPLACING NUMERIC       DATA BY ZEROS
                         ALPHANUMERIC  DATA BY SPACES
                         ALPHABETIC    DATA BY SPACES
           .

      * FD's Initialize Paragraph
       DataSet1-tcorrisp-INITREC.
           INITIALIZE tco-rec OF tcorrisp
               REPLACING NUMERIC       DATA BY ZEROS
                         ALPHANUMERIC  DATA BY SPACES
                         ALPHABETIC    DATA BY SPACES
           .

      *
       DataSet1-DISPATCH-BUFTOFLD.
           .

       form1-Open-Routine.
           PERFORM form1-Scrn
           PERFORM form1-Proc
           .

       form1-Scrn.
           PERFORM form1-Create-Win
           PERFORM form1-Init-Value
           PERFORM form1-Init-Data
      * Tab keystrok settings
      * Tool Bar
           PERFORM form1-DISPLAY
           .

       form1-Create-Win.
           Display Independent GRAPHICAL WINDOW
              LINES 22,13,
              SIZE 48,30,
              HEIGHT-IN-CELLS,
              WIDTH-IN-CELLS,
              COLOR 131329,
              CONTROL FONT Calibri14-Occidentale,
              LINK TO THREAD,
              MODELESS,
              NO SCROLL,
              TITLE-BAR,
              TITLE titolo,
              WITH SYSTEM MENU,
              USER-GRAY,
              USER-WHITE,
              No WRAP,
              EVENT PROCEDURE form-cliente-Event-Proc,
              HANDLE IS form1-handle,
      * <TOTEM:EPT. FORM:form1, FORM:form1, AfterCreateWin>
      * <TOTEM:END>


      * Tool Bar    
      * Status-bar
           DISPLAY form1 UPON form1-handle
      * DISPLAY-COLUMNS settings
           .

       form1-PROC.
      * <TOTEM:EPT. FORM:form1, FORM:form1, BeforeAccept>
           move 78-ID-ef-anno to control-id.
           move 4 to accept-control.

           .
      * <TOTEM:END>
           PERFORM UNTIL Exit-Pushed
              ACCEPT form1
                 ON EXCEPTION
                    PERFORM form1-Evaluate-Func
                 MOVE 1 TO TOTEM-Form-Index
              END-ACCEPT
      * <TOTEM:EPT. FORM:form1, FORM:form1, AfterEndAccept>
      * <TOTEM:END>
           END-PERFORM
      * <TOTEM:EPT. FORM:form1, FORM:form1, BeforeDestroyWindow>
      * <TOTEM:END>
           DESTROY form1-handle
           INITIALIZE Key-Status
           .

       form1-Evaluate-Func.
      * <TOTEM:EPT. FORM:form1, FORM:form1, AfterAccept>
      * <TOTEM:END>
           EVALUATE TRUE
              WHEN Exit-Pushed
                 PERFORM form1-Exit
              WHEN Event-Occurred
                 IF Event-Type = Cmd-Close
                    PERFORM form1-Exit
                 END-IF
              WHEN Key-Status = 13
                 PERFORM pb-procedi-LinkTo
              WHEN Key-Status = 1000
                 PERFORM rb-fatture-LinkTo
              WHEN Key-Status = 1001
                 PERFORM rb-corrisp-LinkTo
              WHEN Key-Status = 465
                 PERFORM pb-singola-LinkTo
           END-EVALUATE
      * avoid changing focus
           MOVE 4 TO Accept-Control
           .

       form1-CLEAR.
           PERFORM form1-INIT-VALUE
           PERFORM form1-DISPLAY
           .

       form1-DISPLAY.
      * <TOTEM:EPT. FORM:form1, FORM:form1, BeforeDisplay>
      * <TOTEM:END>
           DISPLAY form1 UPON form1-handle
      * <TOTEM:EPT. FORM:form1, FORM:form1, AfterDisplay>
           SET LK-BL-SCRITTURA     TO TRUE.
           MOVE COMO-PROG-ID       TO LK-BL-PROG-ID.
           MOVE FORM1-HANDLE       TO LK-HND-WIN.
           CALL "BLOCKPGM"  USING LK-BLOCKPGM.
           CANCEL "BLOCKPGM".

           .
      * <TOTEM:END>
           .

       form1-Exit.
      * for main screen
      * <TOTEM:EPT. FORM:form1, FORM:form1, BeforeExit>
      * <TOTEM:END>
           MOVE 27 TO Key-Status
           .

       form1-Init-Data.
           MOVE 1 TO TOTEM-Form-Index
           MOVE 0 TO TOTEM-Frame-Index
           .

       form1-Init-Value.
           MOVE titolo TO TOTEM-MSG-TITLE
      * <TOTEM:EPT. FORM:form1, FORM:form1, SetDefault>
      * <TOTEM:END>
           PERFORM form1-FLD-TO-BUF
           .


       form1-ALLGRID-RESET.
           .

      * for Form's Validation
       form1-VALIDATION-ROUTINE.
           SET TOTEM-CHECK-OK TO TRUE
           .


       form1-Buf-To-Fld.
      * <TOTEM:EPT. FORM:form1, FORM:form1, BeforeBufToFld>
      * <TOTEM:END>
      * <TOTEM:EPT. FORM:form1, FORM:form1, AfterBufToFld>
      * <TOTEM:END>
           .

       form1-Fld-To-Buf.
      * <TOTEM:EPT. FORM:form1, FORM:form1, BeforeFldToBuf>
      * <TOTEM:END>
      * <TOTEM:EPT. FORM:form1, FORM:form1, AfterFldToBuf>
      * <TOTEM:END>
           .

       form1-CONTROLLO-OLD.
           set SiSalvato to true.
           if mod = 0 exit paragraph end-if.
           perform form1-BUF-TO-FLD.
           move 0 to scelta.
           .
       form1-EXTENDED-FILE-STATUS.
           CALL "C$RERRNAME" USING TOTEM-MSG-ERR-FILE
           CALL "C$RERR" USING EXTEND-STAT, TEXT-MESSAGE
           MOVE PRIMARY-ERROR TO TOTEM-MSG-ID
           PERFORM form1-SHOW-MSG-ROUTINE
           .

       form1-SHOW-MSG-ROUTINE.
           PERFORM SHOW-MSG-ROUTINE
           PERFORM form1-DISPLAY-MESSAGE
           .

       form1-DISPLAY-MESSAGE.
           PERFORM MESSAGE-BOX-ROUTINE
           DISPLAY MESSAGE BOX TOTEM-MSG-TEXT
               TITLE IS TOTEM-MSG-TITLE
               TYPE  IS TOTEM-MSG-BUTTON-TYPE
               ICON  IS TOTEM-MSG-DEFAULT-BUTTON
               RETURNING TOTEM-MSG-RETURN-VALUE
           .

       form1-Save-Status.
           .             

       form1-Restore-Status.
           .



       form-cliente-Event-Proc.
           .

      * USER DEFINE PARAGRAPH
       PARAGRFO-COPY.
      * <TOTEM:PARA. PARAGRFO-COPY>
           copy "color-custom.cpy"              
           .
      * <TOTEM:END>

      * EVENT PARAGRAPH
       ginqui-Ev-Before-Program.
      * <TOTEM:PARA. ginqui-Ev-Before-Program>
           move LK-BL-PROG-ID    TO COMO-PROG-ID 
           .
      * <TOTEM:END>
       ginqui-Ev-After-Program.
      * <TOTEM:PARA. ginqui-Ev-After-Program>
           SET LK-BL-CANCELLAZIONE TO TRUE.
           MOVE COMO-PROG-ID       TO LK-BL-PROG-ID.
           CALL "BLOCKPGM"  USING LK-BLOCKPGM 
           .
      * <TOTEM:END>
       pb-procedi-LinkTo.
      * <TOTEM:PARA. pb-procedi-LinkTo>
           modify form1-handle, visible false.
           set tutto-ok to true.
           evaluate tipo-doc
           when 1 set vdocum-tipo-fattura to true
           when 2 set vdocum-tipo-corrisp to true
           end-evaluate.

           move ef-anno-buf   to vdocum-anno.
           move ef-numero-buf to vdocum-numero.
                                    
           perform CANCELLA-COLORE.
           call   "notacr" using vdocum-linkage.
           cancel "notacr".
           modify form1-handle, visible true.

           perform CANCELLA-COLORE.
           move 78-ID-ef-anno to control-id.
           move 4 to accept-control 
           .
      * <TOTEM:END>
       Screen1-Rb-1-BeforeProcedure.
      * <TOTEM:PARA. Screen1-Rb-1-BeforeProcedure>
           modify control-handle, color = colore-nu
           .
      * <TOTEM:END>
       Screen1-Rb-1-AfterProcedure.
      * <TOTEM:PARA. Screen1-Rb-1-AfterProcedure>
           modify control-handle, color = colore-or
           .
      * <TOTEM:END>
       rb-fatture-LinkTo.
      * <TOTEM:PARA. rb-fatture-LinkTo>
           evaluate tipo-doc
           when 1
                modify rb-fatture, bitmap-number = 6
                modify rb-corrisp, bitmap-number = 1
           when 2
                modify rb-fatture, bitmap-number = 5
                modify rb-corrisp, bitmap-number = 2
           end-evaluate 
           .
      * <TOTEM:END>
       rb-corrisp-LinkTo.
      * <TOTEM:PARA. rb-corrisp-LinkTo>
           evaluate tipo-doc
           when 1
                modify rb-fatture, bitmap-number = 6
                modify rb-corrisp, bitmap-number = 1
           when 2
                modify rb-fatture, bitmap-number = 5
                modify rb-corrisp, bitmap-number = 2
           end-evaluate 
           .
      * <TOTEM:END>
       ef-anno-s-BeforeProcedure.
      * <TOTEM:PARA. ef-anno-s-BeforeProcedure>
           MODIFY CONTROL-HANDLE COLOR = COLORE-NU
           .
      * <TOTEM:END>
       ef-anno-s-AfterProcedure.
      * <TOTEM:PARA. ef-anno-s-AfterProcedure>
           MODIFY CONTROL-HANDLE COLOR = COLORE-OR
           .
      * <TOTEM:END>
       ef-numero-s-BeforeProcedure.
      * <TOTEM:PARA. ef-numero-s-BeforeProcedure>
           MODIFY CONTROL-HANDLE COLOR = COLORE-NU
           .
      * <TOTEM:END>
       ef-numero-s-AfterProcedure.
      * <TOTEM:PARA. ef-numero-s-AfterProcedure>
           MODIFY CONTROL-HANDLE COLOR = COLORE-OR
           .
      * <TOTEM:END>
       pb-singola-LinkTo.
      * <TOTEM:PARA. pb-singola-LinkTo>
           set tutto-ok to true.
           evaluate tipo-doc
           when 1
                inquire ef-anno,   value tfa-anno
                inquire ef-numero, value tfa-numero
                read tfatture no lock
                     invalid
                     set errori to true
                     display message "Fattura non valida"
                               title tit-err
                                icon 2
                end-read
           when 2
                inquire ef-anno,   value tco-anno
                inquire ef-numero, value tco-numero
                read tcorrisp no lock
                     invalid
                     set errori to true
                     display message "Corrispettivo non valido"
                               title tit-err
                                icon 2
                end-read
           end-evaluate.

           if tutto-ok
              evaluate tipo-doc
              when 1 set vdocum-tipo-fattura to true
              when 2 set vdocum-tipo-corrisp to true
              end-evaluate

              move ef-anno-buf   to vdocum-anno
              move ef-numero-buf to vdocum-numero

              call   "vdocum" using vdocum-linkage
              cancel "vdocum"
           else
              perform CANCELLA-COLORE
              move 78-ID-ef-anno to control-id
              move 4             to accept-control
           end-if 
           .
      * <TOTEM:END>

      *{TOTEM}END

      *{TOTEM}SHOW-MSG
       MESSAGE-FOR-FILEERROR.
           CALL "C$RERRNAME" USING TOTEM-MSG-ERR-FILE
           CALL "C$RERR" USING EXTEND-STAT, TEXT-MESSAGE
              MOVE PRIMARY-ERROR TO TOTEM-MSG-ID
           .

       SHOW-TRANSACTION-ROUTINE.
           IF TOTEM-TRANSACTION-FLAG = SPACES
              IF TRANSACTION-STATUS NOT = 0
                 STRING "TRANSACTION ERROR ", TRANSACTION-STATUS
                    DELIMITED BY SIZE INTO TOTEM-MSG-1
              END-IF
           ELSE
              PERFORM SHOW-MSG-ROUTINE
              IF TRANSACTION-STATUS = 0
                 MOVE "Transazione terminata con Rollback." TO 
           TOTEM-MSG-3
              ELSE
                 STRING "TRANSACTION ERROR ", TRANSACTION-STATUS
                    DELIMITED BY SIZE INTO TOTEM-MSG-3
              END-IF
           END-IF
           .

       SHOW-MSG-ROUTINE.
           MOVE SPACE TO TOTEM-MSG-1 TOTEM-MSG-2 TOTEM-MSG-3
           EVALUATE TOTEM-MSG-ID
               WHEN "10"
                    STRING "File:" TOTEM-MSG-ERR-FILE DELIMITED BY SPACE
                       INTO TOTEM-MSG-1
                    MOVE "Nessun altro dato." TO TOTEM-MSG-2
                    MOVE MB-DEFAULT-ICON TO TOTEM-MSG-ICON-TYPE
                    MOVE MB-OK TO TOTEM-MSG-BUTTON-TYPE
               WHEN "22"
                    STRING "File:" TOTEM-MSG-ERR-FILE DELIMITED BY SPACE
                       INTO TOTEM-MSG-1
                    MOVE "Chiave Duplicata." TO TOTEM-MSG-2
                    MOVE MB-ERROR-ICON TO TOTEM-MSG-ICON-TYPE
                    MOVE MB-OK TO TOTEM-MSG-BUTTON-TYPE
               WHEN "23"
                    STRING "File:" TOTEM-MSG-ERR-FILE DELIMITED BY SPACE
                       INTO TOTEM-MSG-1
                    MOVE "Raggiunta fine file." TO TOTEM-MSG-2
                    MOVE MB-WARNING-ICON TO TOTEM-MSG-ICON-TYPE
                    MOVE MB-OK TO TOTEM-MSG-BUTTON-TYPE
               WHEN "101"
                    MOVE "Terminare l'applicazione?" TO TOTEM-MSG-1
                    MOVE 4 TO TOTEM-MSG-ICON-TYPE
                    MOVE MB-YES-NO TO TOTEM-MSG-BUTTON-TYPE
               WHEN "201"
                    MOVE "Aggiungere un nuovo record?" TO TOTEM-MSG-1
                    MOVE 4 TO TOTEM-MSG-ICON-TYPE
                    MOVE MB-YES-NO TO TOTEM-MSG-BUTTON-TYPE
               WHEN "202"
                    MOVE "Aggiornare il Record?" TO TOTEM-MSG-1
                    MOVE 4 TO TOTEM-MSG-ICON-TYPE
                    MOVE MB-YES-NO TO TOTEM-MSG-BUTTON-TYPE
               WHEN "203"
                    MOVE "Cancellare il Record?" TO TOTEM-MSG-1
                    MOVE 4 TO TOTEM-MSG-ICON-TYPE
                    MOVE MB-YES-NO TO TOTEM-MSG-BUTTON-TYPE
               WHEN "204"
                    MOVE "Chiave duplicata." TO TOTEM-MSG-1
                    MOVE MB-WARNING-ICON TO TOTEM-MSG-ICON-TYPE
                    MOVE MB-OK TO TOTEM-MSG-BUTTON-TYPE
               WHEN "301"
                    MOVE "Inserimento avvenuto con Successo." TO 
           TOTEM-MSG-1
                    MOVE MB-DEFAULT-ICON TO TOTEM-MSG-ICON-TYPE
                    MOVE MB-OK TO TOTEM-MSG-BUTTON-TYPE
               WHEN "302"
                    MOVE "Aggiornamento avvenuto con Successo." TO 
           TOTEM-MSG-1
                    MOVE MB-DEFAULT-ICON TO TOTEM-MSG-ICON-TYPE
                    MOVE MB-OK TO TOTEM-MSG-BUTTON-TYPE
               WHEN "303"
                    MOVE "Cancellazione avvenuta con Successo." TO 
           TOTEM-MSG-1
                    MOVE MB-DEFAULT-ICON TO TOTEM-MSG-ICON-TYPE
                    MOVE MB-OK TO TOTEM-MSG-BUTTON-TYPE
               WHEN "401"
                    MOVE "Shell non trovata." TO TOTEM-MSG-1
                    MOVE MB-ERROR-ICON TO TOTEM-MSG-ICON-TYPE
                    MOVE MB-OK TO TOTEM-MSG-BUTTON-TYPE
               WHEN OTHER
                    MOVE TEXT-MESSAGE TO TOTEM-MSG-1
                    STRING "FILE:" TOTEM-MSG-ERR-FILE DELIMITED BY SPACE
                       INTO TOTEM-MSG-3
                    MOVE 0 TO TOTEM-IDX1
                    INSPECT TOTEM-MSG-3 TALLYING TOTEM-IDX1
                       FOR TRAILING SPACE
                    STRING TOTEM-MSG-3(1:TOTEM-MSG-LENGTH - 
           TOTEM-IDX1), 
                       ", FILE STATUS ", PRIMARY-ERROR "," 
                       SECONDARY-ERROR
                    DELIMITED BY SIZE INTO TOTEM-MSG-2
                    MOVE SPACES TO TOTEM-MSG-3
                    MOVE MB-ERROR-ICON TO TOTEM-MSG-ICON-TYPE
                    MOVE MB-OK TO TOTEM-MSG-BUTTON-TYPE
           END-EVALUATE
           PERFORM MESSAGE-BOX-ROUTINE
           .

       MESSAGE-BOX-ROUTINE.
           MOVE 1 TO TOTEM-MSG-TEXT-POINTER
           IF TOTEM-MSG-1 NOT = SPACE
              MOVE 0 TO TOTEM-MSG-SIZE
              INSPECT TOTEM-MSG-1 TALLYING TOTEM-MSG-SIZE FOR TRAILING 
           SPACE
              STRING TOTEM-MSG-1( 1 : TOTEM-MSG-LENGTH - TOTEM-MSG-SIZE 
           )
                 DELIMITED BY SIZE
                 INTO TOTEM-MSG-TEXT, POINTER TOTEM-MSG-TEXT-POINTER
           END-IF

           IF TOTEM-MSG-2 NOT = SPACE
              MOVE 0 TO TOTEM-MSG-SIZE
              INSPECT TOTEM-MSG-2 TALLYING TOTEM-MSG-SIZE FOR TRAILING 
           SPACE
              IF TOTEM-MSG-TEXT-POINTER > 1
                 STRING X"0A" DELIMITED BY SIZE
                     INTO TOTEM-MSG-TEXT, POINTER TOTEM-MSG-TEXT-POINTER
              END-IF
              STRING TOTEM-MSG-2( 1 : TOTEM-MSG-LENGTH - TOTEM-MSG-SIZE 
           )
                  DELIMITED BY SIZE
                  INTO TOTEM-MSG-TEXT, POINTER TOTEM-MSG-TEXT-POINTER
           END-IF

           IF TOTEM-MSG-3 NOT = SPACE
              MOVE 0 TO TOTEM-MSG-SIZE
              INSPECT TOTEM-MSG-3 TALLYING TOTEM-MSG-SIZE FOR TRAILING 
           SPACE
              IF TOTEM-MSG-TEXT-POINTER > 1
                 STRING X"0A" DELIMITED BY SIZE
                     INTO TOTEM-MSG-TEXT, POINTER TOTEM-MSG-TEXT-POINTER
              END-IF
              STRING TOTEM-MSG-3( 1 : TOTEM-MSG-LENGTH - TOTEM-MSG-SIZE 
           )
                  DELIMITED BY SIZE
                  INTO TOTEM-MSG-TEXT, POINTER TOTEM-MSG-TEXT-POINTER
           END-IF

           IF TOTEM-MSG-TEXT-POINTER = 1
              MOVE 0 TO TOTEM-MSG-SIZE
              INSPECT TOTEM-MSG-TEXT TALLYING TOTEM-MSG-SIZE FOR 
           TRAILING SPACE
                  COMPUTE TOTEM-MSG-TEXT-POINTER = 
           TOTEM-MSG-FULL-LENGTH - TOTEM-MSG-SIZE + 1
           END-IF
           MOVE LOW-VALUES TO TOTEM-MSG-TEXT(TOTEM-MSG-TEXT-POINTER : 1 
           )
           .

       MESSAGE-BOX-DISPLAY.
           PERFORM SHOW-MSG-ROUTINE
           PERFORM MESSAGE-BOX-ROUTINE
           DISPLAY MESSAGE BOX TOTEM-MSG-TEXT
               TITLE IS TOTEM-MSG-TITLE
               TYPE  IS TOTEM-MSG-BUTTON-TYPE
               ICON  IS TOTEM-MSG-DEFAULT-BUTTON
               RETURNING TOTEM-MSG-RETURN-VALUE
           .

      *{TOTEM}END

