      *{TOTEM}PRG-COMMENT
      * tcodiva.Cbl
      * tcodiva.Cbl is generated by TOTEM
      * This is a generated file. DO NOT modify this file directly.
      *{TOTEM}END
       IDENTIFICATION       DIVISION.
      *{TOTEM}PRGID
       PROGRAM-ID.          tcodiva.
       AUTHOR.              Andrea.
       DATE-WRITTEN.        lunedì 21 maggio 2012 11:05:52.
       REMARKS.
      *{TOTEM}END

       ENVIRONMENT          DIVISION.
       CONFIGURATION        SECTION.
       SPECIAL-NAMES.
      *{TOTEM}SPECIAL-NAME
      * <TOTEM:EPT. INIT:tcodiva, INIT:tcodiva, SpecialName>
      * <TOTEM:END>
      *{TOTEM}END
      *{TOTEM}ACTIVEX-DEF
      *{TOTEM}END
      *{TOTEM}DECIMAL-POINT
           DECIMAL-POINT IS COMMA.
      *{TOTEM}END

       INPUT-OUTPUT         SECTION.
       FILE-CONTROL.
      *{TOTEM}FILE-CONTROL
           COPY "codiva.sl".
      *{TOTEM}END
       DATA                 DIVISION.
       FILE                 SECTION.
      *{TOTEM}FILE
           COPY "codiva.fd".
      *{TOTEM}END

       WORKING-STORAGE      SECTION.
      *{TOTEM}ACU-DEF
               COPY "acugui.def".
               COPY "acucobol.def".
               COPY "fonts.def".
               COPY "crtvars.def".
               COPY "showmsg.def".
               COPY "totem.def".
               COPY "comune.def".
               COPY "custom.def".
               COPY "UTYDATA.DEF".
      *{TOTEM}END

      *{TOTEM}COPY-WORKING
      * Key Status
       77 Key-Status IS SPECIAL-NAMES CRT STATUS PIC 9(5) VALUE 0.
          88 Enter-Pushed VALUE 13.
          88 Exit-Pushed VALUE 27.
          88 Message-Received VALUE 95.
          88 Event-Occurred VALUE 96.
          88 Screen-No-Input-Field VALUE 97.
      * Properties & User defined Working Stoarge
       77 Form1-Handle
                  USAGE IS HANDLE OF WINDOW.
       77 TIPO-DATA        PIC  9(8)
                  VALUE IS 0.
       77 Form1-Tb-1-Handle
                  USAGE IS HANDLE OF WINDOW.
       78 titolo VALUE IS "Studio - Tabella Codici IVA". 
       77 E-ESCI           PIC  9
                  VALUE IS 1.
       77 E-NUOVO          PIC  9
                  VALUE IS 1.
       77 E-CANCELLA       PIC  9
                  VALUE IS 1.
       77 E-SALVA          PIC  9
                  VALUE IS 1.
       77 E-ANTEPRIMA      PIC  9
                  VALUE IS 0.
       77 E-MODIFICA       PIC  9
                  VALUE IS 1.
       77 E-STAMPA         PIC  9
                  VALUE IS 0.
       77 E-CERCA          PIC  9
                  VALUE IS 1.
       77 MESSAGGIO        PIC  X(300)
                  VALUE IS SPACE.
       77 Small-Font
                  USAGE IS HANDLE OF FONT SMALL-FONT.
       77 toolbar-bmp      PIC  S9(9)
                  USAGE IS COMP-4
                  VALUE IS 0.
       01 rec-grid.
           05 col-codice       PIC  x(03).
           05 col-des          PIC  X(50).
           05 col-aliquota     PIC  zz9,99.
       77 Screen1-Handle
                  USAGE IS HANDLE OF WINDOW.
       01 FILLER           PIC  9.
           88 ricarica VALUE IS 1    WHEN SET TO FALSE  0. 
       77 esegui-73x21-bmp PIC  S9(9)
                  USAGE IS COMP-4
                  VALUE IS 0.
       77 Default-Font
                  USAGE IS HANDLE OF FONT DEFAULT-FONT.
       77 STATUS-codiva    PIC  X(2).
           88 Valid-STATUS-codiva VALUE IS "00" THRU "09". 
       77 Calibri14-Occidentale
                  USAGE IS HANDLE OF FONT.
       77 LOGO_PICCOLO-BMP PIC  S9(9)
                  USAGE IS COMP-4
                  VALUE IS 0.

      ***********************************************************
      *   Code Gen's Buffer                                     *
      ***********************************************************
       77 STATUS-Form1-FLAG-REFRESH PIC  9.
          88 Form1-FLAG-REFRESH  VALUE 1 FALSE 0. 
       77 TMP-Form1-KEY1-ORDER  PIC X VALUE "A".
       77 TMP-Form1-codiva-RESTOREBUF  PIC X(612).
       77 TMP-Form1-KEYIS  PIC 9(3) VALUE 1.
       77 Form1-MULKEY-TMPBUF   PIC X(612).
       77 TMP-DataSet1-codiva-BUF     PIC X(612).
      * VARIABLES FOR RECORD LENGTH.
       77  TotemFdSlRecordClearOffset   PIC 9(5) COMP-4.
       77  TotemFdSlRecordLength        PIC 9(5) COMP-4.
      * FILE'S LOCK MODE FLAG
       77 DataSet1-codiva-LOCK-FLAG   PIC X VALUE SPACE.
           88 DataSet1-codiva-LOCK  VALUE "Y".
       77 DataSet1-KEYIS   PIC 9(3) VALUE 1.
       77 DataSet1-codiva-KEY1-ORDER  PIC X VALUE "A".
          88 DataSet1-codiva-KEY1-Asc  VALUE "A".
          88 DataSet1-codiva-KEY1-Desc VALUE "D".


       01 OLD-iva-rec.
           05 OLD-iva-chiave.
               10 OLD-iva-codice       PIC  x(3).
           05 OLD-iva-dati.
               10 OLD-iva-descrizione  PIC  x(50).
               10 OLD-iva-aliquota     PIC  9(3)v99.
               10 OLD-iva-vuoti.
                   15 FILLER           PIC  9(18).
                   15 FILLER           PIC  9(18).
                   15 FILLER           PIC  9(18).
                   15 FILLER           PIC  x(500).
      *{TOTEM}END

      *{TOTEM}ID-LOGICI
      ***** Elenco ID Logici *****
      ***** Fine ID Logici *****
      *{TOTEM}END

       LINKAGE          SECTION.
      *{TOTEM}LINKAGE
           COPY  "BLOCKPGM.LKS".

      *{TOTEM}END

       SCREEN           SECTION.
      *{TOTEM}COPY-SCREEN
      * FORM
       01 
           Form1, 
           .

      * LABEL
       05
           CST-BLOCKPGM, 
           Label, 
           COL 49,57, 
           LINE 1,00,
           LINES 0,48 ,
           SIZE 2,10 ,
           ID IS 12,
           HEIGHT-IN-CELLS,
           WIDTH-IN-CELLS,
           TRANSPARENT,
           TITLE "BlockPgm",
           VISIBLE v-custom,
           .

      * GRID
       05
           form1-gd-1, 
           Grid, 
           COL 2,30, 
           LINE 1,78,
           LINES 22,70 ,
           SIZE 51,90 ,
           ADJUSTABLE-COLUMNS,
           BOXED,
           DATA-COLUMNS (1, 4, 54),
           ALIGNMENT ("C", "U", "R"),
           SEPARATION (5, 5, 5),
           DATA-TYPES ("X(3)", "X(50)", "zz9,99"),
           NUM-COL-HEADINGS 1,
           COLUMN-HEADINGS,
           CURSOR-FRAME-WIDTH 2,
           DIVIDER-COLOR 1,
           HEADING-COLOR 257,
           HEADING-DIVIDER-COLOR 1,
           ID IS 1,
           HEIGHT-IN-CELLS,
           WIDTH-IN-CELLS,
           RECORD-DATA rec-grid,
           TILED-HEADINGS,
           USE-TAB,
           VIRTUAL-WIDTH 50,
           VPADDING 10,
           VSCROLL,
           EVENT PROCEDURE Form1-Gd-1-Event-Proc,
           .

      * TOOLBAR
       01
           Form1-Tb-1,
           .    

      * PUSH BUTTON
       05
           TOOL-ESCI, 
           Push-Button, 
           COL 1,00, 
           LINE 1,09,
           LINES 64,00 ,
           SIZE 48,00 ,
           BITMAP-HANDLE toolbar-bmp,
           BITMAP-NUMBER 1,
           UNFRAMED,
           SQUARE,
           ENABLED E-ESCI,
           EXCEPTION-VALUE 27,
           FLAT,
           ID IS 2,
           SELF-ACT,
           ESCAPE-BUTTON,
           TITLE "&Esci",
           .

      * PUSH BUTTON
       05
           TOOL-NUOVO, 
           Push-Button, 
           COL 6,30, 
           LINE 1,09,
           LINES 64,00 ,
           SIZE 48,00 ,
           BITMAP-HANDLE toolbar-bmp,
           BITMAP-NUMBER 2,
           UNFRAMED,
           SQUARE,
           ENABLED E-NUOVO,
           EXCEPTION-VALUE 2,
           FLAT,
           ID IS 6,
           SELF-ACT,
           TITLE "Nuovo (F2)",
           .

      * PUSH BUTTON
       05
           TOOL-CANCELLA, 
           Push-Button, 
           COL 16,90, 
           LINE 1,09,
           LINES 64,00 ,
           SIZE 48,00 ,
           BITMAP-HANDLE toolbar-bmp,
           UNFRAMED,
           SQUARE,
           ENABLED E-CANCELLA,
           EXCEPTION-VALUE 4,
           FLAT,
           ID IS 5,
           SELF-ACT,
           TITLE "Cancella (F4)",
           BITMAP-NUMBER BitmapNumDelete
           .

      * PUSH BUTTON
       05
           TOOL-SALVA, 
           Push-Button, 
           COL 11,60, 
           LINE 1,09,
           LINES 64,00 ,
           SIZE 48,00 ,
           BITMAP-HANDLE toolbar-bmp,
           UNFRAMED,
           SQUARE,
           ENABLED E-SALVA,
           EXCEPTION-VALUE 3,
           FLAT,
           ID IS 8,
           SELF-ACT,
           TITLE "Salva (F3)",
           BITMAP-NUMBER BitmapNumSave
           .

      * CHECK BOX
       05
           TOOL-MODIFICA, 
           Check-Box, 
           COL 22,20, 
           LINE 1,09,
           LINES 64,00 ,
           SIZE 48,00 ,
           BITMAP-HANDLE toolbar-bmp,
           BITMAP-NUMBER 5,
           UNFRAMED,
           SQUARE,
           ENABLED E-MODIFICA,
           EXCEPTION-VALUE 1005
           FLAT,
           ID IS 7,
           SELF-ACT,
           TITLE "Modifica (F5)",
           VALUE MOD,
           AFTER PROCEDURE TOOL-MODIFICA-AfterProcedure,
           BEFORE PROCEDURE TOOL-MODIFICA-BeforeProcedure, 
           .
      * PUSH BUTTON
       05
           TOOL-CERCA, 
           Push-Button, 
           COL 27,50, 
           LINE 1,09,
           LINES 64,00 ,
           SIZE 48,00 ,
           BITMAP-HANDLE toolbar-bmp,
           UNFRAMED,
           SQUARE,
           ENABLED E-CERCA,
           EXCEPTION-VALUE 8,
           FLAT,
           ID IS 11,
           SELF-ACT,
           TITLE "Cerca (F8)",
           VISIBLE 0,
           BITMAP-NUMBER BitmapNumZoom
           .

      * BITMAP
       05
           Form1-Bt-1, 
           Bitmap, 
           COL 50,70, 
           LINE 1,00,
           LINES 64,00 ,
           SIZE 48,00 ,
           BITMAP-HANDLE LOGO_PICCOLO-BMP,
           BITMAP-NUMBER 1,
           ID IS 13,
           .

      *{TOTEM}END

      *{TOTEM}LINKPARA
       PROCEDURE  DIVISION USING LK-BLOCKPGM.
      *{TOTEM}END

      *{TOTEM}DECLARATIVE
       DECLARATIVES.
      * <TOTEM:EPT. INIT:tcodiva, INIT:tcodiva, BeforeDeclarative>
       codiva-ERR SECTION.
           use after error procedure on codiva.
           evaluate status-codiva
           when "35"
                display message "File [codiva] not found!"
                           title titolo
                            icon 3
                set errori to true
           when "39"
                display message "File [codiva] Mismatch size!"
                           title titolo
                            icon 3
                set errori to true
           when "98"
                display message "[codiva] Indexed file corrupt!"
                           title titolo
                            icon 3
                set errori to true 
           when "93"             
                move 0 to mod
                modify tool-modifica, value = mod  
                set StatusVisua to true
                open input codiva
                display message box MSG-Gia-in-uso-su-altro-terminale
                            x"0d0a" MSG-SOLA-VISUA
                        title = tit-err
                        icon is mb-error-icon      
           end-evaluate.

      * <TOTEM:END>
       INPUT-ERROR SECTION.
           USE AFTER STANDARD ERROR PROCEDURE ON INPUT.
       0100-DECL.
           EXIT.
       I-O-ERROR SECTION.
           USE AFTER STANDARD ERROR PROCEDURE ON I-O.
       0200-DECL.
           EXIT.
       OUTPUT-ERROR SECTION.
           USE AFTER STANDARD ERROR PROCEDURE ON OUTPUT.
       0300-DECL.
           EXIT.
       TRANSACTION-ERROR SECTION.
           USE AFTER STANDARD ERROR PROCEDURE ON TRANSACTION.
       0400-DECL.
           EXIT.
       END DECLARATIVES.
      *{TOTEM}END

       MAIN-LOGIC.
      *{TOTEM}ENTRY-BEFPRG
      *    Before-Program
           PERFORM PAS004P-Ev-Before-Program
      *{TOTEM}END
           PERFORM INITIALIZE-ROUTINE.
      * run main screen
      *{TOTEM}RUN-MAINSCR
           PERFORM Form1-OPEN-ROUTINE.
      *{TOTEM}END

      *{TOTEM}COPY-PROCEDURE
       EXIT-STOP-ROUTINE.
           PERFORM CLOSE-FILE-RTN
      * <TOTEM:EPT. INIT:tcodiva, INIT:tcodiva, BeforeDestroyResource>
      * <TOTEM:END>
           DESTROY Calibri14-Occidentale
           CALL "w$bitmap" USING WBITMAP-DESTROY, toolbar-bmp
           CALL "w$bitmap" USING WBITMAP-DESTROY, LOGO_PICCOLO-BMP
      *    After-Program
           PERFORM I-O-BLOCCO
           EXIT PROGRAM TOTEM-PgmStatus
           STOP RUN.

       INITIALIZE-ROUTINE.
      *    Before Init
      * initialize program status variable
           Initialize TOTEM-PgmStatus.
      * get system information
           ACCEPT SYSTEM-INFORMATION FROM SYSTEM-INFO.
      * get terminal information
           ACCEPT TERMINAL-ABILITIES FROM TERMINAL-INFO.
      * set font
           PERFORM INIT-FONT.
      * load bitmap
           PERFORM INIT-BMP.
      * load resource
           PERFORM INIT-RES.
      * create pop-up menu
           PERFORM INIT-POPUP.
      * open files
           PERFORM OPEN-FILE-RTN.
      *    After Init
           .
    
       INIT-FONT.
      * Calibri14-Occidentale
           INITIALIZE WFONT-DATA Calibri14-Occidentale
           MOVE 14 TO WFONT-SIZE
           MOVE "Calibri" TO WFONT-NAME
           SET WFCHARSET-DONT-CARE TO TRUE
           SET WFONT-BOLD TO FALSE
           SET WFONT-ITALIC TO FALSE
           SET WFONT-UNDERLINE TO FALSE
           SET WFONT-STRIKEOUT TO FALSE
           SET WFONT-FIXED-PITCH TO FALSE
           MOVE 0 TO WFONT-CHAR-SET
           CALL "W$FONT" USING WFONT-GET-FONT, 
                     Calibri14-Occidentale, WFONT-DATA
           .

       INIT-BMP.
      * TOOL-ESCI
           COPY RESOURCE "toolbar.bmp".
           CALL "w$bitmap" USING WBITMAP-LOAD "toolbar.bmp", 
                   GIVING toolbar-bmp.
      * Form1-Bt-1
           COPY RESOURCE "LOGO_PICCOLO.BMP".
           CALL "w$bitmap" USING WBITMAP-LOAD "LOGO_PICCOLO.BMP", 
                   GIVING LOGO_PICCOLO-BMP.
           .

       INIT-RES.
           .

       INIT-POPUP.
           .

       OPEN-FILE-RTN.
      *    Before Open
           PERFORM OPEN-codiva
      *    After Open
           .

       OPEN-codiva.
      * <TOTEM:EPT. INIT:tcodiva, FD:codiva, BeforeOpen>
      * <TOTEM:END>
           OPEN  I-O codiva
           IF STATUS-codiva = "35"
              OPEN OUTPUT codiva
                IF Valid-STATUS-codiva
                   CLOSE codiva
                   OPEN I-O codiva
                END-IF
           END-IF
           IF NOT Valid-STATUS-codiva
              PERFORM  Form1-EXTENDED-FILE-STATUS
              GO TO EXIT-STOP-ROUTINE
           END-IF
      * <TOTEM:EPT. INIT:tcodiva, FD:codiva, AfterOpen>
      * <TOTEM:END>
           .

       CLOSE-FILE-RTN.
      *    Before Close
           PERFORM CLOSE-codiva
      *    After Close
           .

       CLOSE-codiva.
      * <TOTEM:EPT. INIT:tcodiva, FD:codiva, BeforeClose>
      * <TOTEM:END>
           CLOSE codiva
           .

       DataSet1-codiva-INITSTART.
           EVALUATE DataSet1-KEYIS
           WHEN 1
              IF DataSet1-codiva-KEY1-Asc
                 MOVE Low-Value TO iva-chiave
              ELSE
                 MOVE High-Value TO iva-chiave
              END-IF
           END-EVALUATE
           .

       DataSet1-codiva-INITEND.
           EVALUATE DataSet1-KEYIS
           WHEN 1
              IF DataSet1-codiva-KEY1-Asc
                 MOVE High-Value TO iva-chiave
              ELSE
                 MOVE Low-Value TO iva-chiave
              END-IF
           END-EVALUATE
           .

       DataSet1-CHANGETO-KEY1.
           MOVE 1 TO DataSet1-KEYIS
           .   

       DataSet1-Change-CurrentKey-Asc.
           EVALUATE DataSet1-KEYIS
           WHEN 1
              MOVE "A" TO DataSet1-codiva-KEY1-ORDER
           END-EVALUATE
           .

       DataSet1-Change-CurrentKey-Desc.
           EVALUATE DataSet1-KEYIS
           WHEN 1
              MOVE "D" TO DataSet1-codiva-KEY1-ORDER
           END-EVALUATE
           .

      * codiva
       DataSet1-codiva-START.
           EVALUATE DataSet1-KEYIS
           WHEN 1
              IF DataSet1-codiva-KEY1-Asc
                 START codiva KEY >= iva-chiave
              ELSE
                 START codiva KEY <= iva-chiave
              END-IF
           END-EVALUATE
           .

       DataSet1-codiva-START-NOTGREATER.
           EVALUATE DataSet1-KEYIS
           WHEN 1
              IF DataSet1-codiva-KEY1-Asc
                 START codiva KEY <= iva-chiave
              ELSE
                 START codiva KEY >= iva-chiave
              END-IF
           END-EVALUATE
           .

       DataSet1-codiva-START-GREATER.
           EVALUATE DataSet1-KEYIS
           WHEN 1
              IF DataSet1-codiva-KEY1-Asc
                 START codiva KEY > iva-chiave
              ELSE
                 START codiva KEY < iva-chiave
              END-IF
           END-EVALUATE
           .

       DataSet1-codiva-START-LESS.
           EVALUATE DataSet1-KEYIS
           WHEN 1
              IF DataSet1-codiva-KEY1-Asc
                 START codiva KEY < iva-chiave
              ELSE
                 START codiva KEY > iva-chiave
              END-IF
           END-EVALUATE
           .

       DataSet1-codiva-Read.
      * <TOTEM:EPT. FD:DataSet1, FD:codiva, BeforeRead>
      * <TOTEM:END>
      * <TOTEM:EPT. FD:DataSet1, FD:codiva, BeforeReadRecord>
      * <TOTEM:END>
           EVALUATE DataSet1-KEYIS
           WHEN 1
              IF DataSet1-codiva-LOCK
                 READ codiva WITH LOCK 
                 KEY iva-chiave
              ELSE
                 READ codiva WITH NO LOCK 
                 KEY iva-chiave
              END-IF
           END-EVALUATE
           MOVE STATUS-codiva TO TOTEM-ERR-STAT 
           MOVE "codiva" TO TOTEM-ERR-FILE
           MOVE "READ" TO TOTEM-ERR-MODE
      * <TOTEM:EPT. FD:DataSet1, FD:codiva, AfterRead>
      * <TOTEM:END>
      * <TOTEM:EPT. FD:DataSet1, FD:codiva, AfterReadRecord>
      * <TOTEM:END>
           .

       DataSet1-codiva-Read-Next.
      * <TOTEM:EPT. FD:DataSet1, FD:codiva, BeforeRead>
      * <TOTEM:END>
      * <TOTEM:EPT. FD:DataSet1, FD:codiva, BeforeReadNext>
      * <TOTEM:END>
           EVALUATE DataSet1-KEYIS
           WHEN 1
              IF DataSet1-codiva-KEY1-Asc
                 IF DataSet1-codiva-LOCK
                    READ codiva NEXT WITH LOCK
                 ELSE
                    READ codiva NEXT WITH NO LOCK
                 END-IF
              ELSE
                 IF DataSet1-codiva-LOCK
                    READ codiva PREVIOUS WITH LOCK
                 ELSE
                    READ codiva PREVIOUS WITH NO LOCK
                 END-IF
              END-IF
           END-EVALUATE
           MOVE STATUS-codiva TO TOTEM-ERR-STAT
           MOVE "codiva" TO TOTEM-ERR-FILE
           MOVE "READ NEXT" TO TOTEM-ERR-MODE
      * <TOTEM:EPT. FD:DataSet1, FD:codiva, AfterRead>
      * <TOTEM:END>
      * <TOTEM:EPT. FD:DataSet1, FD:codiva, AfterReadNext>
      * <TOTEM:END>
           .

       DataSet1-codiva-Read-Prev.
      * <TOTEM:EPT. FD:DataSet1, FD:codiva, BeforeRead>
      * <TOTEM:END>
      * <TOTEM:EPT. FD:DataSet1, FD:codiva, BeforeReadPrev>
      * <TOTEM:END>
           EVALUATE DataSet1-KEYIS
           WHEN 1
              IF DataSet1-codiva-KEY1-Asc
                 IF DataSet1-codiva-LOCK
                    READ codiva PREVIOUS WITH LOCK
                 ELSE
                    READ codiva PREVIOUS WITH NO LOCK
                 END-IF
              ELSE
                 IF DataSet1-codiva-LOCK
                    READ codiva NEXT WITH LOCK
                 ELSE
                    READ codiva NEXT WITH NO LOCK
                 END-IF
              END-IF
           END-EVALUATE
           MOVE STATUS-codiva TO TOTEM-ERR-STAT
           MOVE "codiva" TO TOTEM-ERR-FILE
           MOVE "READ PREVIOUS" TO TOTEM-ERR-MODE
      * <TOTEM:EPT. FD:DataSet1, FD:codiva, AfterRead>
      * <TOTEM:END>
      * <TOTEM:EPT. FD:DataSet1, FD:codiva, AfterReadPrev>
      * <TOTEM:END>
           .

       DataSet1-codiva-Rec-Write.
      * <TOTEM:EPT. FD:DataSet1, FD:codiva, BeforeWrite>
      * <TOTEM:END>
           WRITE iva-rec OF codiva.
           MOVE STATUS-codiva TO TOTEM-ERR-STAT
           MOVE "codiva" TO TOTEM-ERR-FILE
           MOVE "WRITE" TO TOTEM-ERR-MODE
      * <TOTEM:EPT. FD:DataSet1, FD:codiva, AfterWrite>
      * <TOTEM:END>
           .

       DataSet1-codiva-Rec-Rewrite.
      * <TOTEM:EPT. FD:DataSet1, FD:codiva, BeforeRewrite>
      * <TOTEM:END>
           REWRITE iva-rec OF codiva.
           MOVE STATUS-codiva TO TOTEM-ERR-STAT
           MOVE "codiva" TO TOTEM-ERR-FILE
           MOVE "REWRITE" TO TOTEM-ERR-MODE
      * <TOTEM:EPT. FD:DataSet1, FD:codiva, AfterRewrite>
      * <TOTEM:END>
           .

       DataSet1-codiva-Rec-Delete.
      * <TOTEM:EPT. FD:DataSet1, FD:codiva, BeforeDelete>
      * <TOTEM:END>
           DELETE codiva.
           MOVE STATUS-codiva TO TOTEM-ERR-STAT
           MOVE "codiva" TO TOTEM-ERR-FILE
           MOVE "DELETE" TO TOTEM-ERR-MODE
      * <TOTEM:EPT. FD:DataSet1, FD:codiva, AfterDelete>
      * <TOTEM:END>
           .

       DataSet1-INIT-RECORD.
           INITIALIZE iva-rec OF codiva
           .


      * GRID
       form1-gd-1-Content.
      * CELLS' SETTING
              MODIFY form1-gd-1, X = 1, Y = 1,
                CELL-DATA = "Codice",
      * CELLS' SETTING
              MODIFY form1-gd-1, X = 2, Y = 1,
                CELL-DATA = "Descrizione",
      * CELLS' SETTING
              MODIFY form1-gd-1, X = 3, Y = 1,
                CELL-DATA = "Aliquota",
           .

      * FD's Initialize Paragraph
       DataSet1-codiva-INITREC.
           INITIALIZE iva-rec OF codiva
               REPLACING NUMERIC       DATA BY ZEROS
                         ALPHANUMERIC  DATA BY SPACES
                         ALPHABETIC    DATA BY SPACES
           .

      *
       DataSet1-DISPATCH-BUFTOFLD.
           EVALUATE TOTEM-Form-Index ALSO TOTEM-Frame-Index
              WHEN 1 ALSO 0
                  PERFORM Form1-Buf-To-Fld
           END-EVALUATE
           .

       Form1-Open-Routine.
           PERFORM Form1-Scrn
           PERFORM Form1-Proc
           .

       Form1-Scrn.
           PERFORM Form1-Create-Win
           PERFORM Form1-Init-Value
           PERFORM Form1-Init-Data
      * Tab keystrok settings
      * Tool Bar
           DISPLAY Form1-Tb-1
           PERFORM Form1-DISPLAY
           .

       Form1-Create-Win.
           Display Independent GRAPHICAL WINDOW
              SCREEN LINE 1,
              SCREEN COLUMN 0,
              LINES 24,30,
              SIZE 54,50,
              COLOR 131329,
              CONTROL FONT Calibri14-Occidentale,
              LINK TO THREAD,
              NO SCROLL,
              TITLE-BAR,
              TITLE titolo,
              AUTO-MINIMIZE,
              WITH SYSTEM MENU,
              USER-GRAY,
              USER-WHITE,
              No WRAP,
              EVENT PROCEDURE Form1-Event-Proc,
              HANDLE IS Form1-Handle,
      * <TOTEM:EPT. FORM:Form1, FORM:Form1, AfterCreateWin>
      * <TOTEM:END>


      * Tool Bar    
           DISPLAY TOOL-BAR 
              LINES 3,35,   
              CONTROL FONT IS Calibri14-Occidentale
              HANDLE IN Form1-Tb-1-Handle
           DISPLAY Form1-Tb-1 UPON Form1-Tb-1-Handle

      * Status-bar
           DISPLAY Form1 UPON Form1-Handle
      * DISPLAY-COLUMNS settings
              MODIFY form1-gd-1, DISPLAY-COLUMNS (1, 9, 43)
           .

       Form1-PROC.
      * <TOTEM:EPT. FORM:Form1, FORM:Form1, BeforeAccept>
           perform ABILITA-TOOLBAR.

           perform INTESTAZIONE.
           perform LOAD-RECORD.

           move 2  to event-data-2.
           perform SPOSTAMENTO.

           perform INIT.

           |specifico dei pgm. con grid-control
           perform ABILITAZIONI.

           .
      * <TOTEM:END>
           PERFORM UNTIL Exit-Pushed
              ACCEPT Form1
                 ON EXCEPTION
                    PERFORM Form1-Evaluate-Func
                 MOVE 1 TO TOTEM-Form-Index
              END-ACCEPT
      * <TOTEM:EPT. FORM:Form1, FORM:Form1, AfterEndAccept>
      * <TOTEM:END>
           END-PERFORM
      * <TOTEM:EPT. FORM:Form1, FORM:Form1, BeforeDestroyWindow>
      * <TOTEM:END>
           DESTROY Form1-Handle
           INITIALIZE Key-Status
           .

       Form1-Evaluate-Func.
      * <TOTEM:EPT. FORM:Form1, FORM:Form1, AfterAccept>
      *    per il bottone modifica
           if key-status = 5
              inquire tool-modifica, enabled in e-modifica
              if e-modifica = 1
                 if mod = zero
                    move 1    to mod
                 else 
                    move zero to mod
                 end-if
                 modify tool-modifica, value = mod
                 perform MODIFICA
              end-if
           end-if.

           .
      * <TOTEM:END>
           EVALUATE TRUE
              WHEN Exit-Pushed
                 PERFORM Form1-Exit
              WHEN Event-Occurred
                 IF Event-Type = Cmd-Close
                    PERFORM Form1-Exit
                 END-IF
              WHEN Key-Status = 2
                 PERFORM NUOVO-LinkTo
              WHEN Key-Status = 4
                 PERFORM CANCELLA-LinkTo
              WHEN Key-Status = 3
                 PERFORM TOOL-SALVA-LinkTo
              WHEN Key-Status = 1005
                 PERFORM TOOL-MODIFICA-LinkTo
              WHEN Key-Status = 8
                 PERFORM TOOL-CERCA-LinkTo
           END-EVALUATE
      * avoid changing focus
           MOVE 4 TO Accept-Control
           .

       Form1-CLEAR.
           PERFORM Form1-INIT-VALUE
           PERFORM Form1-DISPLAY
           .

       Form1-DISPLAY.
      * <TOTEM:EPT. FORM:Form1, FORM:Form1, BeforeDisplay>
      * <TOTEM:END>
           DISPLAY Form1-Tb-1
           DISPLAY Form1 UPON Form1-Handle
      * <TOTEM:EPT. FORM:Form1, FORM:Form1, AfterDisplay>
           SET LK-BL-SCRITTURA     TO TRUE.
           MOVE COMO-PROG-ID       TO LK-BL-PROG-ID.
           MOVE FORM1-HANDLE       TO LK-HND-WIN.
           CALL "BLOCKPGM"  USING LK-BLOCKPGM.
           CANCEL "BLOCKPGM".
           SET LK-BL-SCRITTURA     TO TRUE.
           MOVE COMO-PROG-ID       TO LK-BL-PROG-ID.
           MOVE FORM1-HANDLE       TO LK-HND-WIN.
           CALL "BLOCKPGM"  USING LK-BLOCKPGM.
           CANCEL "BLOCKPGM".

           .
      * <TOTEM:END>
           .

       Form1-Exit.
      * for main screen
      * <TOTEM:EPT. FORM:Form1, FORM:Form1, BeforeExit>
           perform SALV-MOD.
           if errori
              move 28 to key-status
              exit paragraph
           end-if.

           .
      * <TOTEM:END>
           MOVE 27 TO Key-Status
           .

       Form1-Init-Data.
           MOVE 1 TO TOTEM-Form-Index
           MOVE 0 TO TOTEM-Frame-Index
      * GRID
           PERFORM form1-gd-1-Content
           .

       Form1-DataSet1-CHANGETO-KEY1.
           MOVE 1 TO DataSet1-KEYIS
           PERFORM Form1-DataSet1-Update-Key
           .

       Form1-DataSet1-Change-CurrentKey-Asc.
           EVALUATE DataSet1-KEYIS
           WHEN 1
              MOVE "A" TO DataSet1-codiva-KEY1-ORDER
           END-EVALUATE
           PERFORM Form1-DataSet1-Update-Key
           .

       Form1-DataSet1-Change-CurrentKey-Desc.
           EVALUATE DataSet1-KEYIS
           WHEN 1
              MOVE "D" TO DataSet1-codiva-KEY1-ORDER
           END-EVALUATE
           PERFORM Form1-DataSet1-Update-Key
           .

       Form1-DataSet1-Update-Key.
           MOVE iva-rec OF codiva TO
                     Form1-MULKEY-TMPBUF
           PERFORM Form1-CLEAR
           PERFORM Form1-INIT-DATA
           MOVE Form1-MULKEY-TMPBUF TO
                     iva-rec OF codiva
           PERFORM DataSet1-codiva-Read
           PERFORM Form1-DUPLICATE-MOVEKEY
           PERFORM Form1-DUMMY-CURR
           PERFORM Form1-IUD-Display
           .

       Form1-DUPLICATE-MOVEKEY.
           .

       Form1-First.
           PERFORM Form1-DUMMY-FIRST
           PERFORM DataSet1-codiva-INITSTART
           PERFORM DataSet1-codiva-START
           IF NOT Valid-STATUS-codiva
              PERFORM Form1-Extended-File-Status
              EXIT PARAGRAPH
           END-IF
      * <TOTEM:EPT. FORM:Form1, FORM:Form1, BeforeFirst>
      * <TOTEM:END>
           PERFORM DataSet1-codiva-Read-Next
           IF NOT Valid-STATUS-codiva
              PERFORM Form1-Extended-File-Status
              EXIT PARAGRAPH
           END-IF
      * <TOTEM:EPT. FORM:Form1, FORM:Form1, AfterFirst>
      * <TOTEM:END>
           PERFORM Form1-DUPLICATE-MOVEKEY.
           PERFORM Form1-IUD-Display
           .

       Form1-Previous.
              PERFORM Form1-Buf-To-Fld
              PERFORM DataSet1-codiva-START-LESS
           IF NOT Valid-STATUS-codiva
              PERFORM Form1-Extended-File-Status
              EXIT PARAGRAPH
           END-IF
      * <TOTEM:EPT. FORM:Form1, FORM:Form1, BeforePrevious>
      * <TOTEM:END>
           PERFORM DataSet1-codiva-Read-Prev
           IF NOT Valid-STATUS-codiva
              PERFORM Form1-Extended-File-Status
              EXIT PARAGRAPH
           END-IF
      * <TOTEM:EPT. FORM:Form1, FORM:Form1, AfterPrevious>
      * <TOTEM:END>
           PERFORM Form1-DUPLICATE-MOVEKEY
           PERFORM Form1-DUMMY-PREVIOUS
           PERFORM Form1-IUD-Display
           .

       Form1-Next.
              PERFORM Form1-Buf-To-Fld
              PERFORM DataSet1-codiva-START-GREATER
           IF NOT Valid-STATUS-codiva
              PERFORM Form1-Extended-File-Status
              EXIT PARAGRAPH
           END-IF
      * <TOTEM:EPT. FORM:Form1, FORM:Form1, BeforeNext>
      * <TOTEM:END>
           PERFORM DataSet1-codiva-Read-Next
           IF NOT Valid-STATUS-codiva
              PERFORM Form1-Extended-File-Status
              EXIT PARAGRAPH
           END-IF
      * <TOTEM:EPT. FORM:Form1, FORM:Form1, AfterNext>
      * <TOTEM:END>
           PERFORM Form1-DUPLICATE-MOVEKEY
           PERFORM Form1-DUMMY-NEXT
           PERFORM Form1-IUD-Display
           .
      
       Form1-Last.
           PERFORM Form1-DUMMY-LAST
           PERFORM DataSet1-codiva-INITEND
           PERFORM DataSet1-codiva-START-NOTGREATER
           IF NOT Valid-STATUS-codiva
              PERFORM Form1-Extended-File-Status
              EXIT PARAGRAPH
           END-IF
      * <TOTEM:EPT. FORM:Form1, FORM:Form1, BeforeLast>
      * <TOTEM:END>
           PERFORM DataSet1-codiva-Read-Prev
           IF NOT Valid-STATUS-codiva
              PERFORM Form1-Extended-File-Status
              EXIT PARAGRAPH
           END-IF
      * <TOTEM:EPT. FORM:Form1, FORM:Form1, AfterLast>
      * <TOTEM:END>
           PERFORM Form1-DUPLICATE-MOVEKEY.
           PERFORM Form1-IUD-Display
           .

       Form1-Curr.
      * <TOTEM:EPT. FORM:Form1, FORM:Form1, BeforeCurrent>
      * <TOTEM:END>
           PERFORM Form1-Buf-To-Fld
           PERFORM DataSet1-codiva-Read
           PERFORM Form1-DUPLICATE-MOVEKEY
           PERFORM Form1-DUMMY-CURR
           PERFORM Form1-IUD-Display
      * <TOTEM:EPT. FORM:Form1, FORM:Form1, AfterCurrent>
      * <TOTEM:END>
           .

       Form1-IUD-Display.
           IF Valid-STATUS-codiva
              PERFORM Form1-ALLGRID-RESET
              PERFORM Form1-Fld-To-Buf
              PERFORM Form1-NAVI-FOR-MASTERGRID
              PERFORM Form1-DISPLAY
           ELSE
              IF Form1-FLAG-REFRESH
                 CONTINUE
              ELSE
                 PERFORM Form1-Extended-File-Status
              END-IF
           END-IF
           .

       Form1-Add.
           PERFORM Form1-Buf-To-Fld
           PERFORM Form1-VALIDATION-ROUTINE
           IF NOT TOTEM-CHECK-OK
               EXIT PARAGRAPH
           END-IF
           PERFORM Form1-DUMMY-ADD
           PERFORM DataSet1-codiva-INITREC
           PERFORM Form1-Buf-To-Fld
           MOVE SPACES TO TOTEM-TRANSACTION-FLAG
      * <TOTEM:EPT. FORM:Form1, FORM:Form1, BeforeAdd>
      * <TOTEM:END>
      * write
           PERFORM DataSet1-codiva-Rec-Write
           IF Valid-STATUS-codiva
              PERFORM Form1-RESUMMARY-INS
              PERFORM Form1-DUMMY-UPDATE-INIT
              MOVE "301" TO TOTEM-MSG-ID
              PERFORM Form1-IUD-Display
           END-IF
           PERFORM Form1-ERR-CHECKING
      * <TOTEM:EPT. FORM:Form1, FORM:Form1, AfterAdd>
      * <TOTEM:END>
           .
     
       Form1-Update.
           PERFORM Form1-Buf-To-Fld
           PERFORM DataSet1-codiva-START              
           IF NOT Valid-STATUS-codiva
              PERFORM Form1-Extended-File-Status
              EXIT PARAGRAPH
           END-IF
           PERFORM DataSet1-codiva-Read
           PERFORM Form1-Buf-To-Fld
           PERFORM Form1-VALIDATION-ROUTINE
           IF NOT TOTEM-CHECK-OK
               EXIT PARAGRAPH
           END-IF
           PERFORM Form1-DUMMY-UPDATE
           PERFORM Form1-Buf-To-Fld
           MOVE SPACES TO TOTEM-TRANSACTION-FLAG
      * <TOTEM:EPT. FORM:Form1, FORM:Form1, BeforeUpdate>
      * <TOTEM:END>
      * write
           PERFORM DataSet1-codiva-Rec-Rewrite
           IF Valid-STATUS-codiva
              PERFORM Form1-RESUMMARY-DEL
              PERFORM Form1-DUMMY-UPDATE-INIT
              MOVE "302" TO TOTEM-MSG-ID
              PERFORM Form1-IUD-Display
           END-IF
           PERFORM Form1-ERR-CHECKING
      * <TOTEM:EPT. FORM:Form1, FORM:Form1, AfterUpdate>
      * <TOTEM:END>
           .

       Form1-Delete.
           MOVE "203" TO TOTEM-MSG-ID
           PERFORM MESSAGE-BOX-DISPLAY
           IF TOTEM-MSG-RETURN-VALUE NOT = 1
              INITIALIZE TOTEM-MSG-TEXT
              EXIT PARAGRAPH 
           END-IF
           MOVE SPACES TO TOTEM-TRANSACTION-FLAG
      * <TOTEM:EPT. FORM:Form1, FORM:Form1, BeforeDelete>
      * <TOTEM:END>
           PERFORM Form1-DUMMY-DELETE
      * delete
           PERFORM Form1-Buf-To-Fld
           PERFORM DataSet1-codiva-Rec-Delete
           IF Valid-STATUS-codiva
              PERFORM Form1-CLEAR
              PERFORM Form1-DUMMY-DELETE-INIT
              MOVE "303" TO TOTEM-MSG-ID
              MOVE "00" to STATUS-codiva
           END-IF
      * <TOTEM:EPT. FORM:Form1, FORM:Form1, AfterDelete>
      * <TOTEM:END>
           PERFORM Form1-ERR-CHECKING
           .

       Form1-NAVI-FOR-MASTERGRID.
           .

       Form1-ERR-CHECKING.
           IF Valid-STATUS-codiva
              PERFORM Form1-SHOW-MSG-ROUTINE
           ELSE
              PERFORM Form1-Extended-File-Status
           END-IF
           .

       Form1-RESUMMARY-INS.
           .

       Form1-RESUMMARY-DEL.
           .


       Form1-DUMMY-FIRST.
           .

       Form1-DUMMY-PREVIOUS.
           .

       Form1-DUMMY-NEXT.
           .

       Form1-DUMMY-LAST.
           .

       Form1-DUMMY-CURR.
           .

       Form1-DUMMY-ADD.
           .

       Form1-DUMMY-UPDATE.
           .

       Form1-DUMMY-UPDATE-INIT.
           .

       Form1-DUMMY-DELETE.
           .

       Form1-DUMMY-DELETE-INIT.
           .

       Form1-Init-Value.
           MOVE titolo TO TOTEM-MSG-TITLE
      * FORM : Form1
           PERFORM DataSet1-INIT-RECORD
      * <TOTEM:EPT. FORM:Form1, FORM:Form1, SetDefault>
      * <TOTEM:END>
           PERFORM Form1-FLD-TO-BUF
           .


       Form1-ALLGRID-RESET.
           .

      * for Form's Validation
       Form1-VALIDATION-ROUTINE.
           SET TOTEM-CHECK-OK TO TRUE
           .


       Form1-Buf-To-Fld.
      * <TOTEM:EPT. FORM:Form1, FORM:Form1, BeforeBufToFld>
      * <TOTEM:END>
      * <TOTEM:EPT. FORM:Form1, FORM:Form1, AfterBufToFld>
      * <TOTEM:END>
           .

       Form1-Fld-To-Buf.
      * <TOTEM:EPT. FORM:Form1, FORM:Form1, BeforeFldToBuf>
           set SiSalvato to true.

           .
      * <TOTEM:END>
      * <TOTEM:EPT. FORM:Form1, FORM:Form1, AfterFldToBuf>
      * <TOTEM:END>
           .

       Form1-CONTROLLO-OLD.
           set SiSalvato to true.
           if mod = 0 exit paragraph end-if.
           perform Form1-BUF-TO-FLD.
           move 0 to scelta.
           .
       Form1-EXTENDED-FILE-STATUS.
           CALL "C$RERRNAME" USING TOTEM-MSG-ERR-FILE
           CALL "C$RERR" USING EXTEND-STAT, TEXT-MESSAGE
           MOVE PRIMARY-ERROR TO TOTEM-MSG-ID
           PERFORM Form1-SHOW-MSG-ROUTINE
           .

       Form1-SHOW-MSG-ROUTINE.
           PERFORM SHOW-MSG-ROUTINE
           PERFORM Form1-DISPLAY-MESSAGE
           .

       Form1-DISPLAY-MESSAGE.
           PERFORM MESSAGE-BOX-ROUTINE
           DISPLAY MESSAGE BOX TOTEM-MSG-TEXT
               TITLE IS TOTEM-MSG-TITLE
               TYPE  IS TOTEM-MSG-BUTTON-TYPE
               ICON  IS TOTEM-MSG-DEFAULT-BUTTON
               RETURNING TOTEM-MSG-RETURN-VALUE
           .

       Form1-Save-Status.
           MOVE DataSet1-codiva-KEY1-ORDER TO TMP-Form1-KEY1-ORDER
           MOVE DataSet1-KEYIS TO TMP-Form1-KEYIS
           MOVE iva-rec OF codiva TO 
              TMP-Form1-codiva-RESTOREBUF
           .             

       Form1-Restore-Status.
           MOVE TMP-Form1-KEY1-ORDER TO DataSet1-codiva-KEY1-ORDER
           MOVE TMP-Form1-KEYIS TO DataSet1-KEYIS
           MOVE TMP-Form1-codiva-RESTOREBUF TO
              iva-rec OF codiva
           PERFORM DataSet1-codiva-START
           IF Valid-STATUS-codiva
              PERFORM DataSet1-codiva-Read-Next
           ELSE
              PERFORM DataSet1-codiva-INITREC
           END-IF
           PERFORM UNTIL NOT Valid-STATUS-codiva OR
              (Valid-STATUS-codiva AND
                 iva-rec OF codiva = 
                   TMP-Form1-codiva-RESTOREBUF)
              PERFORM DataSet1-codiva-Read-Next
           END-PERFORM
           .



       Form1-Event-Proc.
           .

       Form1-Gd-1-Event-Proc.
           EVALUATE Event-Type ALSO Event-Control-Id ALSO
                                    Event-Window-Handle
           WHEN Msg-Begin-Drag ALSO 1 ALSO
                    Form1-Handle 
              PERFORM form1-gd-1-Ev-Msg-Begin-Drag
           WHEN Msg-Begin-Entry ALSO 1 ALSO
                    Form1-Handle 
              PERFORM form1-gd-1-Ev-Msg-Begin-Entry
           WHEN Msg-End-Drag ALSO 1 ALSO
                    Form1-Handle 
              PERFORM form1-gd-1-Ev-Msg-End-Drag
           WHEN Msg-Finish-Entry ALSO 1 ALSO
                    Form1-Handle 
              PERFORM form1-gd-1-Ev-Msg-Finish-Entry
           WHEN Msg-Goto-Cell ALSO 1 ALSO
                    Form1-Handle 
              PERFORM form1-gd-1-Ev-Msg-Goto-Cell
           WHEN Msg-Goto-Cell-Drag ALSO 1 ALSO
                    Form1-Handle 
              PERFORM form1-gd-1-Ev-Msg-Goto-Cell-Drag
           WHEN Msg-Goto-Cell-Mouse ALSO 1 ALSO
                    Form1-Handle 
              PERFORM form1-gd-1-Ev-Msg-Goto-Cell-Mouse
           END-EVALUATE
           .

      * USER DEFINE PARAGRAPH
       ABILITAZIONI.
      * <TOTEM:PARA. ABILITAZIONI>
           if mod = 1
              move BitmapDeleteEnabled to BitmapNumDelete
              move BitmapSaveEnabled   to BitmapNumSave
              move 1 to e-salva e-cancella
           else
              |se sono in visua           
              move BitmapDeleteDisabled to BitmapNumDelete
              move BitmapSaveDisabled   to BitmapNumSave
              move 0 to e-salva e-cancella
           end-if.     

      ****** ISACCO (CORREZIONE SU LIVELLO ABILITAZIONE 2) - 10/11/2003
      ****** (CANCELLAZIONE NON PERMESSA)
      *****     if livello-abil = 2 
      *****        move ZERO to e-cancella
      *****        move BitmapDeleteDisabled to BitmapNumDelete
      *****     end-if.
      ****** FINE

           modify tool-cancella, enabled = e-cancella.
           modify tool-salva,    enabled = e-salva.
       
      * ISACCO (SERVE SEMPRE PER LA MODIFICA PRCEDENTE E PER RIPRISTINARE
      * LE BITMAP DISABILITATE. - 10/11/2003
      *     perform FORM1-DISPLAY.
           display tool-nuovo, tool-salva, tool-cancella, tool-modifica.
      * FINE 
           .
      * <TOTEM:END>

       ANTEPRIMA.
      * <TOTEM:PARA. ANTEPRIMA>
           set anteprima       to true.
      *     perform paragrafo-stampa 
           .
      * <TOTEM:END>

       CANCELLA.
      * <TOTEM:PARA. CANCELLA>
      * <TOTEM:PARA. CANCELLA>
      *--->modifica (isacco)
           if mod = 0 exit paragraph end-if.
      *--->fine.                 

           display message box MSG-cancellare-il-record-corrente
                   title = titolo
                   type mb-yes-no
                   default mb-no
                   giving scelta.

           if scelta = mb-yes

              inquire form1-gd-1, cursor-y in riga
              perform VALORE-RIGA

              delete codiva record invalid continue end-delete

              modify  form1-gd-1, record-to-delete = riga
              inquire form1-gd-1, last-row in tot-righe
              if riga > tot-righe move tot-righe to riga end-if
              modify form1-gd-1, cursor-y = riga, cursor-x = 1
              move riga to event-data-2
              perform COLORE-RIGA
              display message MSG-cancellazione-avvenuta-con-successo
                        title titolo
           end-if 
           .
      * <TOTEM:END>

       CERCA.
      * <TOTEM:PARA. CERCA>
           continue 
           .
      * <TOTEM:END>

       COLORE-RIGA.
      * <TOTEM:PARA. COLORE-RIGA>
           if riga < 2 
              move 2 to riga 
           end-if.

           modify form1-gd-1, start-x = 1, x     = 3,
                                  start-y = riga,
                                        y = riga,
                                  region-color 257,
                                  cursor-color 481 
           .
      * <TOTEM:END>

       CONTROLLO.
      * <TOTEM:PARA. CONTROLLO>
           set tutto-ok to true.

           inquire form1-gd-1, cursor-y in riga.

           perform VALORE-RIGA.

           evaluate colonna
           when 1
                if nuovo
                   if iva-codice = zero or spaces 
                      set errori to true
                      move 1     to colonna
                      display message box MSG-Codice-obbligatorio
                              title = tit-err
                              icon mb-warning-icon
                   else  
                      read codiva
                           not invalid
                               set errori to true
                               display message MGS-codice-gia-inserito|"Codice già inserito!"
                                       title = tit-err
                                       icon mb-warning-icon
                      end-read
                   end-if
                end-if
           when 2
                if iva-descrizione = spaces
                   set errori to true
                   move 2 to colonna
                   display message box MSG-Descrizione-mancante|"Descrizione mancante"
                           title = tit-err
                           icon mb-warning-icon
                end-if

           end-evaluate.

           if errori
              modify form1-gd-1, cursor-y = riga, cursor-x = colonna
              move riga    to event-data-2
              move colonna to event-data-1
           end-if 
           .
      * <TOTEM:END>

       INIT.
      * <TOTEM:PARA. INIT>
           set vecchio  to true.
           set tutto-ok to true 
           .
      * <TOTEM:END>

       INTESTAZIONE.
      * <TOTEM:PARA. INTESTAZIONE>
           modify form1-gd-1(1, 1), cell-data = "Codice".
           modify form1-gd-1(1, 2), cell-data = "Descrizione".
           modify form1-gd-1(1, 3), cell-data = "Aliquota" 
           .
      * <TOTEM:END>

       LOAD-RECORD.
      * <TOTEM:PARA. LOAD-RECORD>
           modify form1-gd-1, mass-update = 1.
           move low-value to iva-codice.
           start codiva key is >= iva-chiave
                  invalid continue
              not invalid
                  perform varying riga from 2 by 1
                          until 1 = 2
                     read codiva next
                          at end exit perform
                      not at end
                          move iva-codice      to col-codice
                          move iva-descrizione to col-des
                          move iva-aliquota    to col-aliquota
                          modify form1-gd-1(riga, 1), cell-data 
           col-codice
                          modify form1-gd-1(riga, 2), cell-data col-des
                          modify form1-gd-1(riga, 3), cell-data 
           col-aliquota
                     end-read                                           
                  end-perform
           end-start.
           modify form1-gd-1, mass-update = 0 
           .
      * <TOTEM:END>

       MODIFICA.
      * <TOTEM:PARA. MODIFICA>
           inquire tool-modifica, value in mod.

      *--->modifica (isacco)
           if nuovo 
              move 1 to mod 
           else
              |specifico per i pgm. con grid-control
              if mod = 1
                 close codiva
                 open i-o codiva allowing readers
              else
                 set tutto-ok to true
                 if NoSalvato
                    move 1 to mod
                    perform SALV-MOD
                 end-if   
                 if tutto-ok
                    move 0 to mod
                    close codiva
                    open input codiva

      *             | specifico x le tabelle.
                    | fa in modo che resto sulla cella in cui ero
                    if ricarica
                       set ricarica to false
                       modify form1-gd-1, reset-grid = 1
                       perform INTESTAZIONE
                       perform LOAD-RECORD
                    end-if

                 else
                    move 1 to mod
                 end-if
              end-if
           end-if.

           perform ABILITAZIONI.

           modify tool-modifica, value mod 
           .
      * <TOTEM:END>

       NUOVO.
      * <TOTEM:PARA. NUOVO>
           set tutto-ok to true.

           if nuovo
              perform VALORE-RIGA
              if iva-codice not = SPACES
                 perform SALVA
              else
                 set errori to true
              end-if
           end-if.

           if tutto-ok
              set nuovo to true
              inquire form1-gd-1,  last-row in tot-righe
              modify  form1-gd-1,  insert-rows = 1
              modify  form1-gd-1,  cursor-x    = 1 
                                   cursor-y    = tot-righe + 1
              move 1 to mod
              modify  tool-modifica,   value = mod

              add 1 to tot-righe giving riga

              perform ABILITAZIONI

              initialize old-iva-rec replacing numeric data by zeroes
                                          alphanumeric data by spaces
              add 1 to tot-righe giving event-data-2
              perform COLORE-RIGA
           end-if 
           .
      * <TOTEM:END>

       PARAGRAFO-COPY.
      * <TOTEM:PARA. PARAGRAFO-COPY>
           copy "abilita-toolbar.cpy".
           copy "color-custom.cpy"    
           .
      * <TOTEM:END>

       SALV-MOD.
      * <TOTEM:PARA. SALV-MOD>
           if nuovo
              perform VALORE-RIGA
              if iva-rec not = old-iva-rec
                 set NoSalvato to true
              else
                 set SiSalvato to true
              end-if
           end-if.

           set tutto-ok to true.
           if NoSalvato
              display message box MSG-Salvare-le-modifiche, 
                             title = titolo
                             type = mb-yes-no-cancel
                             giving scelta

              evaluate scelta
              when mb-yes    perform SALVA
              when mb-cancel set errori    to true
              when mb-no     set tutto-ok  to true
                             set SiSalvato to true
                             set ricarica  to true
              end-evaluate

           end-if 
           .
      * <TOTEM:END>

       SALVA.
      * <TOTEM:PARA. SALVA>
           if sisalvato or mod = 0 exit paragraph end-if.

           inquire form1-gd-1, cursor-x in colonna, 
                               cursor-y in riga.

           perform varying colonna from 1 by 1
                     until colonna > 2
              perform CONTROLLO
              if errori exit perform end-if
           end-perform.

           if tutto-ok
              write iva-rec
                    invalid rewrite iva-rec
              end-write

              set sisalvato to true
              set vecchio   to true
           else
              perform ABILITAZIONI
           end-if 
            
           .
      * <TOTEM:END>

       SPOSTAMENTO.
      * <TOTEM:PARA. SPOSTAMENTO>
           inquire form1-gd-1, cursor-x = colonna, cursor-y = riga.

           if event-data-2 not = riga
              perform VALORE-RIGA
              if iva-codice = spaces or zero
                 modify form1-gd-1, record-to-delete riga
                 set vecchio to true
              else  
                 perform SALVA
                 if errori
                    move riga    to event-data-2
                    move colonna to event-data-1 | (isacco)
                    set event-action to event-action-fail
                 end-if
              end-if
           else
              if colonna not = event-data-1
                 perform CONTROLLO
                 if errori
                    set event-action to event-action-fail
                 end-if
              end-if
           end-if.

      * VALORIZZO L'OLD DELLA RIGA SU CUI SONO ANDATO
           move event-data-2 to riga.
           move event-data-1 to colonna.
           perform VALORE-OLD-RIGA.

      * COLORAZIONE RIGA IN GRID
           perform COLORE-RIGA 
           .
      * <TOTEM:END>

       STAMPA.
      * <TOTEM:PARA. STAMPA>
           set stampa       to true.
      *     perform paragrafo-stampa 
           .
      * <TOTEM:END>

       VALORE-RIGA.
      * <TOTEM:PARA. VALORE-RIGA>
           inquire form1-gd-1(riga, 1), cell-data iva-codice.
           inquire form1-gd-1(riga, 2), cell-data iva-descrizione. 
           inquire form1-gd-1(riga, 3), cell-data iva-aliquota  
           .
      * <TOTEM:END>

       VALORE-OLD-RIGA.
      * <TOTEM:PARA. VALORE-OLD-RIGA>
           if vecchio
              inquire form1-gd-1(riga, 1) cell-data old-iva-codice
              move old-iva-codice         to iva-codice
              read codiva                 no lock
              move iva-rec                to old-iva-rec
           else
              initialize old-iva-rec replacing numeric data by zeroes
                                          alphanumeric data by spaces
           end-if 

           .
      * <TOTEM:END>

      * EVENT PARAGRAPH
       NUOVO-LinkTo.
      * <TOTEM:PARA. NUOVO-LinkTo>
           inquire tool-nuovo, enabled in e-nuovo.
           if e-nuovo = 1
              perform NUOVO
           end-if 

           .
      * <TOTEM:END>
       CANCELLA-LinkTo.
      * <TOTEM:PARA. CANCELLA-LinkTo>
           inquire tool-cancella, enabled in e-cancella.
           if e-cancella = 1
              perform CANCELLA
           end-if 
           .
      * <TOTEM:END>
       TOOL-SALVA-LinkTo.
      * <TOTEM:PARA. TOOL-SALVA-LinkTo>
           inquire tool-salva, enabled in e-salva.
           if e-salva = 1
              perform salva
           end-if 
           .
      * <TOTEM:END>
       TOOL-MODIFICA-LinkTo.
      * <TOTEM:PARA. TOOL-MODIFICA-LinkTo>
           inquire tool-modifica, enabled in e-modifica
           if e-modifica = 1
              perform MODIFICA
           end-if 
           .
      * <TOTEM:END>
       I-O-BLOCCO.
      * <TOTEM:PARA. I-O-BLOCCO>
           SET LK-BL-CANCELLAZIONE TO TRUE.
           MOVE COMO-PROG-ID       TO LK-BL-PROG-ID.
           CALL "BLOCKPGM"  USING LK-BLOCKPGM 
           .
      * <TOTEM:END>
       PAS004P-Ev-Before-Program.
      * <TOTEM:PARA. PAS004P-Ev-Before-Program>
           move LK-BL-PROG-ID    TO COMO-PROG-ID 
           .
      * <TOTEM:END>
       form1-gd-1-Ev-Msg-Finish-Entry.
      * <TOTEM:PARA. form1-gd-1-Ev-Msg-Finish-Entry>
           inquire form1-gd-1, cursor-y in riga.
           perform VALORE-RIGA.

           inquire form1-gd-1(riga, 3), cell-data col-aliquota.
           modify  form1-gd-1(riga, 3), cell-data col-aliquota.

           set environment "KEYSTROKE" to "DATA=44 44".
           set environment "KEYSTROKE" to "DATA=46 46".

           perform  CONTROLLO.

           if errori 
              set event-action to event-action-fail 
              perform VALORE-RIGA
           end-if.

           if iva-rec not = old-iva-rec
              set NoSalvato to true                            
           else 
              set SiSalvato to true
           end-if 
           .
      * <TOTEM:END>
       form1-gd-1-Ev-Msg-Begin-Entry.
      * <TOTEM:PARA. form1-gd-1-Ev-Msg-Begin-Entry>
           inquire form1-gd-1, cursor-x = colonna,
                                   cursor-y in riga.
                         
           perform VALORE-RIGA.

           if colonna = 1
              if iva-codice not = zero and iva-codice not = spaces
                 set event-action to event-action-fail
              end-if
           else 
              if mod = 0
                 set event-action to event-action-fail
              else
                 if iva-codice = zero or spaces
                    set event-action to event-action-fail
                    modify form1-gd-1, cursor-y = riga, cursor-x = 1
                 else
                    if colonna = 3           
                       set environment "KEYSTROKE" to "DATA=44 46"
                    end-if
                 end-if   
              end-if
           end-if 
           .
      * <TOTEM:END>
       form1-gd-1-Ev-Msg-End-Drag.
      * <TOTEM:PARA. form1-gd-1-Ev-Msg-End-Drag>
           perform SPOSTAMENTO 
           .
      * <TOTEM:END>
       form1-gd-1-Ev-Msg-Goto-Cell.
      * <TOTEM:PARA. form1-gd-1-Ev-Msg-Goto-Cell>
           perform SPOSTAMENTO 
           .
      * <TOTEM:END>
       form1-gd-1-Ev-Msg-Goto-Cell-Drag.
      * <TOTEM:PARA. form1-gd-1-Ev-Msg-Goto-Cell-Drag>
           perform SPOSTAMENTO 
           .
      * <TOTEM:END>
       form1-gd-1-Ev-Msg-Goto-Cell-Mouse.
      * <TOTEM:PARA. form1-gd-1-Ev-Msg-Goto-Cell-Mouse>
           perform SPOSTAMENTO 
           .
      * <TOTEM:END>
       form1-gd-1-Ev-Msg-Begin-Drag.
      * <TOTEM:PARA. form1-gd-1-Ev-Msg-Begin-Drag>
           perform SPOSTAMENTO 
           .
      * <TOTEM:END>
       TOOL-MODIFICA-BeforeProcedure.
      * <TOTEM:PARA. TOOL-MODIFICA-BeforeProcedure>
           .
      * <TOTEM:END>
       TOOL-MODIFICA-AfterProcedure.
      * <TOTEM:PARA. TOOL-MODIFICA-AfterProcedure>
           .
      * <TOTEM:END>
       TOOL-CERCA-LinkTo.
      * <TOTEM:PARA. TOOL-CERCA-LinkTo>
           .
      * <TOTEM:END>

      *{TOTEM}END

      *{TOTEM}SHOW-MSG
       MESSAGE-FOR-FILEERROR.
           CALL "C$RERRNAME" USING TOTEM-MSG-ERR-FILE
           CALL "C$RERR" USING EXTEND-STAT, TEXT-MESSAGE
              MOVE PRIMARY-ERROR TO TOTEM-MSG-ID
           .

       SHOW-TRANSACTION-ROUTINE.
           IF TOTEM-TRANSACTION-FLAG = SPACES
              IF TRANSACTION-STATUS NOT = 0
                 STRING "TRANSACTION ERROR ", TRANSACTION-STATUS
                    DELIMITED BY SIZE INTO TOTEM-MSG-1
              END-IF
           ELSE
              PERFORM SHOW-MSG-ROUTINE
              IF TRANSACTION-STATUS = 0
                 MOVE "Transazione terminata con Rollback." TO 
           TOTEM-MSG-3
              ELSE
                 STRING "TRANSACTION ERROR ", TRANSACTION-STATUS
                    DELIMITED BY SIZE INTO TOTEM-MSG-3
              END-IF
           END-IF
           .

       SHOW-MSG-ROUTINE.
           MOVE SPACE TO TOTEM-MSG-1 TOTEM-MSG-2 TOTEM-MSG-3
           EVALUATE TOTEM-MSG-ID
               WHEN "10"
                    STRING "File:" TOTEM-MSG-ERR-FILE DELIMITED BY SPACE
                       INTO TOTEM-MSG-1
                    MOVE "Nessun altro dato." TO TOTEM-MSG-2
                    MOVE MB-DEFAULT-ICON TO TOTEM-MSG-ICON-TYPE
                    MOVE MB-OK TO TOTEM-MSG-BUTTON-TYPE
               WHEN "22"
                    STRING "File:" TOTEM-MSG-ERR-FILE DELIMITED BY SPACE
                       INTO TOTEM-MSG-1
                    MOVE "Chiave Duplicata." TO TOTEM-MSG-2
                    MOVE MB-ERROR-ICON TO TOTEM-MSG-ICON-TYPE
                    MOVE MB-OK TO TOTEM-MSG-BUTTON-TYPE
               WHEN "23"
                    STRING "File:" TOTEM-MSG-ERR-FILE DELIMITED BY SPACE
                       INTO TOTEM-MSG-1
                    MOVE "Raggiunta fine file." TO TOTEM-MSG-2
                    MOVE MB-WARNING-ICON TO TOTEM-MSG-ICON-TYPE
                    MOVE MB-OK TO TOTEM-MSG-BUTTON-TYPE
               WHEN "101"
                    MOVE "Terminare l'applicazione?" TO TOTEM-MSG-1
                    MOVE 4 TO TOTEM-MSG-ICON-TYPE
                    MOVE MB-YES-NO TO TOTEM-MSG-BUTTON-TYPE
               WHEN "201"
                    MOVE "Aggiungere un nuovo record?" TO TOTEM-MSG-1
                    MOVE 4 TO TOTEM-MSG-ICON-TYPE
                    MOVE MB-YES-NO TO TOTEM-MSG-BUTTON-TYPE
               WHEN "202"
                    MOVE "Aggiornare il Record?" TO TOTEM-MSG-1
                    MOVE 4 TO TOTEM-MSG-ICON-TYPE
                    MOVE MB-YES-NO TO TOTEM-MSG-BUTTON-TYPE
               WHEN "203"
                    MOVE "Cancellare il Record?" TO TOTEM-MSG-1
                    MOVE 4 TO TOTEM-MSG-ICON-TYPE
                    MOVE MB-YES-NO TO TOTEM-MSG-BUTTON-TYPE
               WHEN "204"
                    MOVE "Chiave duplicata." TO TOTEM-MSG-1
                    MOVE MB-WARNING-ICON TO TOTEM-MSG-ICON-TYPE
                    MOVE MB-OK TO TOTEM-MSG-BUTTON-TYPE
               WHEN "301"
                    MOVE "Inserimento avvenuto con Successo." TO 
           TOTEM-MSG-1
                    MOVE MB-DEFAULT-ICON TO TOTEM-MSG-ICON-TYPE
                    MOVE MB-OK TO TOTEM-MSG-BUTTON-TYPE
               WHEN "302"
                    MOVE "Aggiornamento avvenuto con Successo." TO 
           TOTEM-MSG-1
                    MOVE MB-DEFAULT-ICON TO TOTEM-MSG-ICON-TYPE
                    MOVE MB-OK TO TOTEM-MSG-BUTTON-TYPE
               WHEN "303"
                    MOVE "Cancellazione avvenuta con Successo." TO 
           TOTEM-MSG-1
                    MOVE MB-DEFAULT-ICON TO TOTEM-MSG-ICON-TYPE
                    MOVE MB-OK TO TOTEM-MSG-BUTTON-TYPE
               WHEN "401"
                    MOVE "Shell non trovata." TO TOTEM-MSG-1
                    MOVE MB-ERROR-ICON TO TOTEM-MSG-ICON-TYPE
                    MOVE MB-OK TO TOTEM-MSG-BUTTON-TYPE
               WHEN OTHER
                    MOVE TEXT-MESSAGE TO TOTEM-MSG-1
                    STRING "FILE:" TOTEM-MSG-ERR-FILE DELIMITED BY SPACE
                       INTO TOTEM-MSG-3
                    MOVE 0 TO TOTEM-IDX1
                    INSPECT TOTEM-MSG-3 TALLYING TOTEM-IDX1
                       FOR TRAILING SPACE
                    STRING TOTEM-MSG-3(1:TOTEM-MSG-LENGTH - 
           TOTEM-IDX1), 
                       ", FILE STATUS ", PRIMARY-ERROR "," 
                       SECONDARY-ERROR
                    DELIMITED BY SIZE INTO TOTEM-MSG-2
                    MOVE SPACES TO TOTEM-MSG-3
                    MOVE MB-ERROR-ICON TO TOTEM-MSG-ICON-TYPE
                    MOVE MB-OK TO TOTEM-MSG-BUTTON-TYPE
           END-EVALUATE
           PERFORM MESSAGE-BOX-ROUTINE
           .

       MESSAGE-BOX-ROUTINE.
           MOVE 1 TO TOTEM-MSG-TEXT-POINTER
           IF TOTEM-MSG-1 NOT = SPACE
              MOVE 0 TO TOTEM-MSG-SIZE
              INSPECT TOTEM-MSG-1 TALLYING TOTEM-MSG-SIZE FOR TRAILING 
           SPACE
              STRING TOTEM-MSG-1( 1 : TOTEM-MSG-LENGTH - TOTEM-MSG-SIZE 
           )
                 DELIMITED BY SIZE
                 INTO TOTEM-MSG-TEXT, POINTER TOTEM-MSG-TEXT-POINTER
           END-IF

           IF TOTEM-MSG-2 NOT = SPACE
              MOVE 0 TO TOTEM-MSG-SIZE
              INSPECT TOTEM-MSG-2 TALLYING TOTEM-MSG-SIZE FOR TRAILING 
           SPACE
              IF TOTEM-MSG-TEXT-POINTER > 1
                 STRING X"0A" DELIMITED BY SIZE
                     INTO TOTEM-MSG-TEXT, POINTER TOTEM-MSG-TEXT-POINTER
              END-IF
              STRING TOTEM-MSG-2( 1 : TOTEM-MSG-LENGTH - TOTEM-MSG-SIZE 
           )
                  DELIMITED BY SIZE
                  INTO TOTEM-MSG-TEXT, POINTER TOTEM-MSG-TEXT-POINTER
           END-IF

           IF TOTEM-MSG-3 NOT = SPACE
              MOVE 0 TO TOTEM-MSG-SIZE
              INSPECT TOTEM-MSG-3 TALLYING TOTEM-MSG-SIZE FOR TRAILING 
           SPACE
              IF TOTEM-MSG-TEXT-POINTER > 1
                 STRING X"0A" DELIMITED BY SIZE
                     INTO TOTEM-MSG-TEXT, POINTER TOTEM-MSG-TEXT-POINTER
              END-IF
              STRING TOTEM-MSG-3( 1 : TOTEM-MSG-LENGTH - TOTEM-MSG-SIZE 
           )
                  DELIMITED BY SIZE
                  INTO TOTEM-MSG-TEXT, POINTER TOTEM-MSG-TEXT-POINTER
           END-IF

           IF TOTEM-MSG-TEXT-POINTER = 1
              MOVE 0 TO TOTEM-MSG-SIZE
              INSPECT TOTEM-MSG-TEXT TALLYING TOTEM-MSG-SIZE FOR 
           TRAILING SPACE
                  COMPUTE TOTEM-MSG-TEXT-POINTER = 
           TOTEM-MSG-FULL-LENGTH - TOTEM-MSG-SIZE + 1
           END-IF
           MOVE LOW-VALUES TO TOTEM-MSG-TEXT(TOTEM-MSG-TEXT-POINTER : 1 
           )
           .

       MESSAGE-BOX-DISPLAY.
           PERFORM SHOW-MSG-ROUTINE
           PERFORM MESSAGE-BOX-ROUTINE
           DISPLAY MESSAGE BOX TOTEM-MSG-TEXT
               TITLE IS TOTEM-MSG-TITLE
               TYPE  IS TOTEM-MSG-BUTTON-TYPE
               ICON  IS TOTEM-MSG-DEFAULT-BUTTON
               RETURNING TOTEM-MSG-RETURN-VALUE
           .

      *{TOTEM}END

